### ISSUE TITLE
Regular expression (?<=.)\s(?=.) replacement issue

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/madedit-mod#119]
NP++ supports replace All but has the same issue to replace one by one. MadEdit has issues on both mode

Sub issue in #117

**Comment by LiMinggang** [comment]
It's tricky to fix the Replace while you click Replace instead of Replace All. So, let it be. You can use Selection and Replace All if you want to replace some of the matched string

**Comment by LiMinggang** [comment]
Will rollback the fix since it caused issues

**Comment by zhulaojianke** [comment]
嗯，看到了，在0.4.0 alpha3中这个bug修复了 :)

**Comment by LiMinggang** [comment]
这个现在可以替换了
