### ISSUE TITLE
To use a new Regex Engine - Deelx

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#120]
The discussion its in the #117, because the deelx is much more supportful for Chinese search and less bug.

 
我英语不好，请多包涵。在#117的讨论中我建议在MadEdit-Mod中使用deelx正则搜索引擎，但这对于MadEdit来说肯定是个大变动，说不定会伤筋动骨。deelx很稳定，独有的“反向搜索”功能，可以更精确的搜索中文，可以配合他提供的调试器可以编辑复杂的正则表达式，实现更好更强大的的搜索替换功能，而且基本没什么bug。

但需要deelx的开发者史寿伟先生的配合，希望能够顺利吧。阿门。

**Comment by zhulaojianke** [comment]
这是史寿伟先生给我的回信：

Hi 朱欣研，
1.一直都有更新的，只是网站没有更新。github 上有分享，可以看到我的更新历史：  https://github.com/sswater/deelx
2.源代码免费使用，不用担心版权问题
3.另外一款国人开发的编辑软件，使用了我的 deelx 引擎： http://www.everedit.net 


希望能够对这个issue有帮助。他在github上也有更新。
everedit我试用过，也很不错。

**Comment by LiMinggang** [comment]
嗯，everedit做的不错，界面很好看。但是稳定性一般，我试了试他的宏录制功能，点了几下鼠标后死循环了。

**Comment by LiMinggang** [comment]
我简单看了Deelx的编程接口，看着移植起来比较困难，他的接口太简单。例如：只有Match，没有Search，MadEdit用了regex_search和regex_replace。
我本人对正则表达式还是一知半解，需要更长时间研究，暂时你只能两个软件混用了。毕竟Everedit用了deelx这个库

**Comment by LiMinggang** [comment]
我争取先把 #119 修了

**Comment by zhulaojianke** [comment]
真是辛苦您了。

我不想多说everedit在使用上的不舒适，终归大家都很努力和辛苦了哈。现在能够直接调文本行间距，不用安装任何插件就可以完成繁简互换，点击一次鼠标就可以选择整行，使用空心框高亮当前行从而不会干扰书写思路⋯⋯等等能够照顾中文用户体验的文本编辑器，只有MadEdit了，这就是它需要存在的理由吧。

**Comment by LiMinggang** [comment]
这两天的研究结果是基本上不太可能支持Deelx，就如我上面说到的原因，Deelx如果只是做个简单的工具做文本处理是没有问题的，编辑器有很多问题，需要更丰富的接口，例如，Deelx的接口都是基于简单字符串的----虽然是模板实现（能兼容各种类型的字符串，包括unicode），但是MadEdit搜索替换的时候实际上是需要标识字符串在文件中的位置，所以需要用更通用的迭代器（iterator）类型，如boost的接口：
template<typename BidiIter> 
  bool regex_search(BidiIter begin, BidiIter end, 
                    basic_regex< BidiIter > const & re, 
                    regex_constants::match_flag_type flags = regex_constants::match_default);

Deelx的接口只是跟下面这个类似：
template<typename Char> 
  bool regex_search(Char * begin, basic_regex< Char * > const & re, 
                    regex_constants::match_flag_type flags = regex_constants::match_default);

附上Deelx的接口：
MatchResult Match(const CHART * tstring) const;

MatchResult Match(const CHART * tstring, int start) const;

MatchResult Match(CContext * pContext) const;

除非作者愿意重写，这个对谁都是工作量大，会引入很多bug。所以mark成wontfix

**Comment by zhulaojianke** [comment]
没想到这会使您花这么多工夫，那还是不用改了吧。我也打算写一篇MadEdit-Mod的Regex语法简单教程（我得花些时间用MadEdit-Mod做些复杂表达式查找替换的例子），等我写好了（希望不会时间太长……），我把md文件发给您审阅，我尽量用英文写，您如果觉得还好，就挂出去好啦。这对我来说也是一个很好的锻炼机会。我觉得能把现有的引擎玩儿转，玩儿顺手了，换不换更牛掰的引擎就也是无所谓的事情了。

这个您别催我，我平时工作挺忙，得找时间哈。

我对那个玫瑰红色的框很满意哈，无关审美，仅是醒目又不妨碍阅读思考，能同时做到这两点，“当前行高亮”的目的也就达到了，是吧？ :)

**Comment by zhulaojianke** [comment]
试了试，没有搜索结果高亮功能，而使用“查找全部”功能只能列出匹配行，且结果也没有高亮，只能通过“查找上一个”和“查找下一个”的方法让结果高亮，但若对一系列字符串进行匹配测试，得到的结果不很直观，没办法通过截图说明表达式的匹配效果是怎样的。所以，没办法，只能等您做出搜索结果高亮显示这个功能之后，才能做这个语法测试或者简单教程了。

还有，我对照着deelx的说明书中标准Perl语法列表一一试了一次，大概结果如下：
（1）不支持命名组，以及与命名组相关的所有查找和替换功能。因此只能使用表达式自带的命名系统了，也就是\1、\2……这样的系列；
（2）支持非捕获分组。
（3）支持选择表达式，但不支持条件表达式。
（4）不支持递归表达式，但支持后向引用。
（5）支持零宽断言。
（6）不支持\Q ... \E转义字符。
（7）替换中，支持$$表示“$”，支持$&（与$0是一样的，但MadEdit-Mod里不支持$0，所以这个$&还是很有用的），支持$`和$'，不支持$+和$_。
（8）支持匹配模式修改符。

另外，\A...\Z的结构我还不会用，注释模式（(?#xxx)）我没有试，一些更高级的语法（如平衡组）我也没有掌握呢，大概就是如此吧。

我觉得最大的遗憾是不支持条件表达式，其他的都可以用稍微复杂一些正则表达式进行变通，唯有条件表达式，(?(xxx)yes|no)这种根据捕获组的情况确定匹配方案没办法实现。一个亮点是MadEdit-Mod支持$`和$'，这样即便匹配得不够准确也能做出让人满意的替换。

还有就是我发现了一个神奇的现象：
我用
.*g
匹配结尾为“g”的单词，比如说finding，然后多次按搜素面板中的“查找上一个”和“查找下一个”，没按一次都会出现不同的匹配，一会儿是贪婪模式的，一会儿是勉强模式的，还有“排除模式”的（也就是除了“g”之外其他的都匹配），多按几次就可以在这三种模式之前进行切换，唯独不能匹配finding整个单词，但当我使用替换的时候，使用“替换全部”，就可以匹配整个finding了。
这真的是很神奇。按说.*g是典型的贪婪模式匹配，应该一次就匹配finding的。

总的来说，MadEdit-Mod在文本编辑中，如果没遇到十分乱七八糟的文本，现在的正则引擎是可以承担工作的，但如果要现在的引擎处理html源文件或者其他程序语言的文件，我感觉确实有些捉襟见肘。

**Comment by zhulaojianke** [comment]
呵呵，不知道以上测试的能不能交作业了哈……

**Comment by LiMinggang** [comment]
感谢你细心测试，“结果高亮”还没实现。.+g开一个issue来track吧，以前用正则比较少，也缺少热心用户，所以这部分质量堪忧。

**Comment by zhulaojianke** [comment]
.+g的问题只有在搜索模式并使用“查找上一个”和“查找下一个”的时候才会发生；如果用“查找全部”，因为结果没有高亮出来，而是在搜索结果窗口中列出了含有匹配字符的行，所以看不出到底是怎么匹配的。我觉得还是要等“搜索结果高亮”的功能做出来之后才能比较系统的测试这个问题——说不定还能找到其他类似的问题，多找几个案例之后，才能更准确的判断症结在何处吧。

正则表达式在贪婪模式下可以对一个表达式进行反复多次的匹配，从而拿出满足所有表达式的匹配结果（而且是最大的匹配结果。如果需要最小的匹配结果，就要用勉强模式），尽管它不会进行“前向搜索”，但对一段文本进行反复搜索的情况肯定是会发生的（因此对搜素条件约束不充分的正则表达式是会陷入搜索死循环的，deelx的“熔断”也是防止发生搜索死循环）。

条件表达式正是基于这种反复搜索的机制，先对文本进行预搜索匹配“条件组”，然后再根据条件判断结果进行第2次搜索得到相应的匹配结果。

另外，deelx引擎可以进行反向搜索（前向搜索）的。

**Comment by LiMinggang** [comment]
完全支持正则对编辑器来说是不现实的，编辑器只是匹配其中的一种，估计你说的那些复杂方式，必须用专门的正则表达式工具才行。

**Comment by zhulaojianke** [comment]
嗯，或许确实如您所过吧。EditPad Pro倒是一个充分使用正则表达式的编辑器，可也确实用起来太麻烦，用它编辑文本的工作效率太低了。现在MadEdit-Mod的正则搜索能力在处理一般文本（和带有一定格式的程序语言文本）时够用了。

还有“.”能够代表“换行符”实际上是正则表达式中的“单行模式”，我感觉现在的搜索引擎（EMAC?）下一步升级可能会引入“多行模式”（^和$代表行的首尾而不是字符串的首尾），如果和我猜测的差不多的话，咱们继续使用现有的这个引擎就和比较专业的正则表达式搜索工具没什么区别了。 :)

**Comment by LiMinggang** [comment]
也感谢你在这方面做得贡献，我的正则表达式的了解太弱了，所以一直没有改进MadEdit的这个方面----不懂+不用，所以就Let it be

**Comment by LiMinggang** [comment]
希望你把你发现的问题都提出来，也许修复不了，但是努力改进呗。

**Comment by zhulaojianke** [comment]
哈哈，是，谢谢您的理解。我也是怕频繁在这里提issue会使您心烦。我是这么想的，如果能够实现"搜索结果高亮"、“按书签递进搜索”、“用ctrl键可以实现光标多点定位和多选”、“可以使用‘+’/‘-’进行相对行数、列数的跳转”（包括快速搜索工具栏的改进）等这些功能的话（以后还会有补充），MadEdit-Mod对我来说就是最好的文本编辑器了（而且在所有编辑器中它是独特的有个性的，不可替代的），一段时间内也不用再为其做较大的升级了。我也晓得实现这些功能需要您的很大的努力和时间付出，而我却帮不上更多的忙。

我觉得像多窗口split、导航缩略图等窗口stock、文本折叠等等这些功能都很强大，但在文本编辑工作中并不是必需的，而且可能会降低编辑器的运行性能，我感觉在这一点上您和我的想法是相同或相近的吧？:)

**Comment by LiMinggang** [comment]
用ctrl键可以实现光标多点定位和多选，这个难度大一些，目前没想清楚。

**Comment by zhulaojianke** [comment]
突然明白了，那个.*g在“查找上一个”和“查找下一个”的神奇表现并不完全是bug，而是像您所说的“正则只能正向查找”，当我使用查找上一个时，实际上是从当前光标所在点向前查找，而一次查找之后，光标的位置已经变了，所以第二次查找的结果就和第一次不一样了，同理，查找下一个是在当前光标所在位置向后查找，查找一次之后光标位置也变了，嗯，所以才会出现每次点击得到的查找结果不一样的情况哈。

这里可能是bug的，我感觉应该是我首次点击“查找上一个”或“查找下一个”的时候，至少应该发生一次正确的匹配——但并没有发生。再之后的匹配就都和光标实际所在位置有关了。

**Comment by zhulaojianke** [comment]
我查看了MadEdit-Mod的Help文件中的“RegexReference.html”以及您在#117中给出的http://www.boost.org/doc/libs/1_60_0/doc/html/xpressive/user_s_guide.html，发现在xpressive中是支持“命名组”的：

(?P<name>stuff)

mark_tag name(n);
...
(name= stuff)

Create a named capture.

(?P=name)

mark_tag name(n);
...
name

Refer back to a previously created named capture.

但我在编辑器的查找面板中使用这个格式进行命名组的查找，却返回：
![](http://i4.tietuku.com/7105640eda51bb13.jpg)

还有，您在#117提到的ECMA，是不是指这份帮助文件中替换部分所说的“ECMA-262”格式呢？如果是如此，多少就有些线索了，从帮助文件中看，只有Perl格式支持命名组的替换，其他的ECMA-262和Sed格式都不支持。

**Comment by zhulaojianke** [comment]
哦，这里支持了Markdown，所有的尖括号包围的内容都被认为是html标签了……
我再试试：
```
(?P<name>stuff)

mark_tag name(n);
...
(name= stuff)

Create a named capture.

(?P=name)

mark_tag name(n);
...
name

Refer back to a previously created named capture.
```

**Comment by zhulaojianke** [comment]
deelx不能用的话，我再推荐一个，python自带的正则表达式，我感觉MadEdit-Mod既然能够用Python做宏，用Python自带的正则也可以了吧。

https://docs.python.org/2/library/re.html#contents-of-module-re

我是看了上面的帮助，感觉除了\Q...\E结构不支持之外，其他的都做得很好了。最重要的是它支持命名组，这样就可以做条件表达式了，有了条件表达式，在搜索的时候的准确性就会提高很多。

希望您能考虑 :)

**Comment by zhulaojianke** [comment]
嗯，上面的那个是Python2.7的，我又看了Python3.5的，这部分基本没什么变化。不知道换这个表达式引擎会不会有很多工作量了。

**Comment by zhulaojianke** [comment]
而且我试了一下Python的正则表达式，它的\w是包括汉字的，这个很难得了。

**Comment by LiMinggang** [comment]
我看看再说，RE模块因为尺寸问题，从内嵌的python中移除了

**Comment by zhulaojianke** [comment]
呵呵，我现在基本习惯了MadEdit-Mod的正则表达式了，因为习惯了，也就没有再感到哪里不方便的了。

**Comment by LiMinggang** [comment]
嗯，python的regex实现方式应该是跟第一个建议差不多：纯C的，需要很多适配，用MadPython编程方式好用，但是真的跟搜索对话框和MadEdit结合比较别扭
