### ISSUE TITLE
A replace count bug in the 0.4.0 preview version

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#124]
When I search and replace many characters, in the old version, MadEdit-Mod could return a correct number that it has found and replaced in a pop-up window, but in 0.4.0 preview version, it only return "1"!

在0.4.0预览版中，不管发生了多少次搜索替换，其后弹出的结果计数窗口的返回值都是“1”。

**Comment by LiMinggang** [comment]
You have to use the updated version of 0.4.0 preview which has been put in te Preview directory.

**Comment by LiMinggang** [comment]
没有疑问我就close这个thread了

**Comment by zhulaojianke** [comment]
嗯，没问题了哈，谢谢哈！
