### ISSUE TITLE
Another bug about number highlight in 0.4.0 preview

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#127]
Thank Mr Li for correcting the number highlight bug, now the letters after the number is in plain text color rightly, but when some letters befort the number, the whole string will be recognized as plain text, such as follow:

![](http://i11.tietuku.com/7b5932d50e5d2257.jpg)

-- the number become black text.

希望能够修复这个bug。谢谢哈。

**Comment by LiMinggang** [comment]
这个东西我加了限制，只对Plain Text生效，不然会干扰程序员

**Comment by zhulaojianke** [comment]
也就是说这个bug会被修复的，是么？

**Comment by zhulaojianke** [comment]
现在使用alpha3，最大的烦恼就是这个了。数字之后有英文的情况已经很好，但当数字之前有英文的时候，数字不能高亮，在浏览文本的时候，很容易漏掉信息。

**Comment by LiMinggang** [comment]
已经修复了
![2016-01-16 17_18_29-madedit-mod - 1_](https://cloud.githubusercontent.com/assets/4847132/12371661/82150112-bc75-11e5-9bb0-b32340fa2eee.png)

**Comment by zhulaojianke** [comment]
不错！这个要赞哈！
