### ISSUE TITLE
Wish an Enhanced ctrl+g & ctrl+shift+g and more ……

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#128]
Now the ctrl + g and ctrl + shift + g are worked like other text editors, that the ctrl + g is to jump to a line with the line number is given, and the ctrl + shift + g is to jump to a position with the character number is given. But in most circumstance, the use can't remember the line number or the character number that he need to jump to edit, and the numbers of line and character could change when put some editing on the text file, so the ctrl + g and ctrl + shift + g are not very useful now.

If we can use "+" or "-" on the line jump, for example, I want to jump 5 lines after the cursor position, I will input "+5", and not need to input the exact line number to it. 

And use the ctrl + shift + g to jump colume only, not the character number, but the colume number, also use "+" or "-".

中文：

使用ctrl + g和ctrl + shift + g这两个快捷键在文本中进行跳转在很多编辑器中都是通用的，但因为行号是相对固定的，字符号码也是相对固定的，当我对文本进行一定量的编辑之后，我所需跳转的文本行号、字符号就都会改变了，此时使用这两个快捷键进行跳转就很不方便。

我的这个灵感来自于word，在word中，ctrl + g和ctrl + shift + g同样用于按指定行号或字符号进行跳转，但它还提供一个“+”或“-”的功能，就是说当我不能确定我需要跳转到的具体行号时，使用“+5”或者“-5”，就可以相对的向前或者向后跳转5行。而我感觉ctrl + shift + g使用字符编号进行跳转不如使用“列编号”跳转实用，在word里也是使用列编号进行跳转的，在一行之中，列跳转就一目了然了，它同样使用了“+”或“-”的方法达到快速定位的目的。

MadEdit-Mod的状态栏中给出了行数、列数和字符位置，这在确定跳转数值的时候很有用，如果能够加上“+”或“-”这种相对编号的功能，就更方便了。这样我如果需要跳转到一个位置，只需要4次跳转就可以完成，第1次跳到大概的行号处（停在行首），此时在编辑框中已经可以看到真正需要跳转的行的位置了，我再用“+”或“-”跳第2次，然后横向跳若干列，再“+”或“-”跳若干列，就可以定位了。

如果是这样，就可以把ctrl + g和ctrl + shift + g这两个功能合并在一个快捷键里了，比如合并到ctrl + g快捷键中按下快捷键，弹出一个对话框，分两行，上面是跳转行数，下面是跳转列数，使用tab键在两个文本框之间切换，当完成一次跳转之后，行列数自动清零（或者对话框清空），如果我仅跳转若干行，我在行数中填入数字，列对话框留空即可。关掉这个对话框，按esc键即可。

此功能如果配合搜索定位（比如快速搜索工具栏中的快捷键），就可以在大文档中进行快速而准确的跳转了。

还有就是快速搜索工具栏中也可以使用“+”或“-”的功能，现在使用的是上下箭头来实现向前查找和向后查找，如果改为两个输入框，使用tab在输入框之间切换，就可以了。设置好后面几个复选框的选项之后，在第1个输入框中，输入我所要搜索的文本或者表达式，在第2个输入框中输入“+5”或者“-5”，然后按enter，就可以达到跳转的目的。

我不知道您开发使用快速搜索工具栏的目的是什么，我在使用的过程中，一般遇到搜索，都是使用ctrl + f唤出搜索面板，而不会使用f8调用快速搜索工具栏（还有一个原因就是我使用有道翻译软件，f8是有道的“屏幕取词开关”的快捷键）。我用快速搜索工具栏就是为了在文本之间跳转用的。

快速查找工具栏就简化为如下的形式了：

关键词/表达式：___________；+/-：_____________；OK（enter键）；复选框、复选框、复选框……

如此在使用快速查找工具栏的时候，就不必用鼠标点击那个向上或者向下的箭头了，如果“+/-“留空，就默认是”+1“，查找下一个匹配，多按几次enter键就可以了。如果怕这里的enter与编辑框中的enter冲突，可以设快捷键为”shift + enter“（或者用户自定义，比如说经典的f3）。

不知道这个功能实现起来会不会很麻烦，我总是这样麻烦您，真是很惭愧啊。

我是觉得一个文本编辑器只要把”搜索替换“和”定位跳转“这两点做好了，它就是一个卓越高能的编辑器了。 :)

**Comment by LiMinggang** [comment]
+/-在ctrl+g的时候比较简单，快速搜索我觉得不是很方便，毕竟那个是个简化的搜索功能，比如我要从+1切换到-1，先得点鼠标到输入框，然后删除+号，在输入-，不是特别方便。

ctrl+shift+g，我试出来的是统计功能，不知道你说的是啥功能

**Comment by LiMinggang** [comment]
复杂定位建议你使用宏，其实你只要知道Python里面的循环和if-else这种语法就可以了

**Comment by zhulaojianke** [comment]
哦，我把ctrl+shift+g绑定到了“跳到文件位置”这个功能上了（在“查找”菜单）。

我觉得可以把文本输入框设定为“覆盖”式的输入，也就是每当我点击输入框的时候，输入框内的已有文字就被清空，这样就不会发生您说的需要进行删除的操作了。

这类似与Excel中的单元格的输入方式，我在单元格里输入一个数，当我再次点击这个单元格进行输入时，自动就把前面的那个数给抹掉了。

我感觉一般用户的心理是，如果能够比较方便的调出全面搜索功能面板的话，就不会使用简单的搜索功能了——何况MadEdit-Mod的全面搜索功能窗口所提供的设置和选项并不复杂，用户会更倾向于使用这个搜索框——除非用户更喜欢使用鼠标去选择“快速搜索工具栏”里的复选框。

所以我想如果把这个“快速搜索工具栏”的主要功能定位从“搜索”转化为“跳转”，可能会提供更多的便利。

如果使用“覆盖式”的输入框，那么我用“f8”定位到工具栏的第一个输入框，输入所需搜索的字符或者字符串，然后按tab键跳到第二个输入框，输入“+n”或“-n”，然后按enter，整个工作流程也是很顺畅的。

我的这个想法是这么考虑的，当用户需要从一个编辑位跳转到另一个编辑位，最自然的想法就是他要去找某个字符或者字符串，如果能够更快的找到那个位置，自然对用户是更有利的了。

如此呢，通过“快速搜索工具栏”实现的跳转，并不是使某个字符或者字符串高亮，而是使光标停留在目标字符或字符串的前面（或者后面），然后紧跟着就可以进行新的键盘输入了。

我的这个解释您看可以么？

**Comment by zhulaojianke** [comment]
另外，在“快速搜索工具栏”中如果想在已有输入的基础上增加一个数，或者进行一些修改，用鼠标双击输入框就可以了。这样就跟Excel的输入模式一样了，应该会很容易让用户适应的。

**Comment by zhulaojianke** [comment]
其实我不会用python……用编程来实现跳转这也让我感觉怪怪的（汗）。

还有，ctrl + g是跳到指定行号，当有一大段话，而且使用了折行功能，此时跳转过去并没有达到定位的目的，我看状态栏里对折行之后的大段文字还显示有”次行“，不知能否在ctrl+g中把次行也算进去，或者在”+“或”-“的跳转中算入”次行“，这样”行跳转“才能充分的发挥作用吧。

**Comment by LiMinggang** [comment]
对快速搜索栏的改动还是比较保守，这里先把ctrl-g和ctrl-shift-g做了

**Comment by LiMinggang** [comment]
还是保持快速搜索的简单最好。

**Comment by zhulaojianke** [comment]
好吧，听您的。
