### ISSUE TITLE
经验或者是个bug：条件合并行的正则表达式

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#130]
在处理书目时，遇到了如下的情况：

……
[5]
some book name
出版机构：Kluwer Academic Publishers Group
作者：Costa, L.Da; etc.
出版时间：1986
电子图书：否
ISBN：9780860105480
开本：290mm × 220mm
页数：246
数据源：图书文献
……
此时，我希望把编号[5]与书名放在同一行，而其他的分行保持不变，如果一一选择需要的合并的行，进行ctrl + j的操作工作量就大了，使用正则替换吧。

如果按照一般正则表达式的写法，我应该写
查找：(?<=\d])\r\n
或者使用单行模式，“.”代表换行符的模式，写成：(?<=\d]).
替换为空格： 

但在MadEdit-Mod中以上表达式不起作用，弹出框中会显示发生了多少次替换，但实际上在文本中什么也没发生。此时就得根据MadEdit-Mod的正则语法特点进行一些变通了。

查找：(\d])\r\n 或者：(\d])..
替换为$1空格：$1 

在MadEdit-Mod中，直接将所有的\r\n都替换为空格是可以做到的，但当对这些换行符使用前向零宽断言进行修饰时，MadEdit就不能正常运行了，此时就要通过“扩大匹配范围”的方法将“断行替换行为”变为“普通的字符替换行为”。

我感觉这是一个bug，希望作者明察。

**Comment by LiMinggang** [comment]
这个跟 #119 是一类问题，已经修复了ReplaceAll。单个Replace是一个棘手问题，涉及编辑器的实现悖论，NotePad++在单次替换也是同样的问题。
如果你是用ReplaceAll，请再次更新版本。
单次替换也许等实现了“高亮搜索结果”后可能能解决。

**Comment by zhulaojianke** [comment]
啊，太棒了！以后再编辑文本格式的时候就更方便了！谢谢哈！

**Comment by LiMinggang** [comment]
横滚的功能也完成了

**Comment by zhulaojianke** [comment]
嗯，在alpha3中试出来了，很爽哈！

shift横向滚动功能最常见的使用场景是较长段落的时候，在折行模式下，要看自己的文章是怎么分段的很不方便，尽管可以从左边的行号上看出来，但还是没有“不使用折行”模式来得更直观，一行就是一段，点击行号选择整行，一选就是一行，很清楚明白，此时如果要对段落进行编辑，shift+滚轮就发挥作用了。
