### ISSUE TITLE
Hope MadEdit-Mod could Autosave, Backup files, and have Autolink funciton

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#135]
When a file is very large, and has been made many edits on it, an misoperation or a PC shutdown is disastrous for the user, and maybe damage the files. 

Another function "Autolink" is not necessary. I found using the MadEdit-Mod management the files on computer and URLs will be very easy when use the search and replace function. So I hope MadEdit could add a Autolink function on the file path and the URL text, and when I click them, the files will be opened by the default explorer.

当用MadEdit-Mod处理较大文档并进行了很多操作之后，还没有及时存盘，此时如果发生一次误操作或者电脑断电，这对于用户来说无疑是场灾难。如果MadEdit-Mod可以对所编辑的文件自动存盘（比如说每10~15min一次，由用户在“选项”菜单中设置），并进行备份（使用一个用户自定义的文件夹，并让用户指定哪些标签里的文件需要备份），这将允许MadEdit-Mod可以编辑更大的文件，进行更复杂的文字工作。

Autolink功能不是必须的，仅是我感觉当我在MadEdit-Mod中插入了URL链接或者文件绝对路径之后，如果文本自动就给加上了超链接，那么我就可以使用MadEdit-Mod更方便的进行文档资料的管理，比如说给我一部分挑选出来的文件写内容综述。用文本编辑器做这件事儿的好处是可以在梳理文档的过程中，充分利用搜索和替换功能，方便在“搜索结果窗口”建立文档索引，梳理思路。而且还可以通过这个功能把若干个txt文档互联起来，形成wiki式的阅读。当然这个功能不是必须的，您可以不必考虑哈——我还是典型的word思维，真不好意思 :(

**Comment by LiMinggang** [comment]
Auto URL这个基本不太可能，这个东西基本都是用Rich Text实现的，而目前所有的文本编辑器都是Plain Text。这个真的需要Word，至少也是WordPad

**Comment by zhulaojianke** [comment]
是，您上次一说我的建议有些接近word提供的功能了，让我反省了不少。

看到0.4.0出炉真是高兴，能够看到我能够为这个软件做一些贡献，还真是有些小兴奋 :)

此次我仔细看了“help”文件夹里的内容，发现已经有对正则表达式的全面介绍了，哪些功能支持，哪些功能不支持，里面说得很明白了。不过里面大多是和MadEdit程序相关的内容，而实际上这些功能怎么用确实是缺少示例。我跟您说过等有了“搜索结果高亮”的功能之后，我打算把这部分给补上，到时候必须写英文的么？

**Comment by LiMinggang** [comment]
中文就好，我看看有没有空翻译成英文。文档都是七拼八凑（有些就直接从网站上扒过来的），没时间和精力放上面啊。

**Comment by zhulaojianke** [comment]
发生了一次“未响应”，主要是我在“未响应”前也没存盘……结果真的挺严重的。我仅仅是做了一次正则替换，结果MadEdit-Mod就死在那儿了。

所以真的非常非常希望这个Autosave的功能能够实现呀。

**Comment by zhulaojianke** [comment]
这不是第一次“未响应”了，算起来是第3次了，不过前两次我还存过盘，损失不是很大。都是在编辑比较大的文档的时候，然后用了一次查找或者批量替换，然后就“未响应”了。 :(

**Comment by LiMinggang** [comment]
Autolink没啥思路，dropped
