### ISSUE TITLE
Use shift+middle mouse wheel to scroll horizontal in the search result window

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#136]
When I dock the search result window on the right, it will be long and thin and the part of the result text will out of the window I must use the horizon scroll bar to look through them. If use the shift + middle mouse wheel to scroll result window horizontally, it will be more conveniently to the search window user.

现在用上靠侧边的搜索结果窗口，非常有幸哈，谢谢您了。但此时搜索结果窗口是瘦长的，我需要水平滚动窗口才能看到搜索结果后面的文字，此时如果也能够使用shift + 鼠标滚轮的方式进行水平滚动就方便多了。 :)

**Comment by LiMinggang** [comment]
试了一下，这个有点意思，如果结果不多，滚轮自动是横滚，如果结果多了，就变成竖着滚动了

**Comment by zhulaojianke** [comment]
呵，我感觉资源浏览器的设置也是这样的。

如果是短行的话，当鼠标停留在上面时，也可以看到全行的信息，而如果是长行的话，就需要横向滚动了。 :)

**Comment by LiMinggang** [comment]
Fixed
