### ISSUE TITLE
The “collapse all” bug

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#140]
When the mouse has select one tree in the search window, and I use the "alt + -", it only collpase the tree which be selected. And When I select on line result and press "alt + -", nothing happened. And then I can't use the collapse all hot key anymore, because the select state is always in active even when I switch window between the result window and edit window.

Using the "collapse all" command after right click is work well.

当我浏览点击了结果窗口中的项目之后，选择的焦点就一直处于我所选择的项目上，当我选择了树标题时，使用“alt + -”仅收缩了当前的树，而其他的树并没有收缩，当我选了某一条搜索结果时，使用“alt + -”则什么都不会发生。

使用右键中的“折叠全部”命令还是很好的。

**Comment by LiMinggang** [comment]
两者用的应该是同一功能，不应该有差异，我本地试了你这几种情况，都好使，你看看你那里是不是有热键冲突？修改热键试试

**Comment by zhulaojianke** [comment]
我查了我的快捷键设置，alt + -是空的，没有被其他的程序命令使用。而且我还发现使用数字键盘上的“-”可以得到我上面描述的结果，而使用主键盘上的“-”时，即使是上面那种选中了当前树的情况，也是什么也不会发生。或许确实我这里是一个个例吧。不过有这么一个“collapse all”的命令真的方便了很多哈！在编辑的时候，我的搜索结果窗口里的行数往往会比编辑窗口中多得多，如果没有这样的命令，真是烦死人了。

还望考虑一下#136、#137、#138、#139，这几个功能结合到一起，搜索结果窗口就可以发挥出非常强大的作用了。

谢谢哈！

**Comment by zhulaojianke** [comment]
比如说这样，我通过搜索可以很方便的建立一个文档导航栏：
![](http://i4.tietuku.com/549d7b3300f1693b.jpg)
这就是我上次说的自定义“书签浏览窗口”的意思，不知道其他用户会怎么用它，这个“搜索结果窗口”对我真的是太重要且方便的一个设定。

**Comment by zhulaojianke** [comment]
嗯，从上图中也可以看出：
（1）当我仅搜索一个文件的时候，搜索树的标题始终都是这个文件的绝对路径，当在折叠的状态下时，根本不会知道这个树是通过什么关键词或者表达式建立起来的。
（2）目前搜索树中的内容格式是：
行（行号）： 行内容
但我感觉第1个“行”字和是可以省略的，包围行号的括号“（ ）”也可以省略，可以节约一些“搜索结果窗口”的空间，尤其是当我把搜索窗口调的比较窄的时候，前面的这些行信息占得空间很大，而我实际要浏览的内容却要通过滚动条才能看到——这使我不得不把“搜索结果窗口”调得宽一些，而这样的话，无疑是缩小了编辑窗口的面积。

**Comment by LiMinggang** [comment]
#136、#137、#138、#139 这几个应该都可以做，以前没人提需求，所以没有去增强。

**Comment by LiMinggang** [comment]
热键问题比较奇怪，我试了两台机器，都没发现这个问题，如果你能找到更详细的过程信息，也许我能说出点啥来，现在只能告诉你，这几处（鼠标右键，菜单和快捷键）最后都是汇聚到同一行代码处理的。

**Comment by zhulaojianke** [comment]
还有#125的对标签行进行搜索，如果这个功能做好了，也放在“搜索结果窗口”的右键菜单里，点击的时候调出搜索面板，并已把“对标签行进行搜索”的复选框选上了，这样我感觉是否要“书签浏览窗口”就不是大问题了。

我是想做一个“如何更有效的使用MadEdit-Mod”这样的指南（How To Use the MadEdit-Mod more Efficently），而不仅仅是“如何使用MadEdit-Mod的正则表达式”。嗯，还是要等“搜索结果高亮”的功能具备了，才能动手——不过现在的0.4.0已经非常出色了，我已经很有理由说服我的笔友们尝试用这个文字编辑器了哈！

**Comment by LiMinggang** [comment]
多谢支持，文档用中文也行。

**Comment by LiMinggang** [comment]
行（行号）： 行内容
这个似乎是惯例，NP++也是（少了括号）

**Comment by zhulaojianke** [comment]
如果有了方便的横向滚动，每行的前缀长一些也不会妨碍什么了。:)
