### ISSUE TITLE
如何修改.syn文件使西文字母的颜色可以自定义呢？

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#142]
我希望文档中的西文字母的颜色和中文的颜色区分开，但不知道此时应该如何修改.syn文件了，还望您能拨冗帮忙哈。

**Comment by LiMinggang** [comment]
没有一个完美方案，但是，你可以利用SpecialWordPrefix
把这写成
SpecialWordPrefix=a b c d一直到z，然后是大写
SpecialWordPrefix=a b c d e f ...... z A B C ...... Z
然后你去调整SpecialWordPrefix的颜色

**Comment by zhulaojianke** [comment]
这样有一个问题，就是所有跟在英文字母后面的中文字符和数字都跟英文字母会是一个颜色了。

在MadEdit-Mod中有3个变量是不管什么情况下都可以自定义颜色的，text，number和delimiter，如果能够出一个text1、text2或者delimiter1、delimiter2这样的变量就可以了。这样我把所有的英文字母都设置成delimiter，然后单词的前后没有空格紧跟着其他字符的时候，也会及时变色。您看看能否增加一个这样的变量呢？

**Comment by zhulaojianke** [comment]
OK了哈！谢谢您哈！我一开始对Prefix发生了误解，我还以为这是定义前缀的，也就是说当一行中的某处出现了这个前缀，那么之后的所有字符就都会随着前缀变色。现在看不是这样的哈！太好了！！！非常感谢！

**Comment by LiMinggang** [comment]
前缀都是对单词（word）来说的

**Comment by zhulaojianke** [comment]
如此设置之后，#127的问题就又回来了，当字母处在数字前面的时候，数字就随着字母改变颜色了。

**Comment by LiMinggang** [comment]
这个涉及到中文分词问题，其他语言都是以空格等分词，中文没有分词一说

2016-01-20 14:27 GMT+08:00 zhulaojianke <notifications@github.com>:

**Comment by LiMinggang** [comment]
只影响数字么？贴图给我看看中英文混合以及字母数字混合的样子

**Comment by zhulaojianke** [comment]
就是这样的：
![](http://i8.tietuku.com/a4bae6c2a6929ab8.jpg)
仅在数字前面是英文的时候出现了问题。

我现在一般使用在英文后面加上连字符“-”，但并不是所有的英文数字组合都适合加上连字符的。

**Comment by zhulaojianke** [comment]
我不知道这段的源程序是什么，但我感觉可能与正则表达式有关系，因为MadEdit-Mod中的\w不包括中文，仅包括[1-9a-zA-Z_]，而下划线我已经在.syn文件中设置为delimiter了，所以这种现象在我这边对下划线不起作用。

我是感觉SpecialWordPrefix仅对\w起作用，如果改成让它对[a-zA-Z]起作用，应该就没问题了。

**Comment by zhulaojianke** [comment]
呵呵，另外我建议您学学正则吧，半个小时就能学会的，不必很痛苦哈。:P

**Comment by LiMinggang** [comment]
这个跟正则没关系，MadEdit的正则只用于查找替换

**Comment by LiMinggang** [comment]
![2016-01-22 12_22_18-madedit-mod - 1_](https://cloud.githubusercontent.com/assets/4847132/12502369/e75b883e-c102-11e5-9712-1111f2314550.png)

**Comment by zhulaojianke** [comment]
天哪，您是怎么做到的？教教我好吗？ :)

**Comment by zhulaojianke** [comment]
您这个太完美了！

**Comment by LiMinggang** [comment]
要改code，syn文件你已经改好了，但是code里面有一个bug，上面这个是修复这个bug的

**Comment by zhulaojianke** [comment]
0.4.0真的非常好用！不方便单开Issue，但我又禁不住要表达感谢。现在除了调格式和插图表之外，其他的文字上的活儿我都转到了MadEdit-Mod上了。谢谢您哈！
