### ISSUE TITLE
A bug in the "quick search bar"

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#143]
The function of immediately match when input something in the "quichsearch bar" is very good, but when use regex, when input a "\" or delete the character after a "\", the MadEdit-Mod will pop-up a error warning window, and I must close it before continue to input or delete. It there anyway do not let the warning window pop up?

快速搜索工具栏使用起来很方便，但是当使用正则搜索的时候，每当输入或者删除到“\”（正则的转义字符）时，都会跳出错误警告窗口，我只有关掉它之后，才能继续输入或者删除，等下次输入的时候又会蹦出来。

当我要输入类似于： \w+(\(\d?\))\w*这样的表达式时，这么多次关闭警告窗口的操作就很恼人了。

能否把这个跳出警告窗口的功能关掉？或者让它在遇到“\”时不会弹出来呢？

另外，您在help文件中的这一句：* Up/Down to the line above/under the selection if selecting是什么意思呢？

**Comment by zhulaojianke** [comment]
···
 \w+(\(\d?\))\w*
···

**Comment by LiMinggang** [comment]
这个快速搜索栏的初衷是输入便开始搜索，正则这个情况当时确实没考虑到。
