### ISSUE TITLE
Hope to add a history files bar, and build a new file by double click on the blank area of the Tab bar

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#144]
现在用MadEdit-Mod处理的文件越来越多了，但又不想使它在启动的时候一次打开过多的文件——现在看当启动的文件很多的时候，MadEdit-Mod就有些慢了。

需要打开的往往只有目前处理的主文件，以及辅助的临时文本文件，这两个，但是还有一些辅助的文件时不时要打开查看或编辑，比如说缩略词表、名词解释表、文件夹目录导出的txt文件、其他软件的config文件等等，都是需要时常查看但又不怎么修改编辑的，没有用的时候就关掉了。

当需要再打开的时候，需要在“文件”菜单栏里找“最近开启的文件”，这个操作在经常需要访问历史的时候就有些繁琐了。如果有一个工具条放在顶端，是一个下拉框，当点击的时候，就出现一个下拉列表，里面就是文件编辑历史（类似于搜索面板中的搜索历史下拉列表，特别人性，特别好用！），直接选择点击打开就可以了，这样就方便了很多。

嗯，我这个灵感来自Mathcad，它有一个参考书下拉工具栏，有什么常用的计算公式、常数之类的，做成电子书之后放在指定文件夹里，随时可以调出来查用，挺方便的。不过它也不支持快速访问文件历史……

---

现在的标签栏关闭文件很容易，可以批量关闭，但是新建文件就需要按“ctrl + n”了，如果能够在标签栏的空白地方鼠标双击即可新建一个文件，整个操作就顺畅得多了。

这个灵感来自IE的操作，以及OfficeTab，双击新建标签，感觉很顺畅。

---

还有我刚发现拖动标签就可以做split分屏，这个很爽哈！

**Comment by LiMinggang** [comment]
你有没有搞艺术的朋友能给这个“最近开启的文件”设计一个图标？

**Comment by zhulaojianke** [comment]
我试试看吧，我也是绘画拿过省奖的 :)

**Comment by zhulaojianke** [comment]
也就是说，把现在的“打开文件”的那个图标上面的绿箭头去掉，然后把“撤销”图标的那个逆时针箭头缩小一些叠加到那个“文件夹”上，就可以很明白的告诉用户，这是在已经打开过的一系列文件中回滚，也就是打开历史文件了。

**Comment by LiMinggang** [comment]
额，现在的图标文件都是xpm格式的，是一种文本描述的点阵格式，而且分辨率很低。我自己是缺乏艺术细胞，你可以从网上搜一下免费的图标去改。

我先随便找一个，给你一个新的preview版本吧。

**Comment by zhulaojianke** [comment]
呵呵，就是这样的呀
![](http://i13.tietuku.com/13a72deb13b6a847.png)
我的显示器的分辨率有些大，不过图标中的像素点阵应该不会变吧。

我就是把现有的打开文件的图标竖过来，然后把那个绿色的箭头，搜索的绿色像素都按灰度改成了相应的红色，我感觉和现在MadEdit-Mod的图标风格还是蛮一致的 :)

**Comment by LiMinggang** [comment]
大小没关系，比例是16*15，我自己有工具可以转换成xpm

**Comment by LiMinggang** [comment]
我正在上传，你一会去下载
New: Create a new file by double click on the blank area of the Tab bar #144
New: Full screen/Post-It Mode support #147
New: Always on the top #146
New: Use mouse wheel to scroll and activate the tabs on the tab bar. Click on any of the File name Tab to set the focus to the tab bar. Then use mouse wheel to scroll.The file would not be activated automatically #148
New: History files bar, open recent file list from tool bar #144
New: Save user config of "quick search bar" #149
Fix: A bug in the "quick search bar" #143
Fix: A bug in replace all introduced by code change for #119
Fix: An issue of wxWidgets while scroll result window by mouse wheel
Fix: Not allow to change the size of SearchReplace dialog

**Comment by zhulaojianke** [comment]
嗯，那您看我上面上传的那个图标可以么？

**Comment by zhulaojianke** [comment]
您这里“Fix: Not allow to change the size of SearchReplace dialog”，我试了发现还是原来的样子，现在仍然是1行的搜索替换对话框的空间。

还有，history files bar能否与快速搜索工具栏做到一起，而不和现在的“标准工具栏”放在一起。因为标准工具栏里的所有按钮都可以设置为快捷键，用户可以把这个工具栏引擎隐藏起来的，而快速搜索工具栏则只能在打开的时候才能发挥作用，同样这个“history files bar”也是只有调出这个工具按钮的时候才能发挥作用，把这两个性质一样的工具放在一个工具栏里，要更合理一些吧。

**Comment by LiMinggang** [comment]
Not allow，是不允许。我是限制了对话框的大小，没有做你要的那个工嫩

**Comment by LiMinggang** [comment]
我试了一下你做的图标，大小有点问题，我调整了一下，不知道出了啥问题，结果没出来。先这样吧

**Comment by zhulaojianke** [comment]
噢，我知道了。我的那个图标是偏大了还是偏小了？您要的是16*15，是高16，宽15么？
您再试试这个……高16，宽15的
![](http://i13.tietuku.com/b2286444d728f4d5.png)

**Comment by zhulaojianke** [comment]
另外一个高16，宽15的
![](http://i13.tietuku.com/b3c23c6f3b376f25.png)

**Comment by LiMinggang** [comment]
嗯，多谢，其实是小问题。我自己调整了一下，不知道为啥出问题。

**Comment by zhulaojianke** [comment]
这个是宽16，高15的
![](http://i4.tietuku.com/4a2a86ed0e512cc0.png)

呵呵，还望您能把这个工具栏图标放在“快速搜索工具栏”里面。自私的原因是，我把所有的工具栏都隐藏了，就留了一个“快速搜索工具栏”在外边——主要原因是这个“快速搜索工具栏”不能和其他工具条放在一行里——如果我手动的把它和其他工具条放在一行了，等我关闭之后再打开，它仍旧会跑到第二行。怎么说呢？参差不齐的工具条总让我看着闹心，所以我就索性把所有工具条都隐藏了……处女座的

**Comment by LiMinggang** [comment]
我是专门把搜索条独立出来的，因为可以用快捷键隐藏和显示。对宽屏来说可以延展，但是似乎这种工具条的实现是不能自动所成一团，所以就放第二行了。
![2016-01-29 16_07_29-madedit-mod - c__dev_github_madedit-mod_images_saverec xpm](https://cloud.githubusercontent.com/assets/4847132/12670359/cdcf34c4-c6a2-11e5-8c4a-1f91b90ab069.png)

**Comment by zhulaojianke** [comment]
哦，上面那个宽16，高15的图标我又重新上传了一个，第一次的在缩放的时候“文件夹”下面缺了一角。我看您上图中所用的图标是我作废了的那个。

**Comment by LiMinggang** [comment]
不是，我给剪掉了一行，因为是要高15，宽16，我就自作主张给裁了。不过要是你实在不爽，就再折腾一个好的，哈哈

**Comment by zhulaojianke** [comment]
啊……我是不想凑合，不过又怕再麻烦您了。那什么，您还是用我上面做好的那个吧，终归为此我还改了3次稿了呢。

**Comment by zhulaojianke** [comment]
其实您可以设计一个“让用户自定义工具条”的功能，用户根据自己常用的菜单选项，自行在工具条上添加删除已有的按钮，形成一个自定义的工具栏，这样工具条的长短收缩什么的问题，也就解决了。

很多软件都支持这个功能，比如说Mathad、SmartSketch等我常用的软件。

而且还可以让工具端（竖起来）靠在编辑窗口的一侧，放在编辑窗口的底部，不必都集中在顶部，这样把它们分散开，有再多的工具条都不会跑出显示器边缘了。

**Comment by LiMinggang** [comment]
你说的都是些巨无霸的软件，你看看那个软件大小。有些不影响使用的功能没法做得特别完善。这些注重界面和使用的做起来太花功夫。

**Comment by zhulaojianke** [comment]
对，您说的对，我知道我错了。确实那些CAD、CAE软件对界面下了很大的功夫，都是有专项组或者界面供应商在后面支持着呢。以后我不拿怪兽跟咱们这个小良民比了。

**Comment by LiMinggang** [comment]
也不是啥错，我自己也对界面比较挑剔，但是有时候做那些特效可能引起软件尺寸严重膨胀，而且，毕竟相对你提到的那些软件，MadEdit的功能是相当简单。还没有到那种需要简化的地步。
还是折衷吧。
