### ISSUE TITLE
Need a larger input area in the Search and Repalce pad

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#145]
Now the Search and Replace pad only give the use two single line input area, but when the search content or the regex is a little long, the content that can't be contained in the area will run out of the area, and then it's hardly to inspect and edit it. And if I want to use the replace function to split one line into several line, I must input "enter" to get a multiline appearance, but when I hit "enter", it begin replacing automatively. If the Replace area could use "enter" to make multiline, and use “ctrl + enter” to execute the command, the problem will be solved.

现在的搜索替换面板给“搜索”和“替换”仅提供了1行输入区域，当我要输入比较长的搜索内容或正则表达式时，部分内容就会跑到区域之外，此时要对搜索内容进行检查和编辑就很困难了。

举一个常见的例子，比如说我要把一段中文内的所有空格都删掉，我会使用表达式：
(?<=[\u4e00-\u9fff，。？！“”——；：￥‘’、《》【】·……（）])\s(?=[\u4e00-\u9fff，。？！“”——；：￥‘’、《》【】·……（）])
此时要在1行的搜索框中对它进行编辑是很吃力的。

如果搜索的输入区域能够有3行的高度，而且支持自动折行，且当输入更长的表达式时，会有滚动条，从而允许用户使用比较复杂的正则搜索，那将是件非常好的事情！

另外，在替换框中，如果我要把以下内容：
试试看
分行为：
试
试
看
我会在“搜索框”中输入“试”，在搜索框中输入：
$&

此时就需要使用“enter”键在替换内容中进行换行了，没有其他办法。但当我在只有1行的替换框中输入“enter”时，替换就自动执行了，而不是在替换框中发生了分行。
如果将替换输入框也给出3行的输入空间，更多的有滚动条的话，此时如果用“enter”分行，都检查没问题后，用“ctrl + enter”执行替换，应该就没问题了。

另外，比较奇怪的是，在使用0.3.9进行这种分行的时候，我在替换框里输入“\n”就可以了，而且我还用这个功能处理了很大的文档，都没事儿——但是现在好像不行了。我又在其他的正则调试器上试了试，貌似现在这样的才是正确的，它们在替换框里都不识别\n，仅作为普通字符串处理。不知道，总之在0.4.0里要给大长段分行不是那么容易了。

**Comment by LiMinggang** [comment]
Fixed in 0.4.2
