### ISSUE TITLE
Add a "always on the front" function to let the MadEdit-Mod works like a Notepaper

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#146]
When use MadEdit-Mod to collect text information from other explorer or write some notes during using other software, if the MadEdit-Mod could stand on the front, the user could use it anytime and anywhere, like a small notebook, and needn't toggle the windows everytime, that maybe provide convenience for the uses.

以下是以前写的……

```
不知道怎么用英文说这个“停靠隐藏”，就用中文吧。

类似于QQ，当我把编辑器窗口缩小后，接近显示器边缘时，文本编辑器就会收进边缘隐藏起来，当我的鼠标靠近隐藏的位置时，编辑器就会被“吐出来”。

这样当用户在全屏开启另外一个程序，比如说IE、Word、PDF浏览器等等，使用MadEdit-Mod做“文摘”或者“随手记”的时候，就不必来回按快捷键或者点击Windows任务栏来切换窗口了，只要把它放在一个方便的位置，随时都可以用。也就不必花很大力气去找各种Note软件了，直接用文本编辑器做Note要更实用。

如果需要进行大量的文本编辑的话，用户自可以把它从显示器边缘拉开、放大。

如此还可以设置让MadEdit-Mod开机启动，自动隐藏在上次停靠的位置上。

这样，MadEdit-Mod相当于通过增加这个功能，多了一种很好的用途，而且也提高了文本编辑器的使用率——不是非要在有很大的文本需要编辑的时候才要用到文本编辑器，平时记录灵感、日常计划、网络摘抄的时候，用起来也同样的方便。

希望您能考虑这个建议 :)

```

**Comment by zhulaojianke** [comment]
呵呵，想到这个的原因是，我最近在为另外一个小软件做试用测试，此时再没有比用MadEdit-Mod记录bug和用户需求更方便的手段了。但是来回切换窗口真的挺烦人的，就觉得如果MadEdit-Mod能够像QQ那样靠边隐藏，并且保持在屏幕的最上层，随手召唤，是多么重要了——当从屏幕边缘拉开，即不再“停靠隐藏”的时候，也就没必要让它总保持在屏幕的最上层了。

**Comment by LiMinggang** [comment]
这个比较难，跨平台要考虑其他平台的问题。

**Comment by zhulaojianke** [comment]
嗯，我又想了想，其实我真正需要的没有那么复杂，只要有一个“保持窗口在最上层”的功能就可以解决了。

如果是停靠隐藏的话，还需要让鼠标去靠近，然后可能Windows会附加上一个动画效果“伸出”“收回”——这反而很闹心，而且耽误使用效率。

“总在最前面”相当于把MadEdit-Mod的窗口给缩小成一个悬浮窗口，也不需要停靠和隐藏这么复杂的功能，只要能够让它在别的程序打开时，它仍旧可见，就是一个很棒的note了。

把这个功能的切换键设置在工具栏按钮里，需要的时候打开，不需要的时候关上，用户可以自定义快捷键，比如说ctrl + f11这样的——f11常被用做“全屏”切换，ctrl + f11就作为“总在最前面”的状态切换吧。

我把“标题”给修改一下吧。

**Comment by LiMinggang** [comment]
Always on top应该是可以做，今天刚做了全屏和Post-it，跟NP++一样。

**Comment by zhulaojianke** [comment]
我刚才科普了一下Post-it，是便利贴的意思哈，不知道会是什么样的效果……可能跟我想的这个差不多吧？ :)

**Comment by LiMinggang** [comment]
Post-it是一个著名的便签的商标。我看NP++的样子是比全屏更简单，连下面的状态栏都省了。

**Comment by zhulaojianke** [comment]
又发现了这个“总在最前”的另一个用途——用MadEdit-Mod写了一个比较复杂的写作提纲或者工作流程之后，把窗口缩小放在一个角上，边在word里敲字儿，边参考提纲，不会让自己写着写着就偏离了主题，违背了初衷。呵呵，所以我感觉这个功能至少对文学创作来说还是挺重要的了。

若用word直接拉提纲也不是不成，但是太正式，有压力，心理阴影太大了……而且很容易就会在提纲本身上开始写东西了，结果提纲就失去了记载最初思想的作用。
