### ISSUE TITLE
Full screen/Post-It Mode support

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/madedit-mod#147]

**Comment by zhulaojianke** [comment]
什么是post-it mode呀？

**Comment by zhulaojianke** [comment]
Post-It模式特别适于专心写作，把所有的杂音都屏蔽了哈。不错，但是，怎么退出这个post-it的状态呢？我发现没有切换的快捷键呀。我想了一个，既然f11是全屏，ctrl + f11是总在最前，post-it的快捷键用 alt + f11 来切换，您看怎么样？
