### ISSUE TITLE
Use mouse wheel to scroll  and activate the tabs on the tab bar

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#148]
When the mouse curser is on the tab bar, use the middle wheel to scroll and select and activate the tab which will be edited, it is more easy than "find and click" or more effectively than use hotkey to toggle by one and one.

这是对#144的补充，但又确实是一个新功能，所以就单写一个issue啦。这个灵感也是来自IE和Word，当鼠标处于页面标签栏的时候，使用鼠标滚轮就可以向前或者向后切换并激活相应的标签页面。

当有多个标签页面（或者说文件）被打开的时候，这个功能就比一个一个标签的找，然后鼠标点击要方便多了，也比使用快捷键向前或向后一个一个的切换要有效率得多。

而且当打开的文件数量很大时，标签就会很多，部分标签就会被左右箭头给隐藏到后台，这个时候如果要找到自己所要查询或者编辑的那个文件，就得点击那个左右箭头，很不方便的。如果用鼠标滚轮直接滚动打开的话，藏在后台的文件也会被滚出来，并被激活打开，直接编辑，那样就太好了！

**Comment by LiMinggang** [comment]
Click on any of the File name Tab to set the focus to the tab bar. Then use mouse wheel to scroll.

**Comment by zhulaojianke** [comment]
呵呵，在alpha2版本里看到了。有2个问题：
（1）对鼠标滚轮的滚动太敏感了，能够成为现在的1/2或1/3就很好了。现在用户还没看清楚自己到底滚到了哪一页，就滚过去了……
（2）循环功能也不是很好，当标签被滚到最左边或者最右边的时候，就是到头了，滚不动了，这样也便于用户自己目前的标签安排顺序。嗯，其实如果第（1）个切换时能慢一点儿的话，有个循环也不会添加太大的麻烦。（我是用打开两个标签页测试的，一滚动，就在这两个标签之间循环切换，切换的太快了，就看屏幕闪呀闪的，反而看不到自己要找什么了……）

还有，我发现当鼠标离开标签栏，焦点就自动回到了那个标签的文本里，那么能不能做成“当鼠标进入标签栏，焦点就自动进入标签栏里”呢？那样就不用去点击那一次标签了——当鼠标不处在标签栏里的时候，都是聚焦在文本编辑窗口，仅有当鼠标的位置处于标签栏的时候，才对标签栏起作用。
