### ISSUE TITLE
Wish the check box of the fast search bar could remember the user's choice

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#149]
The fast search bar is really a great function of the MadEdit-Mod, it could increase the edit speed through find and position. But when I close the software and re-open it, the choice I have check in the check box always be emptied, and I have to check them again and again, it's so unconveniently.

I hope the check box could remember what the user has chosed last time, and could check them when re-open the MadEdit-Mod, to use the fast search bar more easily.

现在在文章中定位，除了使用ctrl + g之外，越来越多的是依赖快速查找工具栏了，感觉这个确实是MadEdit-Mod的一大发明。但每个人都有自己的查找习惯，设置过一次复选框之后，下次查找最大的可能是他还会使用相同的选项。但当每次关闭MadEdit-Mod并重启之后，复选框就都被清空了，还要重复去设置，有时就忘了去选复选框了，尤其是在使用正则表达式的情况下，结果是增加了不必要的麻烦。

如果能够让这些复选框记住上次用户的选择，在下次打开时能够保持这些选择，这对用户来说就会方便很多了。

**Comment by LiMinggang** [comment]
这个不需要checkbox，直接记住就好
