### ISSUE TITLE
How to toggle "post-it" mode? a hotkey recommend alt + f11

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#151]
我还是单发出来吧……

Post-It模式特别适于专心写作，把所有的杂音都屏蔽了哈。不错，但是，怎么退出这个post-it的状态呢？我发现没有切换的快捷键呀。我想了一个，既然f11是全屏，ctrl + f11是总在最前，post-it的快捷键用 alt + f11 来切换，您看怎么样？

**Comment by LiMinggang** [comment]
F12，你拿到的版本已经有了

**Comment by zhulaojianke** [comment]
哦，这样啊，我说呢，我早先把f12分配给“选项”了……

**Comment by LiMinggang** [comment]
哦。呵呵，没考虑到
