### ISSUE TITLE
How the MadEdit-Mod sort the chinese lines?

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#155]
我正在整理一个关键词表，就是每行都有一个关键词，一直列下去，我想用MadEdit-Mod的排序功能，结果发现，对中文的排序并没有明显的规律，见下图：
![](http://i13.tietuku.com/2f9adb2de5588228.jpg)
MadEdit-Mod对中文是按照什么方法排序的呢？

**Comment by LiMinggang** [comment]
对西方字母应该是字母序，对中文，这个真没研究，是沿用以前作者的代码，需要看一下才能答复你。

**Comment by zhulaojianke** [comment]
哈哈，刚初三，不必辛苦哈。祝您猴年大吉大利，万事顺心顺意哈！:)

**Comment by zhulaojianke** [comment]
我知道是按照什么方法排序的了！是Unicode字符表，也就是在正则搜索中文的时候用的\uf000系列。这样多少是有规律的了，先看部首的笔画，再看另一部分的笔画，左右优先于上下，注意这个规律只能用于繁体字，跟早年的四角号码查字有些类似。所以要在中文排序后对行进行检索，需要先简体化繁体，然后数笔画。多少还是有些麻烦的，需要较强的中文底子⋯⋯如果能改为按拼音搜索的话就方便多了。

**Comment by LiMinggang** [comment]
过年好！
这个排序其实是最简单的，还是字母序----比大小。拼音排序这个得看看有没有现成的，需要背景知识太多。

**Comment by LiMinggang** [comment]
我极少用到排序功能，试了几次总觉得有问题，排序结果不对，你有发现？

**Comment by zhulaojianke** [comment]
还好，当时为了学正则表达式，对Unicode表的汉字排列规律我大概有些了解了，尽管有些不自然——Unicode表中的汉字顺序是繁简混排的，很多生僻字夹杂在常用字之间。如果改成拼音排序的话确实要方便得多了。

行排序的应用场景主要是自己做某某清单，比如说我现在做的文献关键词列表、关键文献的路径列表，这些如果有了比较好的排序的话，查询起来就方便得多了，因为当列表很长的时候，自己都记不清里面有什么关键词了，用搜索面板也不知道要查什么好，这个时候了解中文的排序规律就很重要了。
