### ISSUE TITLE
Hope to add a "Scroll to here" command when right click on the scroll bar

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#157]
不知道标题说的是否明白，还是说中文吧。就是当我在页面滚动条上右键点击弹出菜单的时候，我希望能够加上一个“滚动到这里”的命令，当我选择这个命令后，页面就滚动到我的鼠标所在的文本的大概位置了。

这个灵感来自于Adobe Reader和Word，当不知道确切具体行数或者相隔了多少行数的时候，此时仅记得所要看或者编辑的文本的大概位置，就用鼠标在右边的滚动条上右键点击一下选择“滚动到这里”，然后就能够跳到差不多的位置了，光标的位置不必动，仅仅是文本滚动就可以了哈。这个操作有时候是很方便的。希望您能够参考 :)

**Comment by zhulaojianke** [comment]
另外，忍不住赞一个，MadEdit-Mod真的提高了我的工作效率，真正的专心工作的感觉呀！

**Comment by LiMinggang** [comment]
好建议，需要研究。

**Comment by zhulaojianke** [comment]
测试的时候，还是很呼唤这个功能能够实现的。 :)
