### ISSUE TITLE
A search history bug

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#159]
不知道是不是一个bug，还是您故意这么设定的。

MadEdit-Mod能够记住搜索记录这个非常好，但貌似有一个限值，最多能够记录那么多个，而之后再进行搜索的记录就不能记载了，只能手动的清空搜索历史记录，把存储搜索记录的这个容器清空之后，才能继续记住新的搜索记录。能否将其改为当有新的搜索记录的时候，超过一定数量，最早的搜索记录自动清除，以容纳这个新的搜索记录呢？也就是“滚动式记录”。这样可能更实用一些吧。

**Comment by LiMinggang** [comment]
I think it's already what you expected.
