### ISSUE TITLE
Quick Search bug

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#160]
Sometime when I input a new keyword in the Quick Search Window, it will use the last keyword before this input to find.

在使用快速查找时，偶尔会发生，我输入一个新的关键词，但是它会用我上次输入的关键词进行查找。并不是每次都发生，偶尔发生。当我再次修改关键词的时候，比如按了backspace键删掉刚才的输入，在Backspace的同时，又恢复了正常。

**Comment by LiMinggang** [comment]
I could not reproduce the issue and did not find any suspicious code.
有可能是wxWidgets本身的问题。复现不了就没法修，这个也不影响使用。基本不会下力气修了，除非你能找到必现的条件。如果你能够稳定复现，再从新Open这个问题吧。_

**Comment by zhulaojianke** [comment]
抓QuickSearch的bug瞬间真的不太容易，有好几次都是已经发生了，但往往顺手就换成了其他的搜索词，等想起来应该把那个bug截图出来的时候，已经晚了
现在截了一个图：
![](http://i12.tietuku.com/312734cac08ae745.jpg)
类似的搜索bug我这边发生的概率差不多是50%

还有，我发现QuickSearch里面的关键词和表达式好像是和"搜索替换面板"中的关键词和表达式是相通的，而且会优先记住“搜索替换面板”里的信息。我主要用QuickSearch作为搜索跳转，当发生了这样的bug的时候，就会跳转到我上次的搜索结果上去，而不是我在QuickSearch工具栏里输入的搜索词。

**Comment by zhulaojianke** [comment]
上图中，我搜索“砂轮”，但它跳到了“砂”上，这个bug屡试不爽，所以才截到了图哈。

**Comment by zhulaojianke** [comment]
出错的情况还是很多的，我找到的规律是每次用快速查找的时候，我输入了N个字符，它只查找前N-1个字符。再举一个：
![](http://i13.tietuku.com/ab8aa8e050511678.jpg)
