### ISSUE TITLE
Syntax highlight of Keyword should override special word prefix 

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#164]
如#156讨论中说的，当用户预先定义了special keyword之后，当CustomKeyword中含有Special keyword中的字符时就不会发生作用。

而且，对于中文字符（使用text着色），在Custom Keyword中定义了中文字符之后也不会发生作用。

special keyword、delimiter、BracePair、AutoCompletePair等对双字节字符、全角符号，以及一些特殊的单字节字符，比如"·"“（）”“【】”“°”等也不会发生作用。

**Comment by LiMinggang** [comment]
special keyword、delimiter、BracePair、AutoCompletePair这些不支持双字节字符。

**Comment by zhulaojianke** [comment]
这个bug改的不错，绝了！我把外文文献中的涉及到的缩写词都设为 custom keyword，现在看我整理的那套文件要清楚多了，基本上是看一眼就知道关键的内容是什么，不用再像原来那样前后看上下文了。谢谢哈！
