### ISSUE TITLE
A QuickSearch Bug

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#168]
上次提出之后，不断的发生这样的bug，我给出两个例子放在#160里了，发生的概率非常高，原来感觉是50%，现在看基本上几乎是100%了。

具体描述：
我在QuichSearch窗口中输入N个字符，它只查找前N-1个字符。比如说我搜索“好不好”，它给出的搜索结果都是“好不”的。

希望您能修复它吧。

**Comment by LiMinggang** [comment]
没复现出来。你能不能贴上例子的文件和步骤。

**Comment by zhulaojianke** [comment]
因为我现在主要用MadEdit干我们单位的调研和文献资料整理的事儿，涉及到了保密的事儿……真的不能上传。

我具体描述一下我这边的情况吧，希望能够在您那里复现：
（1）我同时打开了两个文档(A)和(B)，并且拆分了窗口，每个文档里的内容都比较大，而且确实有一部分是重复的；
（2）我用“搜索替换面板”搜索过一些内容，也在快速搜索工具栏里搜索了一些内容，两者没有发生过重复
（3）此时我关闭MEM，然后再重启，这个时候我在“搜索替换面板”里搜索的一些内容也会在“快速搜索工具条”里出现，貌似这两个是相通的。
（4）然后在文档(B)，使用“快速搜索工具栏”搜索了一个关键词，没问题，此时我发现所搜索的文件错了，应该搜文档(A)，于是切换到文档(A)，按“搜索上一个”或“搜索下一个”，结果就出现了这个bug。
（5）之后，只要我在“快速搜索工具栏”里搜索关键词（注意不是正则表达式，在搜索正则表达式的情况下，如果仅仅搜索关键词，仍旧会出现这个bug；而当我使用正则表达式进行搜索的时候，还没有发现什么异常），结果就只能搜索出前面N-1的字符了，或者直接跳到存储中的以前的搜索关键词上了。

比如说，当我下拉"快速搜索工具栏"后，可以看到一个列表，是以前的搜索记录：
AAA
BBB
CCC
……
此时我搜索“好不好”，可能得到的搜索结果有70%的概率是“好不”，有20%的概率是"AAA"，而真正搜出"好不好"也只有10%的概率。

不过我现在貌似找到了一个解决办法，就是当发生了搜索出"好不"的时候，我在“快速搜索工具栏”里用backspace删掉最后一个字，然后再从新输入那个字，基本上就可以得到“好不好”的搜索结果了——尽管这个方法并不是每次都奏效。

**Comment by zhulaojianke** [comment]
我上面说的，在完成了前(1)~(4)之后，第(5)步就总会出现了，而不是偶尔出现的，跟是否再重复进行(1)~(4)没什么关系了。不知道我这么表述清楚了没有……

**Comment by zhulaojianke** [comment]
而且这个bug好像只会发生在搜索中文的时候，搜索英文的时候我还没有遇到过。

**Comment by LiMinggang** [comment]
哦，明白了。
哈哈，你真是实在，你可以随便弄点文字，只要你能复现这个问题，然后告诉我步骤就好。

**Comment by LiMinggang** [comment]
我这还是找不到条件复现你说的问题，这个快速搜索基本没有新功能，完全是使用搜索对话框的同样功能，唯一不同就是一输入字符就立刻取到用户目前的输入内容就开始搜索，所以不太可能出现你说的bug。

**Comment by zhulaojianke** [comment]
哦，我重新建了两个文档，用的是3楼的那段话，还没有发现这个问题……真是怪了，我关掉刚才我编辑的两个标签页(工作上的文件)，然后重新打开，就也找不到这个问题了。哎……确实在刚才出现这个问题还是概率很大的呢，我关闭文档然后再打开之后，就什么都好了！会不会是因为我对那两个文档编辑的时间太长，而使记住搜索结果的内存或缓存充满了？总之，那什么，这个bug报告看来又要close了哈。

感觉您好像从来没有遇到过这样的问题，是吗？

**Comment by LiMinggang** [comment]
我还真没碰见过，这个quick search实际就是search对话框的简化版，用的所有代码都是那边的。所以，不太可能出现两种结果。

**Comment by zhulaojianke** [comment]
搜狗拼音输入法，特殊符号的输入利器^_^

**Comment by LiMinggang** [comment]
暂时关闭了，无法复现
