### ISSUE TITLE
AutoScroll or lock the cursor in a fixed line range in the window which user defined

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#170]
在向MadEdit-Mod中输入内容的时候，窗口中的内容是静止的，结果光标就渐渐的往下面走，直到用户低头打字累了，才想起来滚一下屏，把光标移动到合适打字的位置，不过一会儿光标又下去了。这还不是最糟糕的情况，我感觉MadEdit中的静止页面给用户带来的最早的情况是根本找不到光标在哪儿，需要满屏看，才发现原来在最下面呢，或者在最上面呢，当使用pageup和pagedown的时候，就会发生这种情况，尤其是电脑屏蔽比较大的情况，真的是满屏的找光标啊。

如果能够在输入的时候，或者平时，有“自动滚屏”的功能，让光标总是停留在窗口的中间位置的那一行（处在最上面一行，或者处在用户自定义的某些行的范围内），也就是"AutoScroll"功能，那么在编写东西的时候就舒适得多了。

这个灵感也是来自Vim，Scrivener也有这样的功能，尤其是在全屏模式下工作的时候，这个自动滚屏的功能非常能够集中用户的写作注意力，也辅助的增强了全屏或者Post-it的功能的目的。呵呵，所以，还希望您能够考虑哈！

**Comment by LiMinggang** [comment]
Vim的这个功能咋用？没注意到啊。我找光标一般都是按一下方向键

**Comment by zhulaojianke** [comment]
确实有呀！因为我已经把Vim从电脑上卸载了，否则我肯定会找出来，证明给您看的。

Vim有3个按键可以控制光标是停留在编辑框顶部、中部或者下部的，然后我记得还有一个命令就是锁定光标所在行，当输入那个命令之后，在打字的时候，光标本身不上下动（可以左右动），而是整个文本滚动。当光标发生折行时，整个文本就向上滚动一行。

我印象中是“z”键是让光标所在行处于编辑器的正中，您可以试试哈。

**Comment by zhulaojianke** [comment]
因为我打字速度还是比较快的（呵呵，我特别会夸奖自己 :P），所以在编辑的时候很快就是要把头低下去了（光标跑到编辑器的最下面了），时间长了就颈椎疼，颈椎一疼，我就动动鼠标滚动滚动屏幕，不过过一会儿又要低着头敲字儿了。所以我就特别怀念Vim和Scrivener的这种人性化的功能了。

还有就是找光标的时候，动方向键可以把光标拉到编辑器的最下面一行或者最上面一行，不过我感觉最下面一行的概率特别大……往往就直接低着头敲字儿了，说到底还是颈椎问题 +_+！如果当光标跑出编辑框的时候，有一个按键，按一下，那部分的内容就直接滚到屏幕的正中了，也不用低头了，也不用用鼠标再滚动一下了，又好找，又使整个工作流更顺当了。

不知道实现起来会不会很麻烦哈？

**Comment by zhulaojianke** [comment]
我还是挺希望这个功能能够实现的，尤其是在使用全屏的时候，让光标总是处于中间的那一行，真的是一个人道主义的设计。

**Comment by zhulaojianke** [comment]
我用Haroopad的Vim模式试了一下，就是“z”键，不过其他的命令键我都忘了T_T

**Comment by LiMinggang** [comment]
vim试了一下
Screen movement commands

z.	Center the screen on the cursor
zt	Scroll the screen so the cursor is at the top
zb	Scroll the screen so the cursor is at the bottom

这个好像是浏览模式用的，并不能控制输入的光标

**Comment by LiMinggang** [comment]
最简单的work around是你把窗口缩小到屏幕的一半，呵呵

**Comment by zhulaojianke** [comment]
哦……光标放在屏幕中间的话，还可以在输入的时候兼顾上下文的情况……您如果觉得没必要我也不能强求啥。终归相比更方便的跳转来说，这个功能仅是改善编辑体验，增加使用舒适性的。您再考虑考虑的？ :P

**Comment by LiMinggang** [comment]
主要是看难度和用处，毕竟不是专职，难度太大的话需要太多精力，没时间啊。感觉上不难实现，只是不知道实现出来是啥效果，有没有带UI（不是gvim这种怪兽）的界面有这个功能？得先体验一下

**Comment by zhulaojianke** [comment]
Scrivener有这个功能，您可以下载试用版，这个功能被他们当做全屏模式下编辑的一大卖点，我记得在他们网站首页上就提到了这个功能了。

**Comment by zhulaojianke** [comment]
http://www.downxia.com/downinfo/50051.html
这个是国内给绿色化了的版本，不用安装就可以试用的。

**Comment by zhulaojianke** [comment]
相比之下，我感觉#158和#169这两条对改善编辑体验更重要一些。这条顶多就是多动动鼠标（肯定会打断编辑过程了），而#158中的搜索窗口中的结果是静态的，不能刷新，确实使"搜索结果窗口"的导航作用大打折扣了。

**Comment by zhulaojianke** [comment]
呵呵，如果您方便的话，还挺想知道您的工作是什么方面的……可能我以后有了什么项目，咱们俩可以合伙赚一笔钱呢哈。 :)

**Comment by zhulaojianke** [comment]
我感觉我能够提的建议差不多就是这些了，等您有时间把它们都实现（或者实现一部分也很感谢您哈），我就不再打扰您了，呵呵，所以我挺希望您能够给下一个版本起名为1.0.0版的——它会具备充分舒适和高效的文本编辑能力的 :)

**Comment by zhulaojianke** [comment]
越来越感觉这个功能有需要了。如果不能做自动滚屏，能够像Vim的"z"键那样给用户一个随手居中的快捷键也好，打着打着字儿，就要动鼠标往上滚，实在没有快捷键来得方便。

**Comment by LiMinggang** [comment]
Please try the latest beta build. Will release it as 4.1 if you don't have comments on the fix for this one.

You can move caret to any pos you like and check View->Lock Caret Pos. Then, the caret would be locked at the line.

**Comment by zhulaojianke** [comment]
我对alpha3做了比较详细的测试，发现以下问题：

下面列出的issue都是您已经添加了"enhancement"的项目。

不太影响使用体验但也没有被添加的功能：
#135(自动保存、备份)
#153(合并所有打开标签页的文本为1个文件)
#166(添加1个用户可自定义的纵向标尺或基准线)

很能提高使用体验但没有被添加的功能：
#137(在搜索结果窗口的树前注明搜索的关键词或表达式)
#139(在搜索结果窗口条目的右键菜单里添加"添加标签"和"去除标签"选项)
#157(在滚动条的右键菜单中添加"滚动到此"选项)
#169(增加"回到上一个编辑位置"和"跳至下一个编辑位置"的快捷命令)
**我感觉以上4条功能对使用体验的影响真的非常大，在0.4.1版本中没有加进来，确实有些可惜。**

没有添加成功的功能：
#172(使用快捷键切换快速搜索工具栏)
**这个功能添加的有问题，原来我用快捷键可以使光标直接聚焦到快速搜索工具栏里，按完快捷键之后，直接输入就可以了；而现在我按快捷键仅仅是呼出了这个工具条，再按一次快捷键，这个工具条就消失了，我需要在呼出工具条之后，再用鼠标点击“快速搜索工具栏”的输入框，比以前还要麻烦了。
我感觉是我在那个帖子里描述的不够清楚所致。我是希望使用快捷键能够将光标聚焦在快速搜索工具栏的输入框中，再次按快捷键或者esc键，光标能够回到了文本编辑框中。至于工具条的隐现，可以用快捷键呼出，但不必用快捷键关闭它，如果用户需要关闭它，可以用鼠标来操作的。**

不知道我上面的表述是否清楚了哈。

还有，您这种是有一个快捷键固定光标所在行的方法确实出奇制胜，目前我还没有发现它有什么不方便的地方。如果之后我发现了，我会继续在这里跟您说的。

您解决在搜索结果窗口显示多行搜索结果的方法也很有意思，效果确实达到了哈！赞一个！ :)

非常感谢您的努力，谢谢您了哈！

**Comment by zhulaojianke** [comment]
我是认为您不必着急发布0.4.1版本，既然已经沉默了一段时间了，是吧，咱们索性就在下一个版本上使MadEdit-Mod在使用体验上有一个较大的飞跃。

我这段时间百度MadEdit-Mod，发现它的用户群在慢慢的增长，而且大多是华人，说明咱们凭实力已经赢得了用户的认可和口碑了，以后升级完全可以稳扎稳打，每次新版本的发布都会提高用户对MEM的信心，您说是吧？ :)

**Comment by LiMinggang** [comment]
我再想想那个快捷搜索的问题，解决完就发布0.4.1。版本号不是大问题，开源软件的精髓是快速，多发布，这样也利于快速发现和解决问题。主要是最近时间少，所以很多没来的及做，累计一部分就发布啦！

**Comment by LiMinggang** [comment]
很多功能是需要思考实现的，像这个锁定光标，开始想复杂了，觉得费劲，后来一段时间后，灵机一动，简单就实现了，所以，你特别希望的那些功能，主要是没有想清楚怎么做。所以一直也没有动手实验

**Comment by zhulaojianke** [comment]
嗯，是，想清楚再做，事半功倍，而且舒朗不闹心。

我是想若您有时间了，教我编程吧，也不用太多太深奥的，能够帮助您维护MadEdit-Mod就可以了哈。如果需要看一些入门的书，您尽管列出书单或者网址来，只要别太刁难人的，我还是挺有信心去学的。我平时不太忙的时候常自己做数学题，学一些应用软件什么的，这几年也渐渐学会了不少哈。即使仅了解个皮毛，缺少实战，帮助您找到实现某些功能的办法也是好的吧。您放心，我会努力做到帮不上忙尽量就不添乱的哈。

**Comment by LiMinggang** [comment]
会让你失去信心的，哈。我都是用了好几年MadEdit才决定自己开始动手，然后又几年才决定共享给大家用。还不提之前上学就开始学编程的时间。
不会有啥添乱，这种开源的软件，都是很分散，需要长期的热情，你有修改，可能不一定被接受，各种原因。
要维护这个，需要C++和wxWidgets的知识，前者一大堆入门书，后面那个好像有人翻译过一本中文的。
你除了使用MadEdit做写作，文档，还有其他用途么？我其实用的更多的是用它做工具处理文本，所以才引入了Python。

**Comment by zhulaojianke** [comment]
我主要用它做文献调研和知识管理，用的最多的还是往里面敲字儿，形成一个结构化的文本，可以速查，可以快速的编辑，呵呵，所以我特别关心的是在文档中的快速导航跳转和清晰的查找替换功能。我试过了其他的几种类似于个人笔记、PKM、Wiki的软件，它们要在好几个文件之间互相链接才能充分发挥作用，特别麻烦（尤其是科技文献中的关键词和术语标书很不统一的，通过简单的查询根本不能找到自己想要的信息），像现在这样，把所有的知识都放在一个txt文件里，通过查询就可以把所有我需要的东西一次性找到，我觉得最是快捷的。

用MarkDown软件说来也可以做这个，但一是速度太慢，尤其是内容多了的时候，而且因为可以做多媒体，可以弄格式，反而让自己分心；二是现在的Markdown软件没有一个支持批量查询的，就算批量查出来，也不能批量显示结果（没有搜索结果显示窗口），用起来还是不方便。

写作这事儿我更多的是用笔在纸上写——不受行的限制，想怎么抡就怎么抡，还可以随手画一些示意图——形成一个比较完整的提纲之后，才到电脑上耍，不过那是后期制作了，敲上字儿之后，用正则查找替换进行全文范围的编辑、润色。

**Comment by LiMinggang** [comment]
现在这个快速查找的快捷键操作改成：
1. F8，如果搜索条被隐藏了， 显示搜索条并设置输入焦点到输入框；如果已经显示了，则直接设置输入焦点到输入框
2. Esc，当前文档获得输入焦点（跳出搜索条）
3.只能用菜单去隐藏搜索框。

**Comment by LiMinggang** [comment]
你上文列出的功能，除了 #139 不是特别清楚是否能支持，其他都是可以做，有时间就在下一个版本里面实现

**Comment by zhulaojianke** [comment]
好呀，您已经上传了么？

**Comment by LiMinggang** [comment]
验证了一下，准备直接在0.4.1发布了
