### ISSUE TITLE
Need to toggle the QuickSearch Bar more simply

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#172]
When the user use the QuickSearch Bar, the most simple way is use the hotkey, I have custom it by "Ctrl + 8", but it only do the jump from Edit Window to QuickSearch Bar's input area, and the reverse operation was very troublesome, because no hotkey bond to this operation.

还是说中文吧……
我自定义了一个快捷键ctrl + 8，而可以很方便的在编辑的过程中跳到"快速查找工具栏"的输入框，但当搜索完毕的时候，光标就停留在了那个输入框里，只有用鼠标点击编辑框，才能实现光标的跳转，本来使用键盘操作是很方便顺利的，但偏偏就在此时要用鼠标，很突兀，不容易让人适应。

也有使用键盘的方法，非常麻烦，比如用ctrl + tab键切换标签页，当打开标签页比较多的时候，要切好几次才可以。还有用esc键退出“快速查找工具栏”，这个操作直接就把这个工具栏隐藏了，这倒不是最麻烦的，因为用ctrl + 8还可以再唤出来，最麻烦的是MadEdit-Mod目前还没有#170的AutoScroll功能，结果当这个“快速搜索工具栏”被隐藏了之后，编辑框的大小改变了，刚才找到了什么马上就会跳到编辑框的外边，也不知道是要往上滚动还是往下滚动。此时，“快速查找工具栏”就是去了它的查找定位的意义。

**建议取消用esc键退出切换快速查找工具栏的功能**，这样当我用esc键退出时，查找工具栏不会消失，而光标又返回到编辑框中刚才查找到的位置。如果要隐藏快速查找工具栏，最好像其他工具栏一样，让用户用鼠标选择操作，如此也增加了MadEdit-Mod的操作方法统一性，提高了使用方便的体验。

**Comment by LiMinggang** [comment]
Use F8 to toggle the toolbar and Esc to set focus to active edit
