### ISSUE TITLE
Wordwrap of input of search/replace dialog

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#175]
0.4.1终于发布了，额手相庆！快速查找工具条上的那个小图标真可爱哈！
您在更新记录中所列的：
17.Fix: Not allow to change the size of SearchReplace dialog
我试了一下，好像并没有改变呀！您能告诉我应该怎么操作才能让它支持多行输入么？
这一条绝对是正则表达式用户的福音哈。

**Comment by LiMinggang** [comment]
多行输入没有实现，只是限制了对话框大小

**Comment by LiMinggang** [comment]
试了一下，还算容易，就是没想好怎么让用户使用
![2016-03-21 14_00_55-it seems that the no 17 fix is not work well in the 0 4 1 issue 175 limingg](https://cloud.githubusercontent.com/assets/4847132/13911594/763784ca-ef6d-11e5-96e8-ef26ad3e8261.png)

**Comment by zhulaojianke** [comment]
哦，您的意思是说这样搞的话，整个“搜索替换面板”就显得太大了是吧？如果把下面的那些功能复选框改为两列或三列布置，整个面板的主要区域就以输入框为主了，这样它的功能主题我感觉也就更鲜明了，您看呢？ :)

**Comment by LiMinggang** [comment]
我在想是加一个什么控件让用户去控制整个框的大小，下面那些选择框太小了对某些语言来说可能会显示不下。
本来MadEdit的选择框没有下面那个bookmark和透明度的控制的，是我加的，所以这个对话框越来越大，呵呵
不过，这个尺寸不想做成能记住的，所以，难看点就算了哈。这个就别纠结了

**Comment by zhulaojianke** [comment]
还是您想的周到。

其实我感觉给出两行的空间就可以了，然后在输入框的右边加上滚动条，并支持用鼠标滚轮滚动，这样既不必用很大的输入框，也可以无限制的进行对行输入，对现在的搜索替换面板布局也是影响最小的。 :)
