### ISSUE TITLE
An Enhanced "Auto-complete"

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#176]
用英文怎么说呢？大概意思就是，咱们现在可以通过修改.syn文件使部分“符号对”可以在输入的时候自动完成，如果这种功能能够扩展为我“选上某个段落、单词或者字符串”之后，输入某个自定义为自动完成的符号之后，就可以在所选的文本两侧加上相应的符号，那样在修改文本的时候就方便多了。

举个例子，比如说下面的一串字儿：
dadaee6q1351a5da54fa21
我在syn中定义了 ( )和[ ]是自动完成的，于是我选择了上面的“ee6q13”，之后按“(”键，再选择“54fa”，之后按“[”键，就形成了下面的文本：
dada(ee6q13)51a5da[54fa]21

在输入的时候，现在的自动完成已经很好用了；但是在修改编辑的时候，需要在某些地方加上这样的括号、引号，或者其他自定义的“符号对”，就很麻烦了——需要用鼠标点击一个位置，输入一个符号，再点击另外一个位置，输入相对应的符号。而且当我将这个“符号对”设置为“自动完成”时，很有可能在进行这样的操作时，自动在第一个位置出现的是符号对，此时我还需要在把多出来的部分用delete删掉。

如果通过鼠标选择之后，直接像在空白区域输入自动完成符号那样插入相应的符号对，就方便多了！希望您能够考虑哈！

此时当读者想删掉所选择的文字，另外输入一个自动完成的符号时，可以用space给出一个空格或者用backspace或delete，然后输入自动完成的符号，仅多了1次按键。而我上面提的输入自动完成符号的方法，可以节省用户3次按键机会（算上鼠标点击）。所以我觉得还是很经济的哈。

**Comment by LiMinggang** [comment]
Word complete动得比较大，暂时不会支持。

**Comment by zhulaojianke** [comment]
您说的word complete是自动补全单词的功能吧？呵呵，我感觉自从有了神一样的搜狗输入法之后，一切自动补全单词的附加功能都是累赘。嗯，NP++和SynWrite中的自动补全单词的功能与搜狗重复了，而且看上去有些闹心，也是放弃它们的一个原因 :)

咱们能够把“符号对”的自动补全能力提升一下，就足够用啦 :)

**Comment by LiMinggang** [comment]
"如果通过鼠标选择之后，直接像在空白区域输入自动完成符号那样插入相应的符号对"----这个基本没法实用：不能揣测用户的行为，除非是有个模式是专门这种模式，即，不删除选中文字。揣测用户行为就会成为鸡肋功能。
目前文本编辑器中，没有人这么做，也许一些高级的文字处理工具有这个模式，估计还是会通过鼠标右键去做。

**Comment by zhulaojianke** [comment]
我觉得不必揣测用户意图，这是一个新的习惯的养成，当用户接触到这个功能并使用了一段时间之后，会感到方便的，终归它节省了按键次数。

而当用户想删除被选上的文字时，他们可以用backspace或者delete。

所以也没必要为此单独设定一个模式，就是一般模式下，当选中一段文字之后，按了“符号对”的开头部分的时候（比如“（”或者“{”）就自动给括上了。我感觉这样比较符合人们的编辑习惯，人们在审阅一段文字的时候，突然发现某处不应该出现在正文里，自然就会用鼠标选择上它们，此时如果有这个功能的话，就可以按一次键直接给括起来了。否则，用户还需要点击这段文字的开头，放一个前括号，再寻找这段文字的结尾，放一个后括号，不仅仅是操作上的复杂，还有就是好不容易找到的“多余的文字”建立了自己的一个瞬间的思路，在再次寻找的时候可能就会忘掉或者找起来很麻烦了。

仅是一个小修改，我想用户会很快适应并接受的，而且说不定咱们吃了第一个螃蟹，以后就会不断的有其他编辑器也发现这个设定很好，也会跟上的。您再考虑考虑么 :)

**Comment by zhulaojianke** [comment]
我感觉这种其他编辑器里没想到的功能，说不定就是一个很不错的功能呢，咱们这里的一小步，说不定就是地球上文本编辑器中的一大步呢。

**Comment by zhulaojianke** [comment]
用户在自定义或者.syn中已经定义了自动完成的“符号对”，它们本身就应该有更多的特殊意义，也就是说自动完成的“符号对”本身的行为就和一般的符号不同（一般的符号敲一次键盘，出现一个；而自动完成的符号对，敲一次键盘，出现一对儿），所以用户至少已经接受了这种自动完成的“符号对”的行为会有所不同的潜在心理预期，在这种心理预期下，我上面提到的这种小小的调整应该会很容易接受的，说不定还会给用户一种“彩蛋”的感觉。

至于有多么不同，我觉得在help文件里提一句就可以了。而且这也增加了MadEdit-Mod的个性，能够因此留住一部分用户的。就像您说的，说不定有些用户将来会选择其他的文本编辑器，但当他们放弃MadEdit-Mod的时候，他们会考虑到其他文本编辑器中没有这种方便的对选中的文字也可以加上自动完成符号对的功能，他们会犹豫的，然后就留下来了。您说呢？

**Comment by LiMinggang** [comment]
哈哈，你这思维太发散，这个和你提的那个group插入真的不是编辑器应该解决的问题啊。我看看能不能把这个做成一个快捷键，相当于有一个模式，比如多按一个ctrl键+({[]})之类

**Comment by zhulaojianke** [comment]
呵呵，我真不是想刁难您。只是感觉如果能够加入这些功能后，使用体验会更好。

我觉得渐渐的MEM的用户会更多的，当咱们有了其他文本编辑器中没想到的便利且强大的专利功能的时候，自然会有软件分享网站主动给咱们做宣传的。而且我是希望能够用MEM仅在文本编辑这件事上做的更自然舒适哈，用得舒服的软件才是好软件了。 :)

**Comment by KrasnayaPloshchad** [comment]
Notepad++ 貌似有这样的

**Comment by zhulaojianke** [comment]
又发现了这个功能的另外一个用途：
　　当我使用MadEdit-Mod进行网页内容摘抄做笔记的时候，使用这种“选择文本 -> 自动完成”的功能可以很方便的给这段摘抄文字中标记出关键词、需要注意的句子等等。

我觉得这个功能还是非常实用的。

**Comment by zhulaojianke** [comment]
今天看到国内有一个capslock+的快捷键软件，里面提供了这个功能，使用它的软件，用光标选中一段文字，然后按capslock + ( 或 [ 或 ] 会在这段文字两侧添加上( )、{ }和[ ]。试用了一下，感觉这种“auto-complete”的效果真的很不错。——只是把capslock当做辅助的快捷键不是很习惯，而且又涉及到好多javascript编程……所以还是把它卸了。

真心希望MadEdit-Mod能够增加这个功能！非常爽的。

以下是capslock+的网址，您也可以试试看，相信您会喜欢上这个增强的autocomplete的功能的 :)
http://cjkis.me/capslock+/#clTabScript

**Comment by zhulaojianke** [comment]
下面这个是WordTips中给出的在Word中实现这个功能的宏代码：

Sub AddBrackets()
 Dim iCount As Integer
 iCount = 1
 While Right(Selection.Text, 1) = " " Or _
 Right(Selection.Text, 1) = Chr(13)
 Selection.MoveLeft Unit:=wdCharacter, Count:=1, _
  Extend:=wdExtend
 iCount = iCount + 1
 Wend

 Selection.InsertAfter "]"
 Selection.InsertBefore "["
 Selection.MoveRight Unit:=wdCharacter, Count:=iCount
End Sub

不知道是否会对您有所帮助。

**Comment by LiMinggang** [comment]
他是用宏实现的，我也可以用宏在madedit里面实现，呵呵

**Comment by zhulaojianke** [comment]
如果能够使其成为MadEdit-Mod的一部分，而不是外挂的宏或插件，那就太好了！我转这两个例子的目的是想跟您说，这个功能是非常有市场需求的哈！

**Comment by zhulaojianke** [comment]
我觉得这个功能最理想的状态是：
（1）对于用户自己设定的AutoCompletePair，当选中一段文字之后，按pair的前半部分符号，比如说( )中的(，就可以在所选文字的两端完成加成对字符的操作，比如说给所选内容两端加上了( )。当用户双击 ( 时，即将所选文字删除，换成一对()——和鼠标什么都没有选择时发生的是一样的。
（2）当用户选择了AutoCompletePair中的文字之后，按delete键或BackSpace键，及将所选文字两端的( )删除掉，当用户双击delete或BackSpace键时，则只删除所选文字，两端的( )保留。

在“选项”中给出一个复选框，让用得到这个功能的用户自己选择是否使用这个功能，可能更好一些吧。

**Comment by LiMinggang** [comment]
嗯，今天基本做完了，试试觉得好用，打算把他缺省给置为这种行为。
双击删除还是不支持为好，你自己delete好了。

2016-06-06 19:54 GMT+08:00 Zhu Xinyan <notifications@github.com>:
