### ISSUE TITLE
BUG: There need a .ico file in the "madedit.exe"

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#177]
当我在“工具”菜单中修改了“文件”关联之后，相应的文件扩展名的图标就变为无法识别的样子了。这种情况我在0.3.9版本的时候就已经发现了，但因为感觉这个并不会影响MadEdit-Mod的使用，所以就没有在issue里提出来。

我是这么解决的，找了一个提取exe文件的工具，然后下载了一个老版本的MadEdit，从它的madedit.exe中提取出图标，命名为madedit.ico，并且复制这个图标文件的路径。然后打开注册表，查找所有的
madedit.exe,1
然后在defaulticon键中，把键值修改为madedit.ico的路径。重启电脑之后，就一切正常了。

嗯，我当时想的是MadEdit-Mod的用户可能不会像我这么在乎图标显示异常的问题——我感觉用这个软件的人不太可能是处女座……处女座都用NP++去了——不过最近wxMedit也进行了更新，呵呵，我发现它这次更新的主要方向是提高颜值，所以就想到可能一个软件的颜值可能确实会影响到它的普及度。嗯，不过我觉得MadEdit-Mod里面的段落符号什么的被说很难看，这个说法我挺不赞同的，这样的段落符号很实用呀！

嗯，希望您在下次更新的时候，能够在madedit.exe中加入图标文件，这样我感觉肯定会拉动人气的。 :)

**Comment by LiMinggang** [comment]
听你说的我去下了wxMedit 3.1，没看到UI的变化啊，图标也是原来MadEdit的，除了新功能的图标

**Comment by LiMinggang** [comment]
刚才又看了一下，即使是压缩后的可执行文件中也是有一个图标的，就是MadEdit那个牙齿图标。

**Comment by LiMinggang** [comment]
NP++我也用过，因为他满足不了我的用法：
1.我用的时候他不支持列编辑，现在支持了，但是还是不好用，
2.不支持十六进制替换，这个估计你也不用
3.十六进制编辑在我用的时候也不支持，好像现在也不支持（因为Scintilla不支持吧）？？
用MadEdit的很多也是这个原因吧。还有不少是Linux的用户，国外的，NP++只支持windows，他其实就是做了一个Scintilla and SciTE的外壳，功能都是人家做好的。

**Comment by zhulaojianke** [comment]
哦，您用的是windows系统么？我用的是win7旗舰sp1，每次做完文件关联之后，就会出现出现这个图标问题。前几天我更换新硬盘的时候重装了系统，结果还是一样的。

您说的UPX压缩，会不会影响程序启动的速度呢？就是在启动的同时，对exe文件进行一次解压缩，结果反而拖慢了程序的启动速度呢？

**Comment by LiMinggang** [comment]
启动速度取决于两点：
文件读取速度（文件大小）和内存运行速度，后者取决于你的CPU好坏。压缩后会提高前者的速度。如果你觉得受影响，可以用upx解压一下即可。
你搜一下freeUPX

**Comment by zhulaojianke** [comment]
那就确实可能是我的系统本身问题了，因为不仅是MadEdit-Mod，还有另外两三个软件的图标也同样有显示问题（不过都可以有办法修复的，只有MadEdit-Mod怎么也修复不了，确实madedit.exe中已经有图标了）。我用的是惠普的机器，win7系统也是惠普的OEM随机附送版，确实和一般的win7不太一样。

呵呵，UPX我看了介绍之后感觉要必死的决心才能折腾它，还是饶了我吧。

我之所以这么问，是因为我测算MadEdit-Mod在我电脑上启动的时间是3秒，而我启动word的时间大概是2秒多一点儿，总感觉不太可能会比word启动还要慢，可掐表结果就是这样的（用手机秒表计的）。您那边启动madedit.exe约是多长时间呢？
