### ISSUE TITLE
Use icons or symbols replace the words in the quicksearch bar

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#181]
现在的“快速搜索工具栏”中的文字说明太多了，使这个工具栏有些长，如果用图标或符号代替那些文字的话，工具栏就能短一些，当我使用小窗口的时候——把MadEdit-Mod的窗口缩小然后在桌面置顶，方便边写东西，边参考MadEdit-Mod中的信息——这个工具栏的一部分就处于窗口之外了。

图标我暂时还没想好，符号倒是能给您提供一些：
全字匹配：^...$
区分大小写：?-i:
使用正则表达式：RE
.匹配换行符：?s:

哦，可能不太好理解哈，下面这套符号呢？
全字匹配：|↔|
区分大小写：Aa
使用正则表达式：RE
.匹配换行符：\n∈.　　　　　其实我觉得这里用“**?s:**”更明白，因为这个功能只能在正则表达式里使用，**?s:**是正则表达式里的修饰符，表明是“单行模式”，也就是“.匹配换行符”的意思了。不用正则的话，打开这个功能也没有用的。

**Comment by LiMinggang** [comment]
这个，其实整个MadEdit的图标都是比较丑，没法子，没有艺术细胞啊

**Comment by zhulaojianke** [comment]
我也一时找不到能够和MadEdit-Mod整个界面匹配很好的图标……要不我就不会像上面那样给出一些奇怪的符号了哈。不过我觉得第二个方案中的符号还是挺明白易懂的吧？主要的目的是为了缩短这个最常用的快速搜索工具条的长度，至于好不好看我觉得是其次的哈 :)

**Comment by zhulaojianke** [comment]
嗯，我试试看，借我一些小宇宙吧！不就是16×16像素么，我应该可以的。

**Comment by zhulaojianke** [comment]
全字匹配：

区分大小写：?-i:
使用正则表达式：RE
.匹配换行符：?s:

**Comment by zhulaojianke** [comment]
感觉还是和MEM的风格不太搭，不过我觉得挺好识别的了。
这样就不必用复选框了，直接那这几个图标，点上之后类似于现在的“编辑模式图标”那样，在周围有一个浅蓝色的框，表明被激活了。并用鼠标在图标上悬浮时给出相应的功能提示弹出气泡，这样快速搜索工具栏的长度就会大大减小了，当缩小窗口尺寸的时候，用起来也方便了许多。 :)

**Comment by LiMinggang** [comment]
嗯，我先换了自己试试看，可以加上Tooltip就不会让人不理解了。你如果用别人图标的时候注意不要用收费的，国外比较注意版权问题

**Comment by zhulaojianke** [comment]
我试试看，主要是我用的是windows的绘图板做的，只能试试看用其他的软件了。

**Comment by LiMinggang** [comment]
绘图板也应该可以吧？白色背景

**Comment by zhulaojianke** [comment]
不是，我准备做出透明的图标来，嗯，我想试试看，总不能都用白色吧，太单调了，像一块块补丁似的。如果我做成功了，我把上次的那个“打开历史文件”的图标也做成透明的，这样就和MadEdit-Mod里面其他的图标是一个风格的。您信任我一次，我觉得应该没问题:P

**Comment by zhulaojianke** [comment]
呵呵，我已经做成功了，您稍等，我在调整一下颜色就上传过来，肯定会让您满意的 :)

**Comment by zhulaojianke** [comment]
全字匹配：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/80231108.jpg)
区分大小写：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/84119333.jpg)
使用正则表达式：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/44084128.jpg)
.匹配换行符：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/54354209.jpg)
打开历史文件：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/38212273.jpg)

**Comment by zhulaojianke** [comment]
如果觉得好，就夸我一句哈！ :dancer:

**Comment by LiMinggang** [comment]
多谢啊！非常好！

**Comment by zhulaojianke** [comment]
哈哈，谢谢 :)

我又修改了一下“区别大小写”的，刚才我发现它被做成16×17的了，下面这个是16×16的版本：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-3-21/71410853.jpg)

**Comment by LiMinggang** [comment]
哎呀，刚才又想了一下，搜索条用图标不太合适----只有突起和按下，似乎不太直观？有可能让你白辛苦了，比较直观还是用你建议的这几个字符比较好。

**Comment by zhulaojianke** [comment]
嗯，我上面使用的字符分别是：
全字匹配：[W]
区分大小写：A a
使用正则表达式：R E
.匹配换行符：?s:

不过那个“访问历史”的按钮应该可以用吧？比早前给您提供的那个要好看不少呢 :)

其实为这个事儿我也看了其他几个文本编辑器的搜索工具条界面，只有那个以正则搜索为主要卖点的editpad pro用的搜索工具条选项都是图标，其他的都是用文字说明的。

不过我感觉在MadEdit-mod中被选中的按钮周围有浅蓝色的框，这点使选中和没有选中直接区别还是很明显的，没觉得有不直观的感觉 +_+!

**Comment by LiMinggang** [comment]
那个已经更新了

**Comment by zhulaojianke** [comment]
啊，我是说我上面做了一个透明背景的“访问历史”按钮，比现在使用的那个要好看一些……您别误会……

**Comment by LiMinggang** [comment]
对，我已经用了。

**Comment by LiMinggang** [comment]
暂时用字母缩写，虽然感觉不是特别直观，用Icon有点费劲
