### ISSUE TITLE
Hide the menu bar and status bar

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#182]
仍旧是小窗口运行的时候的需求哈。在使用MadEdit-Mod形成了很好的文本之后，就该利用这些文本进行其他的工作了，此时就需要把窗口缩小然后置顶，随时对照参考，那就相当方便了。

也就是说此时MadEdit-Mod最好就是一个文本面板就可以了，如果能够把菜单栏和状态栏用快捷键隐藏起来，就能做到文字在这个窗口中所占的面积最大化，也是最不闹心的参考面板样式了。

当用户需要恢复菜单栏或状态栏的时候，使用相同的快捷键把它们切换回来就可以了。

**Comment by LiMinggang** [comment]
这不就是Post-It那个模式么

**Comment by zhulaojianke** [comment]
哦，我明天试试看，我感觉post-it模式不能缩小窗口似的。如果能够缩小窗口，那就没什么问题啦⋯⋯

**Comment by LiMinggang** [comment]
不能缩小窗口

**Comment by LiMinggang** [comment]
不能缩小窗口

**Comment by zhulaojianke** [comment]
这种可缩小窗口的最简化模式，使MEM像个便签一样的，在置顶的情况下非常有用哈。而且我感觉隐藏菜单栏和状态栏的实现不会很难吧， : )

**Comment by LiMinggang** [comment]
这个好像还真不好做，你可以把工具条都关闭，这时候工具条那些位置还是在的。

**Comment by zhulaojianke** [comment]
您是指菜单栏和状态栏吧？

工具栏如果都隐藏了的话，工具栏的位置也就消失了。

![](http://i4.tietuku.cn/6f6847a07f90f7f8.jpg)

**Comment by KrasnayaPloshchad** [comment]
我觉得可以添加一个选项把菜单栏和工具栏搞成自动隐藏的，也可以把菜单栏缩成一个按钮显示在标题栏上面。

**Comment by LiMinggang** [comment]
现在知道怎么隐藏了，但是热键也被disable了。争取在4.3里做出来。
@KrasnayaPloshchad 你居然说中文，我以为是欧洲兄弟
