### ISSUE TITLE
Enable config fix width mode in global config

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#184]
这可能不是一个像样的issue，所以我用中文做的标题。

是这样的，我在使用Courier New字体写东西的时候，按说这是一个典型的等宽字体，但我发现“——”中文破折号占用的空间大约是2.5个字符宽度，而不是2个字符宽度。

习惯上像“——”和“……”应该占用4个字符宽度（也就是2个汉字的宽度），至少这两个符号所占用的宽度应该是一致的吧，但在courier new字体中确实这样的：
![](http://i4.piimg.com/87c1c858f1818db5.jpg)

而我把字体调成华文中宋之后，符号倒是显示的没问题了，可tab键的缩进宽度又不对了：
![](http://i4.piimg.com/370f90b94d8bab2c.jpg)

我试了仿宋、宋体，都没问题，破折号、省略号和tab都没问题。呵呵，可能我的这个发现有些太小众了。仅在这里一提，如果您能够修改一下Courier New下的显示当然更好啦，或者您就给close了吧。 :)

**Comment by LiMinggang** [comment]
我看看，单看上去是字体问题，因为是用西文字体显示汉字

**Comment by zhulaojianke** [comment]
我好像找到了解决办法了！

在MadEdit-Mod中有一个“固定宽度模式”，选择了之后，所有的字体宽度问题就都解决了！呵呵，这个功能太神奇了！

**希望您能够把这个“固定宽度模式”设定为“默认”或者允许用户在“选项”中勾选使其成为“默认”。**

这个功能真的太好了！治好了我这几天的对齐强迫症哈。

**Comment by zhulaojianke** [comment]
我现在通过修改.cfg文件中的：
FixedWidthMode=1
达到了这个目的。
呵呵，还是希望能够在“选项面板”中能够把这个全局选项列出来，说不定会有其他的用户跟我一样在意字体不能严格对齐的事情呢。 :)
