### ISSUE TITLE
A basic "Group Operation" function to insert user defined lines or blocks like batch processing

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#185]
This maybe an interesting function for the users who write a long and structured text, for example a long program file, maybe devided into many sections. To seperate these text for easy reading, someone maybe use the comment line or block, just like this:
```
-----------------------------------------------------------------------
```
or
```
========================================
```
or 
```
-----------------------------------------------------
|                 titles aligned center              |
-----------------------------------------------------
```
or more complex formats, and maybe use them many many times in one file.

So to build a function to record these lines or blocks and recall them by a hotkey and select one format from a pop-up window is very conveniently for the users. Then the user could build various groups of characters, and MadEdit-Mod could save them in a standalone file and users could edit, add, delete these groups in the pop-up windows.

And a more difficult work is let the MadEdit-Mod could monitor the "edit window" width and word wrap options, then it could let the user defined line fill the line or let the title aligned center automatically. If this job is very hard to realize, just fixed the width of the user define group maybe work.

**Comment by zhulaojianke** [comment]
呵呵，“Smart Insert”的名字是我自己起的，其实就是给MadEdit-Mod增加一个“group”的功能，定义某一行字符或者某几行字符为一个“group”，然后在同一个文件里或者其他的文件中，调用插入这些“group”。

我在整理文献的时候发现，当文档比较长的时候，仅仅通过注释行来做文档块的分割并不显眼，如果使用通栏的横线或者好几条通栏的横线的话，就会直观得多。而手动输入这些横线很麻烦，如果从前面copy，当横线的类型不止一种且安排的顺序也不同的时候，来回拷贝也是很麻烦的。

今天看了几个编程文档的源文件，发现他们也经常使用这种方法来使自己的程序分割的更清晰，而且还有更复杂的，比如上面的“titles aligned center”块。

我感觉我上面提到的通过存储用户自定义的字符组群，然后需要的时候使用快捷键插入的方法，对于这种插入后还要修改文字，而且还要求文字居中，可能挺难实现的。不知道您是否试过了wxMedit在新版本中的加入的“列对齐”功能，在我这里除了要做到“列对齐”之外，还要能够对上下的横线进行同步增减。

我是设想添加一个弹出窗口，使用ctrl + insert键，能够唤出这个窗口，使用esc键能够关闭这个窗口。我预想这个窗口可以是这样的：
![](http://i4.piimg.com/b9e6fd75be48f85b.jpg)

有以下几个功能：

（1）定义组
当用户选择了一部分字符之后，在弹出窗口中选择“定义组”的命令，这些字符的组合就被存储为一个“组”，并且有编号，存储到MadEdit-Mod文件夹中的一个新的文件中，比如说叫Group.txt。
在“定义组”命令中，有一个复选框，“通栏”或者叫“整行”，也就是说当再次调用这个组的时候，这个组中的符号就会占满一整行，当调整窗口大小或者改变折行设置时，这一行中的符号不会随着折行，而是进行字符的增减。比如说，我定义了：
```
= = = = = = = = = = =
```
当选择“整行”之后，它在编辑窗口中是占满一整行的，不足的部分自动补足，多出来的部分自动裁掉。
而剪裁是从这一行的中间开始的，这样可以防止发生下面的这种情况：
我定义了一个框
```
= = = = = = = = = = = = =
||                     ||
= = = = = = = = = = = = =
```
如果从结尾处开始裁剪的话，就会把框的右边部分给裁掉了。
嗯，当然，用户也可以不选择“整行”复选框，这样再次插入的时候，就保持原来定义时候的样子。这样也有一个好处，就是用户自定义了一个“字符画”，作为自己的文章的一个logo，每次插入的时候，用户自然会希望能够原汁原味的插进来啦。

（2）插入组
用户定义的组，自动给一个编号，在弹出窗口中有一个预览框，通过下来菜单，用户可以预览各个编号中的组是什么样子的，找到需要插入的组，然后按“插入组”按钮，即可完成一次插入；也可以在后面的文本框中输入需要插入的次数，然后再按“插入组”按钮。

（3）删除组和清空
当用户在定义组的时候发生了误操作，或者用户自己就是想删除掉某个已定义的组，可以选择“删除组”，然后按“确定”，防止在点按钮的时候闹了手癌。同样的，如果用户需要重新定义所有的组，或者说想renew这个Group.txt文件，按“清空”然后按“确定”即可。

嗯，用户直接在Group.txt中进行编辑，甚至把这个文件删除掉，达到的效果和在弹出窗口中是一样的。

当用户删除组之后，这个组的相应序号就为空了，可以把后续序号向前提1个，或者直接就空出来，下次再定义新的组的时候，优先使用这些空序号。——或者允许用户自己对这些组进行命名。

**Comment by zhulaojianke** [comment]
呵呵，我感觉你可能还是会说其他的文本编辑器中没有这个功能哈。我觉得只要是方便用户的功能，根本就不必在意其他的编辑器里是否有先例了，您说是吧？说不定以后其他编辑器会学咱们呢！

我的这个灵感来自CAD软件，用户可以给自己画出来的性状批量group，然后就不再是线条、点或者简单性状级别上的操作了，而是块、组级别的操作，这就意味着，用户可以将某一个零件定位为一个组，然后直接在CAD中进行零件级别、模块级别的组装。

我想在编程的时候，是不是也会遇到这种情况，有些程序代码是跑龙套的，几乎所有程序都会出现那么几行相同的重复的代码，比如说我搞的算法中的for循环，一层两层的都有，给定义为一个固定格式，下次再录入的时候，直接插入这些组，然后在上面做一些小修改就可以了，省了很多打字的时间。

所以我感觉这种“组”操作的概念，无论是对编程，还是对一般的写作来说，都是很有必要的。

希望您能够采纳我的建议  ：）

**Comment by LiMinggang** [comment]
谢谢你这么认真，感觉用宏比较合适？编程用的sourceinsight啥的都是用宏来实现这个功能。给你个简单的插入例子

# Insert string
medit = MadEdit()
medit.InsertStr("-----------------------------------------------------\n|                 titles aligned center              |\n-----------------------------------------------------\n")

你存成文件后放到madedit的脚本下面，在工具栏最右侧有个下拉的三角，可以使用。一直在考虑支持快捷键，但没时间做，也没有想好

**Comment by zhulaojianke** [comment]
呵呵，试了一下，第一次用宏哈，感觉还是很神奇的。不过我感觉和“组”的操作还不一样，“组”操作更直观一些，可以很直观的定义“组”，插入组，删除组，而且对于很复杂的段落的插入，比如说，我需要在不同的文档中插入：

for i ∈ 0..5
     for j ∈ 0..2
           do something with i and j = k
     do something with bool(k)
这样的格式，如果用组操作的话，直接把这几行选择上，然后点击“定义组”即可，但如果在宏中写上面的这种程序框架，感觉就不方便也不自然了。当这个块更复杂的时候，比如说做一个“字符画”，用宏来一点点调字符间距的话，就有些使人抓狂了吧。 :)

**Comment by zhulaojianke** [comment]
我考虑的“组”操作的应用场景，是用户需要大批量的重复插入很多种的文本块。也就是说此时用户不再是进行文本级别的编辑，而是进行装配级别、系统级别的编辑，他操作的是大块大块的文字或者代码块，通过拼接组合形成不同的文章或者程序框架，然后再在这个框架中进行修改完善，得到一个他想要的文本或者程序。

**Comment by zhulaojianke** [comment]
我把标题修改了，我感觉用“组操作”这个名字比“智能插入”要更明白一些吧。

**Comment by LiMinggang** [comment]
这个实现不了，你想用程序实现自己的意图而不是一个特定的功能，太智能了，没法实现，只能是你自己用宏实现。

**Comment by LiMinggang** [comment]
就以你写的这段伪代码来说：
用宏基本就是：
for i in range(5):
　for j  in range(2):
　　 do something with i and j = k
　do something with bool(k)
但这个让Madedit去做，基本就是这一个功能，这个功能又不是通用的，用几千次的功能。

**Comment by zhulaojianke** [comment]
哦，我感觉您是误会了。我的意思是举一个例子，将那段文字当成一个“组”，纯粹的文本，把这个文本组存起来，然后需要用的时候，随时调出来插进某个文本里，而不是执行那段代码⋯⋯

您明白了么？不是要执行那么复杂的功能呀！

您在编程的时候就没有遇到过这样的情况么？某一段程序，这里也用得到，那里也用得到，索性就存成一个固定的组，用的时候直接整体插入进来就可以了，不用反复的敲键盘了。

我的那段for就是举了这么一个例子，是一个for循环的框架，可能不是正经的编程，我也不懂，我只是举了一个可能的for循环框架，您明白了么？这种框架可能在编程里经常会用到，当用到的时候，因为用户已经把它存成“组”了，所以直接调出来插进文本里去就可以了，很方便。

我举这个例子的目的是为了说明我提的这个功能在编程的时候也会经常使用到的。并没有执行什么代码。

您明白了吗？希望不要再发生误会了。

**Comment by zhulaojianke** [comment]
您可以这么想象，一个极端的例子，我把整篇文章，10000多字的文章，存成一个组，然后我就可以在任何文本文件里随时插入这10000多字了，而不必打开原来的文件去复制粘贴。如果我把很多篇这样的文章，比如说100篇，都存成了组，那么我就可以在一个新文档里通过“组”操作，通过排列组合制作出几十万篇毫无重复的新文档了。

组操作，这是多么大的生产力呀！！！

**Comment by zhulaojianke** [comment]
我一定争取使您理解我所说的“组操作”是什么意思，并不是非要有这个强大的功能不可，而是我不希望咱们之间发生误会。

**Comment by LiMinggang** [comment]
如果局限于上面这个组操作，完全可以用我给你的那个宏进行，python的文件操作我也没有优化掉（好像没有），所以，你可以在红里面写代码打开一个文件，读出内容，然后用刚才那段插入。
或者更像有些工具（NP++好像也支持）可以给你几个输入的地方，然后你粘过去，这样他记住这几段文本，随时可以插入。但这个跟那个宏的功能一样啊

**Comment by zhulaojianke** [comment]
嗯，我明白您的意思了，这个功能是需要用户自己定制的哈。确实如果按照我上面的想法来实现的话，对MadEdit-Mod要动的手术就很大了。我听您的。 :)

**Comment by LiMinggang** [comment]
是的，代价大还不说，主要是没法满足用户的各种需求

**Comment by LiMinggang** [comment]
Check the script named insertlines.mpy which is released with 0.4.3. You can also add your deleting functions

**Comment by LiMinggang** [comment]
插入自定义块也许可以用多剪贴板来实现

**Comment by zhulaojianke** [comment]
感觉这一次4.3.0的升级真的是非常大的！我若发现什么问题会及时在这里说的哈。

您是打算在MadEdit-Mod里使用多剪贴板功能么？真是个好消息。 :)

**Comment by LiMinggang** [comment]
这个做起来不难，也比较实用。所以可以考虑
