### ISSUE TITLE
Hope to put the "FixedWidthMode" to the Option

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#187]
This mode is really very good for a neatly text display!

上次我用中文说的部分西文字体的破折号占用的字符宽度导致文本不能正确对齐，后来发现了“固定宽度模式”这个法宝。然后我修改了.cfg文件使MadEdit-Mod默认使用“固定宽度模式”打开所有的文件。现在发现这个模式用起来真的特别特别爽！

所以在这里再次建议您能够把这个模式放在“选项”菜单中，作为一个复选框，允许用户通过这里的勾选设置使其成为MadEdit-Mod的默认打开模式。这样对文字对齐有要求的用户们就不用对每篇文章都应用一次这个模式了。

**Comment by LiMinggang** [comment]
跟原来那个重复了。关了Enable config fix width mode in global config #184

**Comment by zhulaojianke** [comment]
啊，是哈，您一改名字我还以为被删掉了呢⋯⋯真不好意思哈👅
