### ISSUE TITLE
Bug: An interesting behaviour of dot " · "

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#189]
在MadEdit-Mod中输入点号，我不知道英文状态下怎么输入，在中文状态下就是“ ` ”，esc键下方的那个键，在搜狗输入法中输入“dian”也可以打出dot “ · ”。在数学公式中的点乘可以用这个符号。

我给所有的26个英文大小写字母都定义了specialwordprefix，其他的都没有定义。但是却出现了如下的情况：
![](http://i3.piimg.com/ef600c4193e52ce2.jpg)
当其前面是英文的时候，它显示为specialword，当前面为空格，或中文的时候，又显示为普通文本。当单词以dot “ · ”开头的时候，英文就被当做普通文本了。这种情况在其他的半角符号中都是不存在的。

而且作为一个半角符号，dot “ · ”并不能被定义为delimiter。也很奇怪。

**Comment by LiMinggang** [comment]
你这个是全角字符？Esc下边那个在英文里面不是点。英文的点是中文里面敲句号的那个键。这个是点“.”，这个是你说的符号“`”

**Comment by zhulaojianke** [comment]
不是全角字符，而是输入中文的时候，按esc键下方的“ ` ”，就可以出“ · ”。我用的搜狗输入法的中文可以做到，应该其他的中文输入法也可以做到吧。

**Comment by LiMinggang** [comment]
这个还真不是英文的点，你看看这个：
````······E·....。。。

**Comment by zhulaojianke** [comment]
哦，好像是哈，我切换成全角，在MadEdit-mod里打出来的仍旧是“ · ”（这个就是用全角打出来的……）
好吧，只是看上去很像是半角的。

嗯，我还发现除了这个“ · ”之外，还有“ × ”（乘号）也具有这样的性质，即跟在specialword英文字符后面的时候，被显示为specialword，当前面有空格的时候就显示为一般文本了。

我琢磨着这可能与specialwordprefix的定义有关系，这个定义好像是说，以指定为specialwordprefix的字符开头的单词（且占有单个字符位置的字符，delimiter除外）都会被当做specialword处理。

嗯……那么，或许这个不是一个bug哈。

**Comment by LiMinggang** [comment]
“ × ”（乘号）英文是*(星号)
