### ISSUE TITLE
A bug in the typewrite mode

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#195]
在typewrite mode中，当我写很长的句子的时候，没问题，光标的位置是锁定的，但是当我按enter键之后，整个文档都往上移了一行，这样就造成了光标实际上在编辑框里向上移动了一行，而不是固定在某一行上。这种情况无论在折行还是没有折行的情况下，都会发生。我的描述可能不太清楚，您试试看，就知道了。

还有，就是我用backspace删除掉某一行的时候，typewrite mode就不起作用了，仍旧是光标下方的文档向上移动一行，而不是光标上方的文档向下移动。

btw，0.4.2中您对在查找替换框输入多行文本的处理方法真的很机智哈！佩服！

**Comment by zhulaojianke** [comment]
因为按enter换行的时候有这个麻烦，现在typewrite mode的功能反而不方便使用了……

另外，backup的文档文件存储在哪里了呢？

**Comment by LiMinggang** [comment]
刚修好，见 #196。 冏冏冏
多试试其他功能，正在准备出一个bug修复版0.4.2.1

**Comment by LiMinggang** [comment]
Backup应该是在你当前文件那个目录，后缀多了一个.bak

**Comment by zhulaojianke** [comment]
嗯，好的。这几个月我一直在用MadEdit-Mod，因为感觉到您这边确实挺忙的，我就没有来打搅哈。

**Comment by LiMinggang** [comment]
嗯，最近忙了一点，哈哈，所以赶着忙的时候状态好，就做了几个feature
后面看看能不能把那个search in bookmark做了

**Comment by zhulaojianke** [comment]
我很想找一个人或者一个团队合作开发软件呢，是一个画可以交互的流程图的软件（这种软件我从网络上查了好几天，还没有人想到过这个点子，所以不必担心知识产权问题了），功能从最简单的做起，一点点的丰富起来。不知道等您松下来的时候，是否愿意帮我实现它。:)

**Comment by LiMinggang** [comment]
什么是交互的流程图？我不是专业做UI的，然后你这个又跟我工作不怎么沾边，很难合作啊

**Comment by LiMinggang** [comment]
Backup和Auto save试过没有？如果没有啥大的bug我就要推0.4.2.1了

**Comment by zhulaojianke** [comment]
对不起，下午我做实验去了，一刻钟之前刚回来。试了autosave，没问题！但是backup我打开了，并没有生成.bak文件，是不是还需要其他的操作呢？

**Comment by zhulaojianke** [comment]
现在网络上能够提供交互功能的流程图有两种，一种是课件，基于flash、html5或者authorwave，但操作起来还是很麻烦；一种是专门的流程图软件，但只能画，提供交互功能的流程图也仅仅是在块状流程图的情况下，鼠标点击能够变色而已，终归是为了ppt一样的展示。

我希望的流程图是化工用的，比如说PFD（Process Flow Diagram）或者P&ID（Piping and Instrumentation Diagram）。很多大型的仿真软件能够提供这种流程的交互，但是其背后是一个很大的计算引擎，说白了就是当你点击一个流程图上的某个阀门的时候，就会影响到仿真计算结果。这个功能当然是工业级的，是可以通过单片机什么的控制实际的阀门，但这个功能太强大了，在化工设计的大部分时间是用不到的，而且稍微用一次，就会耗死比较弱的CPU。

我也是想做一个课件，也就是基于flash做一个动画，但不仅仅是某一个化工流程的动画，而是提供一个平台可以方便人们随意的搭建某一个化工流程，而且可以通过鼠标点击发生相应的动画即可，是否符合仿真计算我觉得无所谓，因为在化工的最初设计中，人们关心的是我设计的这套工艺需要怎么来操作，可以很快的发现自己工艺中的问题，而不是具体某个贮罐里的瞬时反应温度是什么。

网络上这种课件也不少，但都是专业的公司使用flash或者更高级的视频制作软件来做的，让工程师自己搭建的工具，竟然一个也没有！

我觉得如果用flash搭建一个类似于电子游戏的平台，给工程师提供一些基本的可以通过鼠标拉伸修改形状的模块，工程师在使用的时候，只要用鼠标把相应的反应容器、蒸馏设备等等拖放到编辑界面，然后简单的用鼠标画线，把各个设备连接起来，当管线交叉的时候，可以自动跳线，当安装阀门的时候，可以自动断线，这样就很快的搭建出一个可以很复杂的化工流程了。

以上的功能用visio就可以实现，下面就是交互的部分，这部分是visio做不到的，而且是其他画流程图软件都做不到的。

比如说，假设某一个容器里有水，我用鼠标点击打开某一个阀门，就可以看到某些管道因为里面有水而变成了蓝色，当我关掉这个阀门，流体断开了，阀门后面的管道就恢复为白色。基本的功能就是这么简单！

然后我们可以慢慢的把它变复杂，比如说让管道有粗细之分，这样流量就不同，当我打开一个阀门，管道里就会有水，但流量很低，当我再打开一个泵，流量就会上去，此时就会在流量计处有一个读数。从上面定性的分析，变成定量的分析。

嗯，这样可以不断的复杂下去，比如说引入不同类型的阀门，引入流体的粘度系数等等。

所有的这些目的都是为了能够通过简单的计算（化工计算部分我已经有了），让工程师们可以快速的查看自己的流程哪些地方设计的不合理，不如说该有阀门的地方没有，该考虑流体沉积的地方他没有给出缓冲弯，等等，也是对一个行业有益的设计吧。

我前几天是打算学习flash呢，但一看要按帧设计动画……我就二逼了。 :(

**Comment by zhulaojianke** [comment]
好像autosave模式是关不掉的？我取消选择了autosave模式之后，按确定，然后关闭程序，再次打开MEM之后，发现仍旧是autosave模式。

现在打字的时候，整个界面一闪一闪的，每次录入一个字符或者删除掉一个字符，或者仅仅是按enter，都会闪。不管是否打开backup模式都是如此。

**Comment by LiMinggang** [comment]
闪烁的bug是已知的

**Comment by LiMinggang** [comment]
Flash已经是过时的技术

**Comment by zhulaojianke** [comment]
但是我用0.4.1的时候就不会闪，用0.4.2的时候就闪了…… :s

**Comment by LiMinggang** [comment]
是的，是0.4.2引入的，已经修了
