### ISSUE TITLE
Known issues of 0.4.2

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/madedit-mod#197]
Will be fixed in 0.4.2.1 quickly
New: Code performance improvement for Window list(Performance, menu blink issues)
Fix: Multiple selection does not work with Save/SaveAs(Windows List dialog) #193
Fix: Extra scroll issue while pressing enter key in Typewriter mode introduced by 0.4.2

**Comment by zhulaojianke** [comment]
好像autosave模式是关不掉的？我取消选择了autosave模式之后，按确定，然后关闭程序，再次打开MEM之后，发现仍旧是autosave模式。

现在打字的时候，整个界面一闪一闪的，每次录入一个字符或者删除掉一个字符，或者仅仅是按enter，都会闪。不管是否打开backup模式都是如此。

backup模式开启后并没有发生什么，也没有在文件所在的文件夹里生成.bak文件。

**Comment by zhulaojianke** [comment]
嗯，我用everything搜了一遍，没有在任何地方生成.bak文件。

**Comment by zhulaojianke** [comment]
不是整个界面在闪，而只是菜单栏在闪。不仅仅是录入、删除、换行的时候，当使用鼠标选择某段文字的时候，随着鼠标的移动，菜单栏也会闪。

**Comment by zhulaojianke** [comment]
而且当我用鼠标选择多行的时候，所选择的范围不会随着鼠标的运动而有所改变，是有滞后的，也就是说当最后鼠标停留在某个位置了，才会出现被选择的范围（被选择的背景变色）。

**Comment by zhulaojianke** [comment]
又试了试0.4.1，不存在闪动的问题，也不存在选择滞后的问题。看来这个问题是在0.4.2中出现的。

**Comment by LiMinggang** [comment]
是的，0.4.2引入的

**Comment by LiMinggang** [comment]
Backup的规则如下：
1.在文件被load的时候，认为没有被backup，存盘后变成已经被backup，在文件被关闭前都认为已经被backup，重新打开被认为没有backup，修改再存盘会重新backup（覆盖已有的backup）
2.另存为不会backup文件
3.新创建的不会有backup

**Comment by LiMinggang** [comment]
闪动问题已经修复

**Comment by zhulaojianke** [comment]
哦，看上去有些雾水⋯⋯跟我理解的“备份”不一样哈。我感觉备份是当自己目前的这份文件由于电脑崩盘了，文件损坏了，不能用了，此时会有一个备份可以继续用。

或者是在文件打开的时候就出现一个备份，当我编辑这个文件的时候，实际上就是在编辑这个备份，我存盘也是在向这个备份里存，而不是修改原来的文件。这样有一个好处，就是我对文件可以保留若干个文件的副本或者版本，便于以后参照修改。

嗯，所以我理解吧，autosave实际上是定时的save，而backup实际上是定时的save as。比如说我设定每一个小时backup一次，也就是每个小时MEM就会自动记录一个当前文档（或者未存盘文档的新版本）为一个新的同扩展名文件，文件名是当前文件名+时间戳，这样备份就会在实际的对文档做很大规模编辑的时候起到很大的作用了。


如此呢，我觉得backup功能不宜放在“选项”菜单里，而是放在“文件菜单”中，由用户自己选择对哪一篇文档进行备份。很有可能一些无关紧要的辅助性草稿性的文档是没必要backup的，对它们进行备份只会增加一些垃圾文件。您看呢？

**Comment by zhulaojianke** [comment]
也就是说backup功能是针对个别的很重要的且进行大量修改的文件来使用的，应当作为文档的属性，而不是对整个软件的定制。

backup的性质我感觉与一篇文档的字体、行距、字号等等是一样的，是随着文档走的。可以在打开一篇文档之后，通过菜单选择backup功能，使其具备这个属性，而且每次被MEM打开时都可以被识别出来，用户也可以随时取消它。

**Comment by zhulaojianke** [comment]
还有，现在MEM可以记住每篇文件的行间距了，但是却不能统一设置所有打开文件的行间距了⋯⋯ :(

比如说我喜欢150%的间距，但是现在默认的是100%，我需要打开一个文件就修改一次行间距——尽管有一些文件我需要他们是100%的间距。

能否在“选项”菜单里加一个“默认行间距”的选项，使用户按照自己的习惯设定新建或新打开文件的默认行间距——等到这样用户对个别文件修改了默认的间距之后，MEM也能记住呢？

嗯，现在的默认行间距是100%，用户修改了某篇文档的行间距为150%，MEM就记住了。那么如果默认的行间距是120%或者用户自定义的一个，其他功能不变，用户仍然可以对个别文档进行修改行间距而且被MEM记住，应该也可以实现吧？（不知道我说明白了没有⋯⋯）

**Comment by LiMinggang** [comment]
就是上文提到的menu blink，已经修复

**Comment by LiMinggang** [comment]
“默认行间距”已经修复。
Autobackup这个没法做成你说的那种，那个一会就把你的文件给弄乱了，备份太多了。你真需要这个功能还不如写的脚本或者工具来做。不应该依赖编辑器啊，不然早有编辑器支持了。本身不是很难，但是带来很多误解和混乱
我设想的是就是一次修改之前做一次备份，这样你如果觉得改错了，还有一次机会。

**Comment by LiMinggang** [comment]
这种autobackup模式是可以做到的，但是由于这个编辑器的社区不是很活跃，不然可以搞一个投票。你新开一个issue吧，讨论一下。
最好的方式是给用户一个上限，比如最多存多少个备份。

**Comment by zhulaojianke** [comment]
啊，我想还是等我用一段时间backup功能之后再说吧，直到现在我还没遇到过.bak文件呢……说不定您现在的这个设定会更好呢，是吧？ :)

**Comment by zhulaojianke** [comment]
嗯，前端时间我在与另外一个朋友合作一个地图编辑软件的时候，也遇到了备份的问题，不给备份的机会肯定不行，尤其是在对一个文件在没有另存的情况下进行比较大的修改的时候，风险很大；但给多了就跟您说一样，会出现不少垃圾文件。后来我和那个朋友商量的结果是，让用户手动备份，设置一个快捷键以及一个按钮，执行一次备份命令，就会在文档所在的文件夹里出现一个带有时间戳的.bak文件，多次执行，就会多次产生，直到完成了这份文件的所有编辑最后定稿之后，再由用户自己删除文件夹里原来产生的那些.bak文件，此时就可以筛选哪些是需要保留下来的，哪些是以后再也用不到的。

而且在那个地图软件里，我们还设计了一个弹窗，就是调出备份——我管那个叫“版本回滚”，也就是我正在编辑一个文件，并且已经建立了若干个备份（都在当前文档所在的文件夹里），此时我要回滚到以前的某一个版本，就有一个按钮，我点击之后，出现一个弹窗，类似于您现在开发使用的那个windows list弹窗，选择相应的备份版本，点击导入，然后就可以在以前的某个版本的基础上继续干活儿了。

不知道这个经验您感觉怎么样，尽管没有自动化，完全是用户自己控制的手动操作，但要随意得多，而且不管用户的使用情况怎么复杂，这种手动备份—恢复的功能都可以满足。

呵呵，如果您觉得好，希望能够加到0.4.3或者0.4.2.1中哈！ :)

**Comment by LiMinggang** [comment]
这个倒是可以做，点按钮，然后自动帮用户起名字然后备份。可以把这个写到刚开的那个里面。

**Comment by zhulaojianke** [comment]
哦，我新开那个issue说的就是这个……

**Comment by LiMinggang** [comment]
0.4.2.1 Released
