### ISSUE TITLE
Let the user to do the backup selfly

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#198]
前端时间我在与另外一个朋友合作一个地图编辑软件的时候，也遇到了备份的问题，不给备份的机会肯定不行，尤其是在对一个文件在没有另存的情况下进行比较大的修改的时候，风险很大；但给多了就跟您说一样，会出现不少垃圾文件。后来我和那个朋友商量的结果是，让用户手动备份，设置一个快捷键以及一个按钮，执行一次备份命令，就会在文档所在的文件夹里出现一个带有时间戳的.bak文件，多次执行，就会多次产生，直到完成了这份文件的所有编辑最后定稿之后，再由用户自己删除文件夹里原来产生的那些.bak文件，此时就可以筛选哪些是需要保留下来的，哪些是以后再也用不到的。

而且在那个地图软件里，我们还设计了一个弹窗，就是调出备份——我管那个叫“版本回滚”，也就是我正在编辑一个文件，并且已经建立了若干个备份（都在当前文档所在的文件夹里），此时我要回滚到以前的某一个版本，就有一个按钮，我点击之后，出现一个弹窗，类似于您现在开发使用的那个windows list弹窗，选择相应的备份版本，点击导入，然后就可以在以前的某个版本的基础上继续干活儿了。

不知道这个经验您感觉怎么样，尽管没有自动化，完全是用户自己控制的手动操作，但要随意得多，而且不管用户的使用情况怎么复杂，这种手动备份—恢复的功能都可以满足。

呵呵，如果您觉得好，希望能够加到0.4.3或者0.4.2.1中哈！ :)

**Comment by zhulaojianke** [comment]
在进行“版本回滚”的时候发生了两件事情，我感觉可能是一般的软件没想到的：
（1）修改了现在正在编辑的文档的文件名，使其成为打上时间戳的.bak文件；
（2）将用户所选的需要编辑的版本备份的文件名也修改了，去掉时间戳和.bak后缀。
这样就不必让现在的程序去识别.bak文件的类型了，而且也可以使现在正在编辑的文件不至于丢失。

比如说我现在正在编辑 a.txt文件，并且已经用备份功能生成了 a-201605251130.txt.bak、a-201605251200.txt.bak，现在是13:00。下面我要调用“a-201605251130.txt.bak”进行编辑，从“版本回滚”里找到这个备份，然后点击导入，此时当前窗口的内容就变为“a-201605251130.txt.bak”的内容了，而且其文件名被改为a.txt，而刚才我正在编辑的内容被存为“a-201605251300.txt.bak”，打开文件所在的文件夹就可以看到。

**Comment by LiMinggang** [comment]
可以限制个数，但是时间戳，最好还是自己查文件属性比较好。

**Comment by zhulaojianke** [comment]
嗯，按您的方法也挺好的，加时间戳的目的也是为了能够将多个备份区分开哈。
