### ISSUE TITLE
Need the MadEdit-Mod could be Launched faster

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#200]
可能是因为现在的MadEdit-Mod增加了很多功能吧，现在的这个版本的启动速度要比以前慢很多，从点击图标到打开，需要用7秒钟。希望您能够使它启动的更快一些哈，不知道是不是会比较麻烦做到了。真是麻烦您啦！

**Comment by zhulaojianke** [comment]
启动MadEdit-Mod之后，第一次进入“选项”菜单，十次里有两到三次需要使用11秒钟！

**Comment by zhulaojianke** [comment]
退出程序需要1秒钟。

**Comment by zhulaojianke** [comment]
我测试的是0.4.2.1。

**Comment by LiMinggang** [comment]
又肯能是选项太多了，如果这个原因，是解决不了的，会越来越慢

**Comment by zhulaojianke** [comment]
您那边启动速度一般是多少呢？

**Comment by LiMinggang** [comment]
讨论这个问题先得说清楚系统：
我这里是win7 64 i7 4770 4核 8G

启动和开Option基本是秒开。会load 4个小文件
这个版本唯一大的变化是升级了wxWidgets，从3.0.2到3.10，这个也算不算大的变化。

**Comment by LiMinggang** [comment]
1.New: Hope MadEdit-Mod could load more open files history than 9 #179
这个是影响启动速度，但是也就多读了十几条文件记录
2.New: Redesign of Search Results view----Hope to add search key words or expression on the result tree title on the left of the file path #137
这个跟启动和option无关
3.New: Save LineSpacing, Line Wrap Mode and Edit Mode for opened files #186
load文件时候会多一点点代码
4.New: Enable config fix width mode in global config #184
option对话框多了一个checkbox，多了一个配置项，没这么大影响
5.New: Wordwrap of input of search/replace dialog #175
无关
6.New: Use icons or symbols replace the words in the quicksearch bar #181
无关
7.New: Hope MadEdit-Mod could Autosave, Backup files, and have Autolink funciton #135
无关
8.New: Window list function(Activate, Save, Save As and Close)
打开文件会多一个菜单项，无关

**Comment by zhulaojianke** [comment]
好吧，我的配置跟您的差不多……我还是找我这边儿的原因吧。

**Comment by zhulaojianke** [comment]
非常奇怪，我在我家里的台式机上打开MadEdit-Mod就非常快，但是我的笔记本上打开MEM就慢的厉害……

**Comment by LiMinggang** [comment]
同样的系统？有没有杀毒软件啥的？按理说笔记本除了硬盘慢---Madedit特地做了压缩，其他差不多
