### ISSUE TITLE
Hope typewrite mode could work when use "Backspace" or  "Delete"

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#203]
现在的打字机模式已经很棒了，在回车、打字折行的时候，能够让光标停留在一定的位置。但是当打错了字，需要使用Backspace或者Delete删除的时候，删除几行，光标就会向上走几行，还需要用鼠标滚轮把光标拉回刚才的位置，仍旧不是很方便，会打断写作。

所以我希望在删除的时候，typewrite模式能够保持住。如果使用上下左右键移动光标的时候，它也可以始终保持在固定的那一行中就更好啦！

希望您能采纳哈！

**Comment by zhulaojianke** [comment]
**我觉得解决这个问题的关键是要在开头也”留白“。**

现在的MadEdit-Mod在文本的结尾处是给出留白的，也就是当用鼠标滚轮将文本滚动到文本的末尾的时候，除了能够显示最后一行，下面的全是空白，这样的设定真的是太好了！
在这种情况下使用typewrite模式编写文本的最后一行的时候，下面总会留出空白，以保证光标处于某一个特定的行。

如果能够在文本的开头处也有这样的留白，也就是当将鼠标滚轮向上滚动到文本的开头的时候，在编辑框里除了能够显示文本的第一行之外，上面全是空白。这样当我使用Backspace或者Delete删除文本的时候，也能够保证光标始终停留在某一个特定的行上了。

**Comment by LiMinggang** [comment]
删除这个有点tricky，当时想过一点，后来想到删除选择区比较费劲，所以最多能支持删除非选择区的时候，其他的只能自便了

**Comment by zhulaojianke** [comment]
嗯，我的意思也是删除非选择区，最常见的就是用Backspace或者Delete删除一两个字，此时恰恰在这里发生了折行，结果光标就会向上移动。

对于选择区的删除，我觉得一般都是发生在书写完一篇文档之后的整体编辑中了，此时没必要使用打字机模式。


**我觉得上下左右移动光标的时候，能够保证typewrite模式也很重要哈。**比如说我在打一大堆字儿的时候，并没有事先想好语言的顺序，很有可能先写了句子的后半部分，然后把光标用↑↓←→的方向键移动到前面的某个地方，补充写上句子的前半部分。**这种移动是非常小的，不必使用鼠标，就可以很快的定位到我需要插入的地方。**（也就是说鼠标点击所导致的光标移动不必受到typewrite模式的影响。）但现在在typewrite的模式下，当移动光标的时候，只是光标本身在动，如果能够在移动光标的时候，是整篇文章上下的scroll，而光标位置在行上是固定的（左右移动不受影响，只是上下换行），那么用起来就更舒服了。

**Comment by LiMinggang** [comment]
嗯，现在基本都支持选择区了，backspace和插入状态（文本模式）。

**Comment by LiMinggang** [comment]
Up/Down那个跟这些支持不一样，这种是要刷屏的，Up/Down如果也刷屏你就会觉得会闪烁。所以，不做了

**Comment by zhulaojianke** [comment]
好的，明白了哈，您辛苦了 :)

**Comment by zhulaojianke** [comment]
再赞一次这个typewrite模式，我感觉解决了我在写作时20%的问题，大大减少了我的分心。真的很赞！

如果能够在滚动条的右键里再有一个“滚动到这里”（这个以前提过，但忘了是哪个issue了），在写东西的时候，基本上就不会存在什么分心了吧。 :)

**Comment by LiMinggang** [comment]
有过一个评测，MadEdit对大文件的处理还是有很大的问题，这个是原作者的遗产，最后一个从原作者发出的信息是打算解决大文件的问题，然后就没有然后了。我自己也是一直没有想清楚，比较复杂。然后自己又没有需求，就没动力。

2016-06-21 18:14 GMT+08:00 Zhu Xinyan <notifications@github.com>:

**Comment by zhulaojianke** [comment]
我用MadEdit-Mod处理过的文本文件最大的也就是200MB左右，是把一份硬盘中的文件目录列出来，然后用正则表达式修改格式，查找我需要合并的文件，里面还包括了我的注册表文本……平时编辑的文件能够上2MB就难得了。我接触并编辑大文本文件的机会也不多。 :(

**Comment by LiMinggang** [comment]
是的，200兆按现在的MadEdit系列处理非常费劲，只能按照hex mode处理，转成文本模式就基本完蛋

2016-06-21 19:42 GMT+08:00 Zhu Xinyan <notifications@github.com>:
