### ISSUE TITLE
Hope to use hotkey to  launch the macro saved

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#208]
使用那个insertlines的宏插入行非常爽，弹出一个对话框，输入数字，就可以插入相应的行数了，太棒了！对于有编程恐惧症的我来说简直是福音！

我希望能够丰富这个功能：
（1）通过输入负数，可以删除光标下方相应的行数，最好能够自动识别光标下方的空白行数，然后在对话框中给出一个建议删除的行数，这样就更方便了！
（2）把这个宏从“本底脚本列表”中提出来，单独成为一个命令（尽管它还是以宏来完成命令的），这样用户就可以给这个命令自定义快捷键了，需要进行插入、删除行的操作的时候，热键调出来，输入数按回车就可以了，那就更加人性化了。

插入和删除指定的空白行，这样的操作对于修改文本来说是经常要做的操作，希望能够强化这个功能 :)

非常感谢您！

**Comment by LiMinggang** [comment]
指定快捷键一直在琢磨，一直没有想好怎么做。

**Comment by zhulaojianke** [comment]
在菜单里可以找到宏的脚本列表，如果在选项面板中的“按键”菜单里也有这个列表，不就可以让用户自定义快捷键了么？

**Comment by LiMinggang** [comment]
目前MadEdit的快捷键和菜单都是写死在文件里面的，动态加的目前不支持。一种变通的方法就是预留一些供用户使用----有些编辑器好像是这么干的，先空着放在那里。

这个Issue你改改，负数删除那个可以修改宏来搞定，不是对madedit-mod的修改，我可以发给你。
你把这个issue改成给宏增加热键就可以了

**Comment by LiMinggang** [comment]
`    if len(result) > 0:
        ng = result[0]
        neg = False
        if ng == '-':
            result = result[1:]
            neg = True
        num = int(result)
        if num > 0:
            if neg == False:
                lines = newline * num
                medit.InsertStr(lines)
            else :
                if num != 0:
                    for i in range(num):
                        medit.DeleteLine()`

**Comment by LiMinggang** [comment]
[insertlines.mpy.txt](https://github.com/LiMinggang/madedit-mod/files/340743/insertlines.mpy.txt)

**Comment by zhulaojianke** [comment]
呵呵，刚才睡午觉了。试了您新写的这个宏，可以在一个命令里完成添加和删除行了，确实要方便很多。

如果将这个宏也写死在文件里，作为一个固定功能，就不必使用“动态添加”了吧？

**Comment by zhulaojianke** [comment]
主要是现在我在对一篇文稿的基础上进行二次创作（改写），真的是经常需要使用这个插入空行和删除空行的操作，每次都从菜单或者右键菜单里找那个命令，确实有些麻烦，如果能够用一个快捷键简单的调出这个宏命令的话，就方便得多了。

**Comment by LiMinggang** [comment]
一个好办法是在文件里面加一行特殊的标识，这样用户可以自定义，也不需要存储在配置里面

**Comment by zhulaojianke** [comment]
没太明白，不过您感觉有办法解决它，这是个好消息哈！
