### ISSUE TITLE
When I paste some lines, the typewrite mode is not working

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#209]
当我向文本中粘贴若干行新的文本时，typewrting模式就不会起作用了，也就是在粘贴后文本并没有上滚，而是向下延续，当粘贴的文本比较多的时候，光标就跑到编辑框的底部了。希望您能够处理这个bug哈！

**Comment by LiMinggang** [comment]
这个不一定能支持

**Comment by zhulaojianke** [comment]
希望能够支持吧，typewriting模式真的是难得的好东西呀。 :)

另外#208也望能够实现，现在使用鼠标来做插行确实不方便哈。

**Comment by LiMinggang** [comment]
没有严格测试，简单试试没啥问题
