### ISSUE TITLE
How to use the "goto the last edit position"?

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#212]
您这次升级的动作很大，我初步测试仅发现“回到上一个编辑位”和“跳入下一个编辑位”的功能不知道怎么实现。还望您能够帮助我。还有另外一个，我单开一个issue。
7.New: Seperate "goto the last edit position" and ¡°goto the next edit position¡±function from Undo #169

**Comment by LiMinggang** [comment]
Enable record caret movement

**Comment by zhulaojianke** [comment]
我打开了记录光标位置的选项，但还是不知道怎么操作。

比如说：
我在某一行的末尾写下“试试看”，然后跳过5行之后再写一个“试试看”，然后按ctrl + z，它先把我最后写的那几个字删除掉了，才会跳回上一个编辑位。而这个并不是“回到上一个编辑位”呀！如果是“回到上一个编辑位”，应该是我按什么快捷键之后，它会回到我第一次写的“试试看”的末尾处才对呀。

**Comment by LiMinggang** [comment]
ctrl-z是undo，Alt+,和.是move caret的快捷键，但是输入字符是不作为caret movement被记录的

2016-07-29 10:12 GMT+08:00 Zhu Xinyan <notifications@github.com>:

**Comment by zhulaojianke** [comment]
前几天我们单位放暑假，今天试了您说的这个功能，喜出望外！非常感谢您哈！
