### ISSUE TITLE
Hope to use a custom hotkey to access the history files

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#213]
您把打开历史文件的图标放进了标准工具条里，原来我仅打开一个快速搜索工具条即可以把所需要的功能都实现了，而现在需要打开两个工具条了，而且标准工具条里的大部分功能都可以用快捷键实现，只有打开历史文件需要点击图标。
8.Fix: Move recent files tool bar item from Quick search to Standard

我想您可能觉得把这个图标放在搜索工具栏里很不讲究，没秩序。那么您看看能否让用户对这个功能设置快捷键呢？也就是当用户使用这个快捷键之后，可以弹出一个窗口，里面是历史文件列单，点击所要打开的历史文件之后，文件打开，窗口自动关闭。这样，就不会有图标上的麻烦了。

如果您感觉这样可行的话，我希望能够在弹出窗口中实现多选，多个文件同时打开，这样就更方便了哈！

另一个issue……
————————————————————————————————————————

还有一个问题，我感觉提不上issue，就是调用宏的快捷键不能用户自定义么？我从选项→按键面板里没有找到可以自定义这个快捷键的方法。您安排的ctrl+shift+1的快捷键可能会和用户自定义的其他快捷键冲突了，而且不好记住哈。用一只手同时按住ctrl+ shift +1也不方便。
我建议使用alt + i ，单手可以操作完成，而且左右两个alt都可以用上，稍微灵活一些。

**Comment by LiMinggang** [comment]
You can customize the hot key by editing the script.

**Comment by zhulaojianke** [comment]
嗯，明白了，非常方便哈！谢谢！

对第一个issue，我在选项→按键面板里点击“最近打开的文件”，发现无法给它赋上自定义快捷键。

**Comment by LiMinggang** [comment]
那个最近打开的文件是第一级菜单，（因为还有下级菜单）所以没法赋予热键，只有最终的菜单项可以。正在考虑是不是如你建议的加一个弹出对话框的菜单项来列出所有历史文件（比菜单中要多）
