### ISSUE TITLE
What is ColumeAlignLeft and ColumeAlignRight? and How to use them?

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#216]
在“编辑”菜单的“高级”中最下面有“列对齐（向左）”和“列对齐（向右）”两个选项，这是做什么用的？怎么使用它呢？

**Comment by LiMinggang** [comment]
用在列编辑里面，对你光标左右侧的空格和Tab字符进行删减。
Before:
![image 2](https://cloud.githubusercontent.com/assets/4847132/17649553/ecbc8198-626a-11e6-9630-76ce37553961.png)
After Align Left
![image 3](https://cloud.githubusercontent.com/assets/4847132/17649558/fbd92a28-626a-11e6-92dc-5e8d2d72cb3a.png)
