### ISSUE TITLE
a bug when move up

### ISSUE THREAD

**Issue by ztjal** [LiMinggang/madedit-mod#217]
---------------------------
wxWidgets Debug Alert
---------------------------
..\..\src\msw\dc.cpp(2084): assert ""source"" failed in wxMSWDCImpl::DoStretchBlit(): wxMSWDCImpl::Blit(): NULL wxDC pointer

Call stack:
[01] initredirector                          
[02] initredirector                          
[03] initredirector                          
[04] initredirector                          
[05] initredirector                          
[06] initredirector                          
[07] initredirector                          
[08] initredirector                          
[09] initredirector                          
[10] initredirector                          
[11] initredirector                          
[12] DispatchMessageW                        
[13] DispatchMessageW                        
[14] GetMenuItemInfoW                        
[15] KiUserCallbackDispatcher                
[16] InvalidateRect                          
[17] GetWindowTextW                          
[18] GetWindowTextW                          
[19] Ordinal119                              
[20] Ordinal104                              
[21] CloseThemeData                          

Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.
---------------------------
是(Y)   否(N)   取消   
---------------------------
MadEdit-Mod_X64
再现方法：
1，十六进制打开一个能占满编辑区域的文件，点着MadEdit的标题栏移动，向下移，将编辑区域移到超过WINDOW的任务栏，一半以上吧。
2，再在点着MadEdit的标题栏向上移动（快），很容易就出上边的问题了。
这个问题不是你的问题，在之前你还未接手的原版就有这个问题。

**Comment by LiMinggang** [comment]
看起来有点像是wxWidgets的问题

**Comment by LiMinggang** [comment]
MadEdit.exe!wxDefaultAssertHandler(const wxString & file, int line, const wxString & func, const wxString & cond, const wxString & msg) Line 1159	C++
 	MadEdit.exe!wxOnAssert(const char * file, int line, const char * func, const char * cond, const wchar_t * msg) Line 1260	C++
 	MadEdit.exe!wxMSWDCImpl::DoStretchBlit(int xdest, int ydest, int dstWidth, int dstHeight, wxDC * source, int xsrc, int ysrc, int srcWidth, int srcHeight, wxRasterOperationMode rop, bool useMask, int xsrcMask, int ysrcMask) Line 2084	C++
 	MadEdit.exe!wxMSWDCImpl::DoBlit(int dstX, int dstY, int dstWidth, int dstHeight, wxDC * source, int srcX, int srcY, wxRasterOperationMode rop, bool useMask, int srcMaskX, int srcMaskY) Line 2074	C++
 	MadEdit.exe!wxDC::Blit(int xdest, int ydest, int width, int height, wxDC * source, int xsrc, int ysrc, wxRasterOperationMode rop, bool useMask, int xsrcMask, int ysrcMask) Line 1203	C++
 	MadEdit.exe!MadEdit::PaintHexOffset(wxDC * dc, int x, int y, const int * hexdigit, const int * width, int count) Line 2596	C++
 	MadEdit.exe!MadEdit::PaintHexLines(wxDC * dc, wxRect & rect, int toprow, int rowcount, bool painthead) Line 2683	C++
 	MadEdit.exe!MadEdit::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 11361	C++
 	MadEdit.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2667	C++
 	[External Code]	
 	MadEdit.exe!DoShowAssertDialog(const wxString & msg) Line 1305	C++
 	MadEdit.exe!wxAppTraitsBase::ShowAssertDialog(const wxString & msgOriginal) Line 994	C++
 	MadEdit.exe!wxGUIAppTraitsBase::ShowAssertDialog(const wxString & msg) Line 502	C++
 	MadEdit.exe!ShowAssertDialog(const wxString & file, int line, const wxString & func, const wxString & cond, const wxString & msgUser, wxAppTraits * traits) Line 1382	C++
 	MadEdit.exe!wxAppConsoleBase::OnAssertFailure(const wchar_t * file, int line, const wchar_t * func, const wchar_t * cond, const wchar_t * msg) Line 865	C++
 	MadEdit.exe!wxDefaultAssertHandler(const wxString & file, int line, const wxString & func, const wxString & cond, const wxString & msg) Line 1174	C++
 	MadEdit.exe!wxOnAssert(const char * file, int line, const char * func, const char * cond, const wchar_t * msg) Line 1260	C++
>	MadEdit.exe!wxMSWDCImpl::DoStretchBlit(int xdest, int ydest, int dstWidth, int dstHeight, wxDC * source, int xsrc, int ysrc, int srcWidth, int srcHeight, wxRasterOperationMode rop, bool useMask, int xsrcMask, int ysrcMask) Line 2084	C++
 	MadEdit.exe!wxMSWDCImpl::DoBlit(int dstX, int dstY, int dstWidth, int dstHeight, wxDC * source, int srcX, int srcY, wxRasterOperationMode rop, bool useMask, int srcMaskX, int srcMaskY) Line 2074	C++
 	MadEdit.exe!wxDC::Blit(int xdest, int ydest, int width, int height, wxDC * source, int xsrc, int ysrc, wxRasterOperationMode rop, bool useMask, int xsrcMask, int ysrcMask) Line 1203	C++
 	MadEdit.exe!MadEdit::PaintHexOffset(wxDC * dc, int x, int y, const int * hexdigit, const int * width, int count) Line 2596	C++
 	MadEdit.exe!MadEdit::PaintHexLines(wxDC * dc, wxRect & rect, int toprow, int rowcount, bool painthead) Line 2683	C++
 	MadEdit.exe!MadEdit::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 11361	C++
 	MadEdit.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2667	C++
 	[External Code]	
 	MadEdit.exe!wxWindow::MSWDefWindowProc(unsigned int nMsg, unsigned __int64 wParam, __int64 lParam) Line 2211	C++
 	MadEdit.exe!wxWindow::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3530	C++
 	MadEdit.exe!wxTopLevelWindowMSW::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 321	C++
 	MadEdit.exe!wxFrame::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 897	C++
 	MadEdit.exe!MadEditFrame::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3719	C++
 	MadEdit.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2667	C++
 	[External Code]	
 	MadEdit.exe!wxWindow::MSWDefWindowProc(unsigned int nMsg, unsigned __int64 wParam, __int64 lParam) Line 2211	C++
 	MadEdit.exe!wxWindow::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3530	C++
 	MadEdit.exe!wxTopLevelWindowMSW::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 321	C++
 	MadEdit.exe!wxFrame::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 897	C++
 	MadEdit.exe!MadEditFrame::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3719	C++
 	MadEdit.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2667	C++
 	[External Code]	
 	MadEdit.exe!wxGUIEventLoop::ProcessMessage(tagMSG * msg) Line 169	C++
 	MadEdit.exe!wxGUIEventLoop::Dispatch() Line 229	C++
 	MadEdit.exe!wxEventLoopManual::ProcessEvents() Line 228	C++
 	MadEdit.exe!wxEventLoopManual::DoRun() Line 273	C++
 	MadEdit.exe!wxEventLoopBase::Run() Line 76	C++
 	MadEdit.exe!wxAppConsoleBase::MainLoop() Line 380	C++
 	MadEdit.exe!wxAppConsoleBase::OnRun() Line 302	C++
 	MadEdit.exe!wxAppBase::OnRun() Line 312	C++
 	MadEdit.exe!wxEntryReal(int & argc, wchar_t * * argv) Line 503	C++
 	MadEdit.exe!wxEntry(int & argc, wchar_t * * argv) Line 181	C++
 	MadEdit.exe!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Line 290	C++
 	MadEdit.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 28	C++
 	[External Code]

**Comment by LiMinggang** [comment]
Confirmed

**Comment by ztjal** [comment]
咦？修正了？不如考虑出个ALPHA版/每夜版之类的测试下？

**Comment by LiMinggang** [comment]
你用的是windows哪个版本？64还是32？

**Comment by ztjal** [comment]
64位WIN10。

**Comment by LiMinggang** [comment]
Got，回头通知你到preview目录去下载。另外有遇到过ctrl-F搜索导致程序挂死么？在网上看到过有人说在win8上会出现，我用win7，没遇到过。怀疑是VC2010带的SDK不兼容win8，不知道win10是不是一样，都是metro风格的。

**Comment by ztjal** [comment]
未遇到过，我用的了VS2015编译的那个版本。
不过倒是遇到另一个没任何提示就直接关闭程序的问题。
现在方法：如果“查找结果”窗口找到很多结果，且每个结果的分支都有很多内容，折叠一个差不多在顶位的结果，很容易就“没了”。

**Comment by LiMinggang** [comment]
“没任何提示就直接关闭程序”
看看在你的程序目录里面有没有崩溃的日志文件，如果有，新开一个issue把文件附上。

**Comment by LiMinggang** [comment]
VS2015的64位build出了，https://sourceforge.net/projects/madedit-mod/files/Preview/。验证完反馈一下结果。

**Comment by ztjal** [comment]
行，试了几次都没问题了，等日常使用时长期验证吧。
