### ISSUE TITLE
一个没任何错误提示程序就关了的问题

### ISSUE THREAD

**Issue by ztjal** [LiMinggang/madedit-mod#218]
> [00]:[00007FF66F1F2B19] (0)	initredirector()
> [01]:[00007FF66F26E4AA] (0)	initredirector()
> [02]:[00007FF66F220AE7] (0)	initredirector()
> [03]:[00007FF66F1DD302] (0)	initredirector()
> [04]:[00007FF66F3F4528] (0)	initredirector()
> [05]:[00007FF66F428274] (0)	initredirector()
> [06]:[00007FF66F427D89] (0)	initredirector()
> [07]:[00007FF66F428E2D] (0)	initredirector()
> [08]:[00007FF66F42814D] (0)	initredirector()
> [09]:[00007FF66F427749] (0)	initredirector()
> [10]:[00007FF66F4281D4] (0)	initredirector()
> [11]:[00007FF66F49EE47] (0)	initredirector()
> [12]:[00007FF66F4281E4] (0)	initredirector()
> [13]:[00007FF66F4289B3] (0)	initredirector()
> [14]:[00007FF66F51530A] (0)	initredirector()
> [15]:[00007FF66F51661A] (0)	initredirector()
> [16]:[00007FF66F51FC34] (0)	initredirector()
> [17]:[00007FF66F520387] (0)	initredirector()
> [18]:[00007FF66F4C83CD] (0)	initredirector()
> [19]:[00007FF8848C1169] (0)	DispatchMessageW()
> [20]:[00007FF8848C0C97] (0)	DispatchMessageW()
> [21]:[00007FF66F58428C] (0)	initredirector()
> [22]:[00007FF66F461C05] (0)	initredirector()
> [23]:[00007FF66F461A7E] (0)	initredirector()
> [24]:[00007FF66F461CE5] (0)	initredirector()
> [25]:[00007FF66F3F5621] (0)	initredirector()
> [26]:[00007FF66F4706DB] (0)	initredirector()
> [27]:[00007FF66F442FD8] (0)	initredirector()
> [28]:[00007FF66F63032F] (0)	initredirector()
> [29]:[00007FF886448102] (0)	BaseThreadInitThunk()
> [30]:[00007FF886A0C5B4] (0)	RtlUserThreadStart()

----------------------------------------------------------------------
再现方法：如果“查找结果”窗口找到很多结果，且每个结果的分支都有很多内容，折叠一个差不多在顶位的结果，很容易就“没了”。
“没了”的意思就是，程序自动关了，应该是出错死了。
一堆dmp的内容都是大同小异，所以就贴最后出错的那个上来。

**Comment by LiMinggang** [comment]
没有太多有用信息，有空了我试试

**Comment by ztjal** [comment]
找到100%必死的操作了。
是“鼠标左键双击关闭一个文件窗口”导致的，点“X”关闭文件窗口没问题。
再现方法：多文件查找，通过“查找结果”窗口点击展开结果，点击一条打开相应文件，这时只要通过鼠标左键双击关闭文件之后，再次点击“查找结果”窗口那条结果打开文件的话程序就死了。

**Comment by LiMinggang** [comment]
哦，明白了，行基本不用我再费力气了。看看code就能解决了。

**Comment by LiMinggang** [comment]
还真没重现出来

**Comment by ztjal** [comment]
你重现不了？要不要我录个操作视频？
不过关键我已经试好了，当只有唯一一个文件窗口时，就是“双击关闭”，和点“X”关闭，是不同，有方向的话，代码上找问题应该不难。

**Comment by LiMinggang** [comment]
是只有一个窗口的时候么？我再试试，要是能录视频最好。

**Comment by LiMinggang** [comment]
Use Alfa 2 to verify, thanks

**Comment by ztjal** [comment]
试了几下OK了，继续用日常使用来验证吧。
