### ISSUE TITLE
Bug: 不知道为什么在打"顿号"的时候会变成天蓝色

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#221]
对不起，不知道“顿号”的英文怎么说。

如下图：
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-11-2/77425688.jpg)

不知道为什么，当顿号前面和后面都是中文的时候就不会出现这个情况，但使用数字或半角字符的时候就会出现天蓝色的了。

**Comment by LiMinggang** [comment]
应该是你本地语法文件造成的问题
![image 1](https://cloud.githubusercontent.com/assets/4847132/20029599/0be80068-a38b-11e6-8f29-002b36f770d5.png)

**Comment by zhulaojianke** [comment]
现在这个MadEdit-Mod真的太好用了！特地到这里赞一个！

**Comment by zhulaojianke** [comment]
我大概找到了一些规律，当用鼠标双击某个字符（数字、括号等等）时，就会出现其他字符背景变成天蓝色的现象了。多少有一些规律。

如果是双击字符串就没有这个效应。

**Comment by zhulaojianke** [comment]
我知道了，这个是MadEdit-Mod的自带的功能，在help里有提到过。

* Highlight word(shift+F8)

实际上通过双击就可以实现这个功能哈。

这个功能可以实现全文的某一个单词高亮。

不知道这个功能能否为“搜索结果高亮显示”提供一些帮助呢？
