### ISSUE TITLE
某些字符显示不了

### ISSUE THREAD

**Issue by ztjal** [LiMinggang/madedit-mod#222]
MadEdit-Mod 0.4.5 win64 Visual Studio 2015
这个版本才有的问题，旧版没事。
例如，日文的"・"，这个常见，在日文编码下正常显示，但换成其它编码均显示"方框"。

**Comment by LiMinggang** [comment]
这个有点奇怪，0.4.5主要是修正了一些bug，还有Linux的一个比较大个改动（不影响windows版本）。文字处理和显示相关代码都没有动。
你能不能附上一个文本文件？我输入这个字符的内码0x30FB好像都能显出这个“・”，在日文下也是方框。

**Comment by ztjal** [comment]
是我搞错了，大意了，因为升级MAEDIT后，竟然重置（？）了语法的字体，以前用的是微软雅黑，改回去就没事了。
另外，那个点的UTF8十六进制为“E3 83 BB”
PS：如果可以删贴的话，删掉这贴吧。。。

**Comment by LiMinggang** [comment]
哦，那就close了，语法文件是因为压缩包里带着，所以估计给覆盖了
