### ISSUE TITLE
仍是希望将“最近打开的文件”图标放在快速查找工具栏里

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#225]
“标准”工具栏里的操作都可以用快捷键代替，将它隐藏起来可以使工具栏简洁一些。

而只有这个“最近打开的文件”需要用鼠标（从“文件”菜单里找“最近打开的文件”也挺麻烦的），这与“快速查找”工具栏的性质是一样的，如果把“最近打开的文件”图标放在“快速查找”工具栏里，在工具栏部分只保留一个工具条就可以了，也方便使用。

我觉得为了使用方便，不必太过注重图标功能在工具条中的分类。

**Comment by LiMinggang** [comment]
Need reset toolbar pos

**Comment by zhulaojianke** [comment]
您在0.4.6中把“历史文件”用F9快捷键调出了哈，嗯，同样很方便。不过现在这种复选框之后点击确认的方式操作上还是不很方便，我觉得双击打开会更好一些。

这次的regex升级真的太棒了！使整个工作流更加行云流水！太棒了。:)

**Comment by LiMinggang** [comment]
“复选框之后点击确认的方式”这个说的是啥？关闭程序时候出现的那个对话框？

2017-01-05 10:19 GMT+08:00 Zhu Xinyan <notifications@github.com>:

**Comment by zhulaojianke** [comment]
![image](https://cloud.githubusercontent.com/assets/16543111/21746558/679b4f3e-d584-11e6-874c-665761c5f40b.png)
图中的名称处，是复选框，用户在选择了复选框之后，再点击右侧的“打开”。
