### ISSUE TITLE
Hope to stay in current window when switch between modes

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#226]
不知道标题的英文是不是有毛病……大概意思如下：

MadEdit-Mod有3种编辑模式：普通文字模式、列块模式和十六进制模式，我在编辑文本的时候时常要在“普通文字模式”和“列块模式”之间切换。“列块模式”默认的不会换行，这我能理解，不反对。但每当我切换到“列块模式”之后，窗口就跳到了其他的位置——一般是文本的最后，我需要用左右键的重新定位到我刚才编辑的位置上，完成“列编辑”之后，当我切换回“普通文字模式”时，又一次跳出了我正在编辑的区域。

不知道以上的描述您能明白吗？

如果能够在我切换操作模式的时候，我的光标所在行能够始终处在我可见的窗口内，更好的时候，光标所在行不变动，这样整个工作流会更顺畅，而比不每次都用左右键去重新定位刚才编辑过的地方了。

这个功能能够得到改进么？

**Comment by LiMinggang** [comment]
没见过你说的这个情况啊？切换模式不会改变光标位置，你再确认一下

**Comment by zhulaojianke** [comment]
光标位置是不会改变，但是窗口中的文字就跳到了文本的其他位置了。

可能我描述的还不是很明白。

比如说我在编辑一个很大的文件，很长的文档，这个文档里有大量的折行显示。当我想在这个文档的某处使用“列编辑”的时候，我切换到了“列块模式”，这个时候光标仍旧停留在原位，没问题，但是窗口中显示的文档却已经调到了文档的末尾。此时我只有按方向键才能使窗口回到刚才我编辑的位置上去（或者输入一个字符）。而如果此时手贱，我用鼠标点击了一下窗口内容的话，那么我刚才正在编辑哪一行我还要返回去找。

不是光标动了，而是窗口跳到了文档的后面，不知道我这么说您能明白么？

**Comment by LiMinggang** [comment]
应该是你那个折行导致的问题，因为列编辑没法支持折行，所以修MadEdit列编辑bug的时候就加了一个切换到列编辑就自动取消折行，不然列操作就出问题了

**Comment by LiMinggang** [comment]
你可以给我个能复现这个问题的例子（把你自己文档的私有内容换成乱七八糟的文本即可），我研究下能不能修好

**Comment by zhulaojianke** [comment]
复现的例子您也可以自己做，从网络上拷贝一段小说或者新闻什么的纯文本，大篇幅的，有大段大段文字的那种，然后就可以看到在切换到列编辑模式的窗口跳动情况了。

我觉得您说的“加了一个切换到列编辑就自动取消折行”这个没问题，很好的。我是希望在取消折行或回复折行之后，光标所在行能够停留在窗口可见的区域，**能够停留在原来的光标所在行位置就更好了**。
