### ISSUE TITLE
能否将搜索面板中的“计算次数”按钮变为自动显示匹配次数呢？

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#227]
一般操作的时候想不到特意去点击“计算次数”的按钮，但如果能够及时了解到所输入的关键词或者表达式所匹配的次数，对编辑或者作者来说都是很好的参考数据呀。

**Comment by LiMinggang** [comment]
这种浪费时间，相当于每次都是全文搜索，对于大文件，负担太大
