### ISSUE TITLE
cannot open documents on the network server

### ISSUE THREAD

**Issue by Yang-47** [LiMinggang/madedit-mod#228]
直接在網路上的檔案上,按滑鼠右鍵開啟,會出現以下錯誤,
直接把檔案拖曳到madedit-mod的捷徑也會出現同樣錯誤

![error](https://cloud.githubusercontent.com/assets/26622298/24241980/72d4806c-0ff1-11e7-828e-095df3400aaa.png)

該檔案的正確路徑為 "\\mail\soft\outlook禁用winmail.dat.txt"
如果在madedit-mod開啟的狀態下,把檔案直接拖進去就可以正常打開

madedit-mod的版本為 "MadEdit-Mod0.4.6_X64.7z"

**Comment by LiMinggang** [comment]
這個網絡伺服器\\mail是什麽作業系統？windows還是linux的samba伺服器？我可能需要試試，這個沒有測試過，理論上普通的windows共享是沒有問題的。

**Comment by LiMinggang** [comment]
這個錯誤信息一般原因是路徑有問題（wxwdigets無法識別），因爲MadEdit是基於wxWidgets搭建的，文件操作都是它提供。

**Comment by Yang-47** [comment]
檔案放在 linux的samba伺服器 上

2017-03-24 11:42 GMT+08:00 Minggang Li <notifications@github.com>:

**Comment by LiMinggang** [comment]
The fix was released with 0.4.7. Please update to verify.
