### ISSUE TITLE
复制查找结果的BUG

### ISSUE THREAD

**Issue by ztjal** [LiMinggang/madedit-mod#230]
版本是：MadEdit-Mod 0.4.6 win64 Visual Studio 2015 build 08:05:26 Dec 30 2016
==========================
在当前文本“查找全部”之后，在“查找结果”框列出来的结果的主分支，如：“查找“XXX”（在一个文件中匹配 XXX 次）”，对其右键，选“复制全部”，然后粘贴出来的文本少了第一行（数组0？）。

**Comment by LiMinggang** [comment]
呃，这个今天刚刚修好 d9017d61b7f7b5983355f0f8b6791630ec1f6a68

**Comment by ztjal** [comment]
当然要，修了BUG的版本当然要用。

**Comment by LiMinggang** [comment]
https://sourceforge.net/projects/madedit-mod/upload/Preview/
