### ISSUE TITLE
Caret is not correctly drawed(0.4.7)

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/madedit-mod#231]

**Comment by LiMinggang** [comment]
The caret does not change after toggling it by hit Insert key

**Comment by zhulaojianke** [comment]
有段时间没来哈，来问个好 :) 
一直在用MadEdit-Mod，非常好用，非常喜欢！用txt文件格式写东西心里没有压力，而且快捷键编辑无障碍，批量编辑效率很高，可以舒畅的发挥思想。谢谢您努力维护它！ :)

**Comment by LiMinggang** [comment]
:)
