### ISSUE TITLE
A wrong string in the "insertline.mpy"  

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#232]
在insertline.mpy中有一句：
newline = "1111111111111111111111111111111111111111111112"
这使得用户插入的是重复这个字符串，
我给改成：
newline = '\r\n'
看来是可以了。

**Comment by LiMinggang** [comment]
这个是你自己弄出来的，你看看网站代码里面的这个文件

**Comment by LiMinggang** [comment]
Reopen the issue for others found the same one.

**Comment by zhulaojianke** [comment]
是，您考虑了不同的操作系统 :)

**Comment by LiMinggang** [comment]
额，那个不是操作系统，是操作系统对文本文件行结束的定义，举例来说，你把Linux，或者Mac下的文本文件拷贝到windows上，你就看出区别了。很简单的例子就是浏览网站，多数网站都是Linux搭建的。
