### ISSUE TITLE
一个性能上的问题

### ISSUE THREAD

**Issue by ztjal** [LiMinggang/madedit-mod#233]
MadEdit-Mod 0.4.8 win64 Visual Studio 2015 build 15:00:11 May 31 2017
-------------------------------------------------------------------------------------
多文件查找，在结果里列出的行，如果某行的内容很长（550+）且有特殊字符（不确定）时，鼠标移过去时的预览会极其慢且占CPU。
加个选项可以关掉这个预览吧。

**Comment by LiMinggang** [comment]
我需要看看代码

**Comment by LiMinggang** [comment]
预览是因为该行过长，超过了屏幕宽度才出现的。查了下手册，预览（实际是tooltip）那个是不能禁止的，可以设置的只能是显示长度，这样性能会提高

**Comment by ztjal** [comment]
嗯。。。tooltip这东西默认应该是关闭的吧，至少我用过的VC和.NET都要写几行才可以出会弹出tooltip这东西。。。
好吧，先不管能不能关了，那长度设置为0的话，试下还会不会显示？

**Comment by LiMinggang** [comment]
你可以试试搜索短行，tooltip就不出现了。0是不行的，因为你看不到任何东西，我说的那个行是显示的文自，这个可以设置的，目前我是最大显示1024个字符
