### ISSUE TITLE
崩溃bug

### ISSUE THREAD

**Issue by zhtw2013** [LiMinggang/madedit-mod#235]
昨天发现的，疑似是崩溃Bug

点到设置，然后选择「源文件格式化工具」的页签
之后点关闭按钮，Madedit-mod就崩溃了
实测设置中只有「源文件格式化工具」的页签做这个操作会崩溃

测试系统为Win10 x64与Win7 x64 虚拟机
两个虚拟机测试都有发现崩溃的情况。

有演示gif
![madedit-mod](https://user-images.githubusercontent.com/9501406/29347839-08c99e60-8282-11e7-8304-767b23c485df.gif)

**Comment by LiMinggang** [comment]
这个已经修复了

**Comment by LiMinggang** [comment]
Will redesign source formator config tab

**Comment by LiMinggang** [comment]
修好了，但是造成了翻译有点小问题要调整一下，等下周有空联系你，多谢！
