### ISSUE TITLE
建议在标签右键菜单里加一个“打开文件所在目录”

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#243]
有的时候打开文件多了，就忘了哪个文件是来自于哪个目录了，我看到是有一个“拷贝文件所在目录”，但我感觉“打开文件所在目录”更直接更方便一些。

**Comment by LiMinggang** [comment]
不是同一个功能，原来那个“拷贝文件所在目录”是为了拷贝字符串，不一定是为了打开这个目录，我一般都是用total commander
