### ISSUE TITLE
TXT syntax would not be applied on first loading(0.4.10)

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#244]
我修改了syntax_txt.syn，定制了一些语法显示，在前几个版本用起来很满意。升级到0.4.10版之后，打开txt文件发现自己定制的语法显示都没有了，而我并没有替换我定制的语法文件。

我尝试新建一个txt文件，语法显示没问题，存盘之后也没问题，但是当我关闭文件之后再打开，发现同样的问题，就是语法显示没有了。

希望您能够检查修改这个bug。

**Comment by zhulaojianke** [comment]
演示一下这个Bug：
　　我将txt文件的语法显示修改为：中文文本显示成灰色，英文文本显示成黑色加粗。
　　当我新建一个txt文件时：

**Comment by zhulaojianke** [comment]
我演示一下这个bug：
　　我把txt文件的语法显示修改为：中文文本为灰色，英文文本为黑色加粗。
　　当我新建一个文件时：
　　![](http://7xo4ig.com1.z0.glb.clouddn.com/17-10-23/51155398.jpg)
　　当我将这个文件保存时：
　　![](http://7xo4ig.com1.z0.glb.clouddn.com/17-10-23/33566937.jpg)
　　我当关闭再打开，或者按ctrl + r重新加载该文件时：
　　![](http://7xo4ig.com1.z0.glb.clouddn.com/17-10-23/9941426.jpg)

**Comment by zhulaojianke** [comment]
就像上面这样，我设置的语法显示都没有了！

**Comment by zhulaojianke** [comment]
找到您的这个bug出现问题的地方了！

在“syntax”文件夹里有一个“extension.list”，里面漏掉了对syntax_txt.syn文件的扩展名注解，我给加上了，然后就没问题了。

不过还是希望您能够在0.4.11这个版本里把这个错误修改过来哈！

**Comment by zhulaojianke** [comment]
用我这个方法存在一个问题，就是原来无扩展名的文件默认为是txt文件， 打开后可以套用txt文件的语法格式，但是现在不可以了。

**Comment by LiMinggang** [comment]
没搞明白你的问题，估计是重新加载文件的处理的问题

**Comment by zhulaojianke** [comment]
您的“extension.list”文件里缺少对syntax_txt.syn文件的扩展名关联，导致了我上面说的这个bug。

**Comment by zhulaojianke** [comment]
不是文件编码、字体的问题。
您可能忘了我对txt文件的语法文件做了自定义，所以我才发现这个bug的。

**Comment by LiMinggang** [comment]
不是这个问题，“最原始的MadEdit也没有在extentionlist里面加入txt”
不过我确实发现一个我问题，你需要切到别的语法，再切回去，好像就正常了。

**Comment by zhulaojianke** [comment]
不必切换，直接在“查看”菜单的“语法类型”中选择“纯文本”也可以正常的，但是重新加载或者关闭后再打开，仍旧失效了。 :(

**Comment by LiMinggang** [comment]
对，“查看”菜单的“语法类型”中选择“纯文本”跟你用那个下拉框再选一次一样，你先用ext的方法解决吧，需要研究一下问题所在

**Comment by zhulaojianke** [comment]
嗯，好的。我想尝试在extension.list里定义无扩展名的文件，您知道怎么写么？

**Comment by LiMinggang** [comment]
好像没啥好办法，不行你就回退到0.4.9----如果你不常用书签编辑，删除，剪切书签的话，然后等我出下一个版本的preview

**Comment by zhulaojianke** [comment]
啊，您别生气……我已经接受0.4.10的书签了，挺好使的。

**Comment by LiMinggang** [comment]
知道问题所在了，你把界面设为英文就应该可以了

**Comment by LiMinggang** [comment]
Will provide a preview build for this issue, please verify.

**Comment by zhulaojianke** [comment]
win64

**Comment by LiMinggang** [comment]
It's in Preview directory

**Comment by zhulaojianke** [comment]
没问题了！效果很好哈！

**Comment by zhulaojianke** [comment]
这个preview版没问题了！又变得非常好用了哈！

**Comment by zhulaojianke** [comment]
我工作中使用的专业软件经常会碰到将普通的txt文件修改了一个扩展名就当做其处理的专用文件的情况，此时就特别需要有这个对所有文本文件都可以按统一的语法格式显示的功能了（对那么多奇奇怪怪的扩展名文件修改ext太麻烦了！）。您在修好这个bug推出这个preview版本之前的一段时间，我确实挺焦急的。现在preview版之后，舒服多了。:)

**Comment by LiMinggang** [comment]
这个bug其实没那么严重，改一下翻译文件或者选择英文作为界面语言就好，所以没着急推出修复版本
