### ISSUE TITLE
window space issues

### ISSUE THREAD

**Issue by nikoss** [LiMinggang/madedit-mod#249]
**Please provide the following information**

Madedit-Mod version (or branch):  
madedit-mod-0.4.10-1.x86_64_Mageia6.rpm, Greek language

platform/architecture: 
Mageia 6, Linux 64bit 

Two space issues in the Options dialog window.

![madedit_window_spacing_001](https://user-images.githubusercontent.com/4921343/32700264-3f2a3ce2-c7cb-11e7-91fe-5655ba80d0bf.jpg)

In this case, clicking on the drop-down menu works right. 
But when in "rest" it doesn't show right.
![madedit_window_spacing_002](https://user-images.githubusercontent.com/4921343/32700265-3f57808a-c7cb-11e7-9092-2c39cfae06a2.jpg)

**Comment by LiMinggang** [comment]
Will provide a preview for you which includes fixes for this issue and the "Plain Text issue"
