### ISSUE TITLE
Bug about 0.4.11

### ISSUE THREAD

**Issue by kesdoputr** [LiMinggang/madedit-mod#252]
Hello,i'm using newest 0.4.11 win32 on windows 7,and i found a bug that:

When i uncheck **Reload files previously open on startup**,i will get a setting **ReloadFiles=0**
in the **[Application]** section(new section in 0.4.11) but it's not work and madedit still open
the files previously opened. But if i put ReloadFiles=0 to [MadEdit] section (version before 0.4.11)
then it works.

So i have next try,i modify setting like below:

[Application]
ReloadFiles=1
[MadEdit]
ReloadFiles=0

And it still work like ReloadFiles=0,it seems that the ReloadFiles setting in [Application] sections doesn't be detected.

**Comment by LiMinggang** [comment]
Confirmed

**Comment by LiMinggang** [comment]
Will repack all files to release 0.4.11
