### ISSUE TITLE
Malware report by SF

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/madedit-mod#253]
**Please provide the following information**

Madedit-Mod version (or branch):
0.4.11
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

MadEdit-Mod0.4.11_X64.7z is reported by SF with bad archive.
![image](https://user-images.githubusercontent.com/4847132/34192997-5882d170-e58c-11e7-87f2-c23ac9ff225a.png)

No idea about the problem. MD5 is the same as my local one(F7F51ACF722697A94516731D0D37B253) and 7zip verified OK.

**Comment by zhtw2013** [comment]
好像只有x64有提醒..
https://imgur.com/nuANlTd.png

**Comment by LiMinggang** [comment]
中国这边因为有长城的原因，一直比较慢----因为sf用了一些google和fb的东西

**Comment by zhtw2013** [comment]
我在臺灣，這裡沒有長城也是很慢的阿...
