### ISSUE TITLE
Need Detailed Instructions to build madedit-mod on CentOS 7 Linux

### ISSUE THREAD

**Issue by Rock999Cogar** [LiMinggang/madedit-mod#255]
**Please provide the following information**

Madedit-Mod version (or branch):
MadEdit-Mod 0.4.10.tar.gz

platform/architecture:
Intel i5 (64 bit) CPU running 64 bit CentOS Linux 7 (same as Red Hat 7 and Oracle Linux 7)
compiler and compiler version: (using gcc)

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

Trying to build madedit-mod on CentOS 7 Linux, which is quite old in regards to the c++ runtime libraries compared to current Linux such as Fedora 27, OpenSUSE 42.3 and Debian 9 that I usually use.  To run a madedit executable from a modern Linux on CentOS 7,  looks like this:

madedit
/home/Rcogar/bin/madedit-mod/madedit: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/Rcogar/bin/madedit-mod/madedit)
/home/Rcogar/bin/madedit-mod/madedit: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/Rcogar/bin/madedit-mod/madedit)

So I need to compile it on CentOS 7.  It's quite a challenge.

I am using 

https://sourceforge.net/p/madedit-mod/wiki/How%20to%20compile%20MadEdit-Mod%20under%20Linux/

and there is not enough detail to get past this:

checking for wxWidgets version >= 2.8.0 (--static)... no
configure: error: 
    The requested wxWidgets build couldn't be found.
    
    The configuration you asked for madedit-mod requires a wxWidgets
    build with the following settings:
        --static
    but such build is not available.

    To see the wxWidgets builds available on this system, please use
    'wx-config --list' command. To use the default build, returned by
    'wx-config --selected-config', use the options with their 'auto'
    default values.

    If you still get this error, then check that 'wx-config' is
    in path, the directory where wxWidgets libraries are installed
    (returned by 'wx-config --libs' command) is in LD_LIBRARY_PATH
    or equivalent variable and wxWidgets version is 2.8.0 or above.

and that is after successfully doing a static build of wxWidgets 3.1.0.

I have also learned that Static build of boost_python is yet another challenge

and finally,  when I can (almost never) get past boost and wxwidgets,  I get compile errors due to location of header file unordered_map.hpp.

I cannot get past that.

Thanks!

**Comment by LiMinggang** [comment]
If you were going to build a binary of MadEdit-Mod, you have to install wxWidgets-dev or compile the wxWdigets 3.1 from source code, which is pretty simple.

1. Download the source package from wxWidgets (https://github.com/wxWidgets/wxWidgets/releases)
2. Un-tar the package
3. Use the instruction in README.txt of MadEdit-Mod, i.e. if met PIC problem, you have to add -fPIC as below.
wxWidgets(3.1.0) (CXXFLAGS=-fPIC CPPFLAGS=-fPIC CFLAGS=-fPIC, x64)
./configure --enable-unicode --disable-shared --with-libpng=builtin --with-zlib=builtin --with-expat=builtin --with-gtk=2 --with-libiconv=no
4. Download boost 1.65/1.66 and untar
5. build MadEdit-Mod

a) binary only
./configure --with-boost=${HOME}/boost_1_65_0 --with-wxdir=${HOME}/wxWidgets-3.1.0
b) rpm
cd ./package/rpm and run sh ./makerpm.sh

**Comment by LiMinggang** [comment]
Boost and wxWidgets are must but don't need to build any boost libs

**Comment by LiMinggang** [comment]
Any error message, post it here.

**Comment by LiMinggang** [comment]
For the boost_python stuff, don't worry. I've embedded it in MadEdit-Mod package. Don't need to build any boost code.

BTW, you should use 0.4.11 which fixed bugs found in 0.4.10

**Comment by Rock999Cogar** [comment]
Hi,
0.4.11 sound good, but I could not find the source code for 0.4.11 at 

(https://sourceforge.net/projects/madedit-mod/files/0.4.11/)

(latest source on sourceforge is 0.4.10)

Is there another link ?

ThanksRock.

    On Wednesday, January 17, 2018, 2:29:05 AM MST, Minggang Li <notifications@github.com> wrote:  
 
 
For the boost_python stuff, don't worry. I've embedded it in MadEdit-Mod package. Don't need to build any boost code.

BTW, you should use 0.4.11 which fixed bugs found in 0.4.10

**Comment by LiMinggang** [comment]
https://github.com/LiMinggang/madedit-mod/releases

**Comment by Rock999Cogar** [comment]
Thanks!
    On Wednesday, January 17, 2018, 5:20:50 PM MST, Minggang Li <notifications@github.com> wrote:  
 
 
https://github.com/LiMinggang/madedit-mod/releases
