### ISSUE TITLE
High CPU consumption while moving mouse pointer under Windows.

### ISSUE THREAD

**Issue by hellojianqun** [LiMinggang/madedit-mod#258]
Version 0.4.11 x64 & x86

在Windows上，在文本区域中移动鼠标指针时，鼠标指针形状在箭头与编辑符号之间快速闪烁，同时CPU占用很高，会跑满一个CPU线程（我的4线程CPU占用率会达到25%）.

在64位的Windows 10和Windows 7上都试过，都有这样的问题.

谢谢您的付出，提前祝新年快乐！

**Comment by LiMinggang** [comment]
这个没遇到过，感觉是你系统的问题，是不是有装什么会监视鼠标或者类似截图的软件？鼠标变成指针感觉像是有进程切换，你能贴出你任务管理器的截屏不？按CPU占用率从大到小排序。
我快速移动鼠标确实能看到指针，但是没有发现CPU占用率异常。不移动的时候，CPU占用0.01，移动的时候大约是不到2%

**Comment by LiMinggang** [comment]
从来没遇到过，我这里中英文64位win7都很正常，无论是32还是64位的madedit-mod。一直也没有其他人提过类似问题。
查了一下代码，里面鼠标移动的处理里面只有切换鼠标的图标的操作，这个是系统提供的功能，没有什么可以检查的。确认是你系统的问题。
你如果能看懂C++的话，你看一下MadEdit::OnMouseMotion

**Comment by LiMinggang** [comment]
merge to #258

**Comment by LiMinggang** [comment]
汗呐。其实是另外一个同样的问题报告引起了我的注意，他发现了MadEdit-Mod与MadEdit 0.2.9代码上的一点不同，我研究了一下，发现确实有点区别。然后还需要验证是否真的修复了。

你还能复现这个问题吗？如果可以，我可以放一个编译的版本给你验证，否则还只是理论上认为修复了。
如果你愿意，告诉我你需要那个编译版本，x86还是64

**Comment by hellojianqun** [comment]
正有此意 :) 我想要x64的版本.

**Comment by LiMinggang** [comment]
Win7 X64，在sourceforge的preview目录
