### ISSUE TITLE
Window height increases with every start

### ISSUE THREAD

**Issue by BzfpWg9g** [LiMinggang/madedit-mod#259]
MadEdit-Mod 0.4.11 x86_x64 GCC 5.3.1 20160413 build 07:10:01 Dec 19 2017
Linux 64bit / Lubuntu 16.04 / Openbox

- Windows height gets bigger every time I start Madedit Mod till height is maximum y. 
- Tried with old Version 4.0 if problem exists. Same here.
- No success defining size in lubuntu-rc.xml
- Temporary fix for me: Using gDevilspie to define window size.

**Comment by LiMinggang** [comment]
Did not observe the issue on Ubuntu. Would you please paste a screenshot so that I have some basic idea about the windows theme you used? I've little about Lubuntu.

**Comment by LiMinggang** [comment]
Everything looks OK.
![image](https://user-images.githubusercontent.com/4847132/36081756-214ed3f8-0fde-11e8-996f-7e4f7045cc54.png)

**Comment by BzfpWg9g** [comment]
Tried to reproduce issue with a nearly identical system. No problems there. Maybe first OS is misconfigured. Issue can be closed. Really appreciate your help.
