### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by svnpenn** [LiMinggang/madedit-mod#264]
please and thank you

**Comment by LiMinggang** [comment]
What's the issue?

**Comment by svnpenn** [comment]
need EXE

**Comment by LiMinggang** [comment]
Sorry, I don't understand. There are different windows builds for x86 or x64 in the download directory. What are you asking for? Did you try to click the download icon?

**Comment by svnpenn** [comment]
oh i see them:

http://sourceforge.net/projects/madedit-mod

why cant downloads just be hosted at github?

http://github.com/LiMinggang/madedit-mod/releases

**Comment by LiMinggang** [comment]
I did not figure out the way to add files to github easily. It seemed that the files have to be added manually one by one and I can't see the download statistics to figure out if none cares about my release and it should be a dead release.
