### ISSUE TITLE
Version 0.4.13 x64 looks as if using a dark theme on Windows

### ISSUE THREAD

**Issue by hellojianqun** [LiMinggang/madedit-mod#268]
**Please provide the following information**

Madedit-Mod version (or branch):
MadEdit-Mod0.4.13_X64.7z

platform/architecture:
Windows 7, Windows 10 (x64)

compiler and compiler version:
**

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

MadEdit-Mod0.4.13_X64.7z解压出来的版本是类似一种“黑暗主题”的，如下图所示：

![2018-06-04_115941](https://user-images.githubusercontent.com/35357331/40902071-38172ef8-6805-11e8-8924-13552359219f.png)

而x86版本以及Ubuntu版本则仍然是原来的"白色主题".

**Comment by LiMinggang** [comment]
因为资源有限，没有做独立的发布环境，所以我自己使用的环境就做了发布环境，一不小心就引入了我自己的配置。冏
主题因为wxwidgets有些问题，所以不太完美，工具条不能改背景色，但可以隐藏工具条的
