### ISSUE TITLE
reopen: MadEdit not responding when open .java file

### ISSUE THREAD

**Issue by ooab** [LiMinggang/madedit-mod#270]
**Please provide the following information**

Madedit-Mod version (or branch):0.4.12, 0.4.13

platform/architecture:windows7 64bit

compiler and compiler version: vs2015

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

same as #267

**Comment by LiMinggang** [comment]
Is it possible to share the java file you used to reproduce the issue? I used to met the issue by opening HTML file and don not see it for a long time.
