### ISSUE TITLE
The activelinemark is too thick in V0.4.15

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#276]
**Please provide the following information**

Madedit-Mod version (or branch): 0.4.15

platform/architecture: win7

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

之前的版本，如0.4.14，活动行的框线很窄，效果很不错。现在变粗了，尽管很醒目，但遮盖了字符的一些部分，不方便阅读了。

**Comment by LiMinggang** [comment]
Let me add a config item for this
