### ISSUE TITLE
Annoying and time consuming warning message.

### ISSUE THREAD

**Issue by nikoss** [LiMinggang/madedit-mod#280]
**Please provide the following information**

Madedit-Mod version (or branch):
MadEdit-Mod 0.4.15 x86_x64 GCC 5.4.0 build 05:56:04 Nov 30 2018

platform/architecture:
Mageia Linux 6, 64bit

How to reproduce:
* open a document with madedit
* make a change
* save the document
* press Ctrl+Z to undo the changes
* a pop up warning message will tell you that you are about to undo a change in the saved document

When you do a lot of trial and error,
and have to undo and redo changes many times,
this message not only irritates the user,
but consumes a lot of time.
To the point where I had to use another text editor!

Is there a way to prevent this message from popping up?
I didn't see any option.
Maybe, an option should be provided at Madedit-mod's preferences.

**Comment by LiMinggang** [comment]
Yeah, that's the way it works because your cannot redo the one if you did an undo and currently it could not be disabled.

Will add an option in preference for this

**Comment by LiMinggang** [comment]
Did you want a patched one? I can simply disable the dialog in the code.

**Comment by LiMinggang** [comment]
https://sourceforge.net/projects/madedit-mod/files/Preview/

**Comment by nikoss** [comment]
I downloaded and tested it...
> MadEdit-Mod 0.4.16 x86_x64 GCC 5.4.0 build 21:27:42 Feb 11 2019

This problem is fixed.
I didn't see any other issue, so far.
Thanks!

**Comment by LiMinggang** [comment]
This is not a fix but a patch. I only commented out the code. I'm going to add a checkbox to toggle the code in preference dialog.
