### ISSUE TITLE
录制宏时涉及编码的几处问题

### ISSUE THREAD

**Issue by findpkq** [LiMinggang/madedit-mod#286]
例如
me.SetEncoding('GBK')
me.ConvertEncoding('SHIFT-JIS', 5)

默认录制情况下，录下的宏是
me.SetEncoding(GBK)
me.ConvertEncoding(SHIFT-JIS, 5)

没有引号，所以之后运行失败。然后报错信息我是回到老版本才看见来着

也不确定这是不是和系统python环境有关，总之先试着报一下吧 :)

Best regards~

**Comment by LiMinggang** [comment]
我以为只有我自己在用宏的功能。:-P
这个的确是bug，之前没有录过编码转换的，没测到。
