### ISSUE TITLE
linux版本完全没法正则搜索，当然也不能够正则替换啊

### ISSUE THREAD

**Issue by harvey-git** [LiMinggang/madedit-mod#288]
Madedit-Mod version (or branch):
 0.4.16  
platform/architecture:
Ubuntu.18.04/x86_x64
compiler and compiler version:
GCC 7.3.0 build 09:07:40 Apr  8 2019
please describe what symptom you see, what you would expect to see instead and how to reproduce it.
![madedit-regexif](https://user-images.githubusercontent.com/52305566/60327775-5677b600-99bf-11e9-836d-e2e08ce6604c.png)

我尝试了自行从源代码编译，然而，./configure 提示glib2.0需要大约2.6版本，然而ubuntu18.04自带的glib2.0是2.56，于是我转而尝试去自行编译glib2.0 2.6，结果缺乏更多的依赖包，这么跌跌撞撞得一周过去了……我终于放弃了，还是向几位大佬求助可能更有效率。
补充一下，因为工作原因，我的主环境切换到了Linux操作系统，在赢下我比较了大量的编辑器，最后发觉也就madedit和EmEditor最符合我的使用习惯，然而当编写大量文字时，EmEditor中的大纲插件能帮我省下不少时间，这使得EmEditor中最终在win下成为了我的主编辑器（madedit在编写修改超大文本时仍旧比EmEditor中更有优势），其他情况下我会用madedit。
我对madedit最干兴趣的地方其实是宏。我以前自行编写了大量emeditor下的宏脚本，如今主要环境转到ubuntu下后，我发觉也就只有madedit最符合我的使用习惯了，如果madedit解决了正则搜索替换再带上个大纲功能，对我来说就完美了！

**Comment by harvey-git** [comment]
补充一下，因为工作原因，我的主环境切换到了linux，在win下我比较了大量的编辑器，最后发觉也就madedit和emeditor的宏编写符合我使用习惯，然而当编写大量文字时，emeditor的大纲插件能帮我省下不少时间，这使得emeditor最终在win下成为了我的主编辑器（madedit在编写修改超大文本时仍旧比emeditor更有优势），其他情况下我会用madedit。

**Comment by LiMinggang** [comment]
等我确认。理论上应该跟平台无关，MadEdit的正则是用boost实现的，而且是不需要编译的boost库

**Comment by LiMinggang** [comment]
确认，等下个版本修复。

**Comment by harvey-git** [comment]
感谢大佬。

**Comment by LiMinggang** [comment]
这个bug仅限于不区分大小写，你先选上区分大小写先使用着

**Comment by harvey-git** [comment]
果然勾上不区分大小写可以用了，这个bug有点意思啊，哈哈哈。

**Comment by harvey-git** [comment]
发现了新bug，madpython如果编码跟操作的文件编码不同，会使得宏运行处理出来的文件乱码，举个例子：madpython是utf8编码的，待处理文件是gb18030的，如果宏里面待搜索替换的内容是中文（比如(第[^章]{1,3}章)），最后宏运行完了出来被替换内容就变成了乱码内容了！

**Comment by harvey-git** [comment]
又发现一个bug，如果保存的madpython脚本跟要操作的文件使用不同编码（比如脚本为utf-8，操作文件为gb18030），则如果脚本里有查找替换操作，脚本运作后最终出来的文件就会乱码。

**Comment by LiMinggang** [comment]
后面这个问题没法重现，你需要给我例子，最好具体的文件+madpython脚本，还有步骤。我试着把脚本编码改成UTF8去替换中文字符，没有任何问题。

**Comment by elsuyazzie** [comment]
以下是测试时的文本：
`测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是
测试第一章还是测试测试还是测试测试还是测试测试还是测试测试还是测试
测试还是测第一章试测试还是测试测试还是测试测试还是测试测试还是测试
测试还第一章是测试
测试还是测试ｖ测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试
ｖｖ什么弥勒佛　浪费了感冒了ｖ＇ｍrdf;l
测试还是测试测试还是测试测试还是测试测试还是测试
rjoj  测试还是测试测试还是测试测试还是测试测试还是测试`
[testmpy.txt](https://github.com/LiMinggang/madedit-mod/files/3346210/testmpy.txt)
以下是出问题时的mpy：
`medit = MadEdit()
medit.DeleteEmptyLines()
medit.DeleteEmptyLinesWithSpaces()
medit.ReplaceTextAll("(第[^章]{1,3}章)(.+)", "\n## 【\1、\2】", True, True, False, False, -1)
medit.ReplaceTextAll("(第[^章]{1,3}章)", "\n## 【\1】", True, True, False, False, -1)`
[小说格式化.zip](https://github.com/LiMinggang/madedit-mod/files/3346214/default.zip)
以下时上面的宏代码在测试文本中运行后的乱码：

![宏运行出来的乱码](https://user-images.githubusercontent.com/50239479/60446936-f7cb6a00-9c54-11e9-89fe-3fc746d188e4.png)

**Comment by LiMinggang** [comment]
\1和\2看着是对的啊，linux上显示的是内码图片。你需要把那俩'\'去掉。以下是去掉后的结果
测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试测试还是
测试
## 【1、2】
测试还是测
## 【1、2】
测试还
## 【1、2】
测试还是测试ｖ测试还是测试测试还是测试测试还是测试测试还是测试测试还是测试
ｖｖ什么弥勒佛　浪费了感冒了ｖ＇ｍrdf;l
测试还是测试测试还是测试测试还是测试测试还是测试
rjoj  测试还是测试测试还是测试测试还是测试测试还是测试

**Comment by harvey-git** [comment]
我又测试了，发现在mpy里面有正则替换必出现乱码，比如下面这样的代码：
`medit.ReplaceTextAll("([^。… “”])(\s*\n)", "\1", True, True, False, False, -1)`
我的本意是将被限制了指定字符长度后就换行的中文合并成正常的连续段落，然而，上面的正则内容在查找替换对话框运行是正常的，在mpy里替换的出来就必定成了乱码。
诡异的是如果mpy的内容只是普通替换不牵涉正则搜索替换就没有问题。

**Comment by harvey-git** [comment]
继续汇报bug，刚刚发现当我在一个utf8编码的文件里复制内容放到搜索对话框的搜索栏里，然后切换到一个不同编码（比如gb18030）的的文件标签时，搜索栏在得到焦点时搜索框里的文字乱码了！反之亦然。换句话说，搜索框里的内容编码不随当前文档切换自动更新而是保留原始复制时的编码。

**Comment by LiMinggang** [comment]
看来你对正则表达式理解的不太正确，这玩意每种实现都有差异，你要是用MadEdit的，需要研究这个：Boost.Xpressive
https://www.boost.org/doc/libs/master/doc/html/xpressive/user_s_guide.html#boost_xpressive.user_s_guide.installing_xpressive

\s那个应该是实现差异，不是bug

**Comment by LiMinggang** [comment]
搜索栏我是做过改进，就是根据当前文件内码来显示

**Comment by harvey-git** [comment]
不好意思，我上面的表述有误，我的mpy核心内容是这一句：
`medit.ReplaceTextAll("(第[^章]{1,3}章)(.+)", "\n## 【\1、\2】", True, True, False, False, -1)`
将类似 “第一章大大大”这样的内容替换为“## 【第一章、大大大】”而不是想把它们替换成“【1、2】”这样。

**Comment by LiMinggang** [comment]
你应该用$1、$2，这个语法是The ECMA-262 Format Sequences，然后你参考boost的讲解

**Comment by harvey-git** [comment]
> 你应该用$ 1，$ 2，这个语法是ECMA-262格式序列，然后你参考boost的讲解
谢谢，有效了，请问哪里有mpy的详细api文档？比如
`medit.ReplaceTextAll("(第[^章]{1,3}章)(.+)", "\n## 【\1、\2】", True, True, False, False, -1)`
这段里True, True, False, False, -1)这几句分别代表啥意思？（我通过测试知道第一个true是值开启正则，第二个是指大小写敏感……最后的-1指全文搜索），我的本意是需要在mpy里执行搜索选取，然后在选区里进行搜索替换的操作。所以我希望能查阅到更详细的medit.xxxxxxx这类的函数的列表。
此外一个很尴尬的地方在于，我没法在搜索框里搜索替换“"”加上“\”也不行，能再麻烦下大佬么？

**Comment by LiMinggang** [comment]
函数列表在 help/MadPython.txt里面，没有太详细的说明。你可以用“先录制然后修改”这种办法

**Comment by LiMinggang** [comment]
“没法在搜索框里搜索替换“"”加上“\”也不行”
没太明白，你举个例子，给出原来的字符串，然后你想怎么替换

**Comment by elsuyazzie** [comment]
> “没法在搜索框里搜索替换““”加上‘\’也不行” 
> 没太明白，你举个例子，给出原来的字符串，然后你想怎么替换
举个例子，我在整理某些文档时，发现这些文档虽然是中文的，然而里面的引号确实英文的比如
`"你好吗？"`
我希望捕获成对的英文的“"”，然后分别替换成“和”，然而我发现在无论在搜索框还是已经录制好的mpy里面，我不知道如何转义英文的“"”。自然也就没法搜索替换“"”到我需要的内容了。
不好意思，给您添麻烦了！

**Comment by LiMinggang** [comment]
哦，这个我经常做啊。你要是用正则替换，是需要加"\\" ，如果是普通文本替换，是不需要的。

**Comment by elsuyazzie** [comment]
> 哦，这个我经常做啊。你要是用正则替换，是需要加"\" ，如果是普通文本替换，是不需要的。

问题的关键就在这里，我加了“\”转义成为
`\"`
，然而在搜索框里搜索匹配不到任何内容。

**Comment by elsuyazzie** [comment]
我是这样匹配的：正则搜索`(\")([^\"]+)(\")`
替换成`“\2”`

**Comment by LiMinggang** [comment]
我试试

**Comment by LiMinggang** [comment]
我这里执行正常（Windows 7）
"wojewo"
"我们"
变成了
“wojewo”
“我们”

**Comment by elsuyazzie** [comment]
> 我这里执行正常（Windows 7）
> "wojewo"
> "我们"
> 变成了
> “wojewo”
> “我们”

win下的确正常（当初在win下的时候madedit本来就是我的第二编辑器），我报的故障全是在linux下的啊。

**Comment by LiMinggang** [comment]
那你得等了，我好像在linux的虚拟机下没法输入中文，我一直没有装输入法。都是虚拟机

**Comment by LiMinggang** [comment]
你再开一个新的问题吧

**Comment by LiMinggang** [comment]
在ubuntu 18.04.2下测试正常，有没有我的修改都是正常替换
