### ISSUE TITLE
希望能支援 在搜尋時 無視簡日漢字

### ISSUE THREAD

**Issue by bluelovers** [LiMinggang/madedit-mod#291]
希望能支援 在搜尋時 無視簡日漢字

例如像這個一樣 https://demonovel.netlify.com
![image](https://user-images.githubusercontent.com/167966/60845548-40fc5a80-a20f-11e9-88fa-23049f07ce76.png)

可以在搜尋框內打上任何漢字 然後會自動配對簡繁日漢字

例如搜尋 `無視簡日漢字`
就會變成 `/[无無][眎視视視][简簡]日[汉漢]字/u`

**Comment by LiMinggang** [comment]
这像是查表出来的

**Comment by bluelovers** [comment]
資料說明是指什麼意思?

是指?
https://github.com/bluelovers/regexp-cjk
https://github.com/bluelovers/cjk-convert

https://github.com/bluelovers/cjk-convert/blob/master/lib/jp/table.ts
https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/table/table.ts


這個要實現的話 難度應該只有 是否要支援 能對 regex 作處理而以
因為 madedit 本身就有 簡繁日轉換的對照表

在不考慮支援 regex 的情況下的話 大概就是分割 找出所有漢字 然後查表之後 製作成 regex 這種比較傻一點的方式

要 支援解析 regex 的話就比較麻煩 還得去找相關的庫 來使用避免解析錯誤

**Comment by LiMinggang** [comment]
我看你给出的例子支持正则的方式就是分割查表啊，换掉正则支持的库有点难

**Comment by bluelovers** [comment]
恩 要能支援解讀 regex 來自動將裡面的漢字換掉比較難 
還不一定能保證找到的庫是能完美支援解析的

但如果是在純文字搜尋這點上的話 就比較簡單實現 只需要注意 escape 就可以了
只要在搜尋時 內部轉換成 regex 就可以

**Comment by LiMinggang** [comment]
能说说这个的主要应用场景（user scenario）吗？

**Comment by bluelovers** [comment]
在繁簡混雜的環境下 要搜尋字詞比較方便
