### ISSUE TITLE
0.4.17的linux版出现了界面上的性能问题

### ISSUE THREAD

**Issue by harvey-git** [LiMinggang/madedit-mod#294]
Madedit-Mod version (or branch):
MadEdit-Mod 0.4.17
platform/architecture:
Ubuntu 19.04/x86_x64
compiler and compiler version:
 x86_x64 GCC 7.3.0 wxWidgets 3.0.4 build 13:27:40 Jul 20 2019
please describe what symptom you see, what you would expect to see instead and how to reproduce it.
**Please provide the following information**
具体表现在界面拖动滚动条（或者用滚轮翻页）时，madedit-mod出现了卡顿，完全没有以前的顺滑流畅，更严重的是用鼠标拖动选定文本时，松开鼠标移动鼠标，选区仍旧会跟着鼠标变化。

**Comment by LiMinggang** [comment]
这个版本对Linux唯一大的变化就是放弃了静态编译的wxWidgets换成用系统自带的wxGTK包。

**Comment by harvey-git** [comment]
神奇，刚刚将linux内核升级到了5.2.3（之前时5.1.6），界面的性能问题明显减轻（甚至可以说感知不到了）卡顿和拖动的跟手感跟之前的0.4.16区别已经不大，当然了跟win版 还是很有差距的。

**Comment by LiMinggang** [comment]
刚刚试了一下Ubuntu 19.04的VM，启动后它自身界面卡顿严重，没法使用，看来是Ubuntu自己的bug。
