### ISSUE TITLE
Combo click the left navigation button in document tab list causes document creation

### ISSUE THREAD

**Issue by hellojianqun** [LiMinggang/madedit-mod#295]
**Please provide the following information**

Madedit-Mod version (or branch):
v 0.4.17

platform/architecture:
Windows x64

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

当打开的文件数量较多导致文档Tab栏出现左右导航按钮时，(左导航按钮可用的状态下) 快速多次点击左导航按钮，会发现最右侧新建了空白文档.

**Comment by LiMinggang** [comment]
我可以肯定地说这不是一个bug，如果你点击过快，操作系统（windows）会把两次单击当作一次双击，双击文件名栏会新建一个文档。

**Comment by hellojianqun** [comment]
好吧……之前还不知道双击文档Tab栏是新建文档的快捷操作.
但是，左右导航按钮是不是可以排除在这个快捷操作的响应区域之外呢？因为当打开较多文档的时候，有时候就会习惯性地想通过快速点击左导航按钮来回到比较前面的文档.

**Comment by LiMinggang** [comment]
这个是wxWidgets提供的，没必要的话不会去动。
