### ISSUE TITLE
查找对话框的文本不能复制了！

### ISSUE THREAD

**Issue by harvey-git** [LiMinggang/madedit-mod#301]
**Please provide the following information**

Madedit-Mod version (or branch):
0.4.18
platform/architecture:
linux/x86_x64
compiler and compiler version:
GCC 9.2.1 20191008 wxWidgets 3.1.3 build 02:30:45 Jan 12 2020
please describe what symptom you see, what you would expect to see instead and how to reproduce it.
昨晚刚刚发现的，选中文字ctrl+f，出现查找对话框，选中文字自动去了查找对话框的文本目标里，然后我点击替换，复制查找对话框的内容想在替换里粘贴，再编辑，这样可以少打字儿，结果发现剪贴板内容不对，反复测试才发现在查找对话框里没法复制文本。

**Comment by LiMinggang** [comment]
你再试试，这部分功能没有动过，刚在windows上试了，没有问题
