### ISSUE TITLE
'瀰' <=> '㳽'

### ISSUE THREAD

**Issue by bluelovers** [LiMinggang/madedit-mod#302]
`瀰` <=> `㳽`

今天在 cjk-conv 那邊發現這個字沒有正確對應

然後試了一下 你這裡也是一樣
本來想在你這裡也修改發PR 但我實在不知道你的對應表怎麼修改xd

**Comment by LiMinggang** [comment]
我的对应表是unicode的十六进制内码。
我有个问题，就是泛中文支持那个功能，目前是按照not safe模式进行匹配的，实际上不够完善，你那里有完整的异体字的对应表么？

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/74236189-abc4c580-4d0b-11ea-9692-38344e7b075a.png)


[temp.zip](https://github.com/LiMinggang/madedit-mod/files/4185603/temp.zip)



這個 zip 來自以下代碼

```ts
import { table_jp, table_plus } from 'cjk-conv/lib/zh/table/table';
import { outputJSON } from 'fs-extra';
import { TABLE, TABLE_SAFE } from 'cjk-conv/lib/jp/core';
import { _greedyTableCacheMap } from 'cjk-conv/lib/zh/table/greedy';

/**
 * 異體字對應表
 */
outputJSON('./temp/table_jp.json', table_jp, {
	spaces: 2
});

/**
 * 異體字對應表(貪婪)
 */
outputJSON('./temp/table_plus.json', table_plus, {
	spaces: 2
});

/**
 * 簡繁日漢字對應表
 */
outputJSON('./temp/jp.TABLE.json', TABLE, {
	spaces: 2
});

/**
 * 簡繁日漢字對應表
 */
outputJSON('./temp/jp.TABLE_SAFE.json', TABLE_SAFE, {
	spaces: 2
});

(() => {
	let ls = _greedyTableCacheMap.entries();

	let maps = [];

	for (let a of ls)
	{
		maps.push(a)
	}

	/**
	 * 貪婪對應表
	 */
	return outputJSON('./temp/_greedyTableCacheMap.json', maps, {
		spaces: 2
	});
})();
```

-----------

我是用以下概念來計算出漢字配對的

- 原始文字
- 轉繁
- 轉簡
- 轉日
- 轉繁之後又轉簡
- 轉簡之後又轉繁
- 漢字轉日文
- 漢字轉繁體
- 漢字轉簡體
- [貪婪配對表](https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/table/greedy.ts) 

以上這些結果得出的字串表合併後成為對應表

https://github.com/bluelovers/cjk-convert/blob/849c7497fdc6708b35b1682d691bb647f9c253f9/lib/zh/table/index.ts#L75

**Comment by LiMinggang** [comment]
主要差在这个貪婪配對表上，没想好怎么实现这个

**Comment by bluelovers** [comment]
table_jp.json 是只有主KEY符合時 才會給出對應表

table_plus.json 是主KEY與對應表內 任何一個字符合就給出對應表

_greedyTableCacheMap.json 我覺得暫時沒必要實現這個 因為那個已經有點偏向搜尋/排序專用的特殊表
