### ISSUE TITLE
希望能够将“列标记”从80列改为可自行配置

### ISSUE THREAD

**Issue by keinejiang** [LiMinggang/madedit-mod#303]
“查看”菜单下有一个“显示第80列的提示标记”，能否将这个固定的“80列”改为“可以用户自行配置在某一列”显示提示标记。

另外，希望能加快发布频率，有些许bug不太要紧。最近半年发布一次太慢了。再次感谢这个项目能够延续下去。

**Comment by LiMinggang** [comment]
现在的主要动力是我自己在用这个编辑器。目前我只有闲暇时间来维护这个项目，工作忙就顾不上啦。而且也没太多人提比较现实的需求或者bug，需要积累一些修改再发布。毕竟多平台发布。

如果有人能帮忙搞定nightly release就不存在这个问题了。
