### ISSUE TITLE
bug: 脚本

### ISSUE THREAD

**Issue by sir2k** [LiMinggang/madedit-mod#304]
环境：
madedit-mod 0.4.18+ win10 ltsc

bug复现：
1、使用下列脚本获取当前文件名：
me = MadEdit()
s=me.GetFileName()
MsgBox(s)
me=None

2、如果文件名是全英文的可以显示带路径的文件名
如果文件名包含有中文则显示一个空串

3、原本想借助脚本实现文件名是“未命名”时，存盘时会自动以第一行文字作为默认文件名

**Comment by LiMinggang** [comment]
这个应该是字符串encoding问题

**Comment by LiMinggang** [comment]
下个版本你可以用python的print去打印debug信息
![Image 2](https://user-images.githubusercontent.com/4847132/75221062-d454c100-57db-11ea-8574-d365874333c6.png)
