### ISSUE TITLE
搜尋對話框的輸入部分字會被切掉

### ISSUE THREAD

**Issue by kesdoputr** [LiMinggang/madedit-mod#305]
**Please provide the following information**

Madedit-Mod version (or branch):
0.4.18 x64
platform/architecture:
windows 7 SP1 x64

你好
當我把字型設成Arial Unicode MS的時候(大小為預設的12)
**UTF-8=Arial Unicode MS
SHIFT-JIS=Arial Unicode MS
BIG5=Arial Unicode MS
GBK=Arial Unicode MS**

按ctrl+f出來的搜尋視窗，在打字的時候發現0.4.18版本會把下面的字切掉
如圖，我搜尋的是小寫的progress
在0.4.17的時候是正常的
https://i.imgur.com/hxagtaM.png
在0.4.18的時候p和g這兩個字的下方都被切掉了
https://i.imgur.com/Hjj1QAK.png

兩張圖比起來好像0.4.18版的按鈕和輸入的地方都小了一點？

還是說0.4.18版我得調整什麼設定？謝謝

**Comment by LiMinggang** [comment]
感觉是wxWidets的问题。你可以把输入框拉大点

**Comment by LiMinggang** [comment]
![image](https://user-images.githubusercontent.com/4847132/76514097-53135480-6492-11ea-893d-c8d9a8573246.png)

**Comment by kesdoputr** [comment]
現在是這樣用的，不過看圖可以知道我兩個版本都調最小
的時候0.4.17的大小比較剛好，調成兩行或三行感覺又太大了點

**Comment by LiMinggang** [comment]
这个倒感觉不是程序bug，像是编译，SDK之类的问题。我在win7 64简体版和win10 64上都没看到类似问题，倒是在Linux版本上见过。
你是不是windows设置的缩放字体？

**Comment by kesdoputr** [comment]
我調成英文的也是一樣狀況，沒改字型前預設的字型Courier New不會切到(不過0.4.18的框框還是比較窄)
我設成Arial Unicode MS就會被切，我是直接讓他重新產生設定檔，只改了字型，其他都沒動過

**Comment by LiMinggang** [comment]
我这简体版windows 7 64上没有你说的那个Arial Unicode MS，只有Arial和Arial Black，都OK。你这个字体是自己安装的吗？

**Comment by LiMinggang** [comment]
发布版是在Win10+VS2017编译的。我这边windows 7上用的是VS2019编译的。你愿意试试吗？

**Comment by kesdoputr** [comment]
好啊，在sourceforge上能抓到用vs2019編的版本嗎？

另外Arial Unicode MS這邊可以下到
http://www.xiazaiziti.com/19862.html

**Comment by LiMinggang** [comment]
我给你放到preview那个目录里了

**Comment by LiMinggang** [comment]
我试用你的字体好像也OK
![image](https://user-images.githubusercontent.com/4847132/76676388-d69d8480-65fd-11ea-8e30-c30fad9dfe4d.png)

**Comment by kesdoputr** [comment]
可以試試看搜尋progress嗎？我的p和g小寫的下面會被切掉

感謝回覆，抓了preview裡頭的版本了，狀況好像是一樣的

如圖可見，我試著打了所有的英文小寫,不少字的下半邊都會被切掉
https://i.imgur.com/DvrZXa3.png

**Comment by LiMinggang** [comment]
哦，Arial black和Arial unicode MS都有这个问题。我得换几个wxWdigets的版本来试试这个问题了。估计是wxWdigets的问题

**Comment by LiMinggang** [comment]
没有找到问题所在，现在用调整字符的base height解决

**Comment by LiMinggang** [comment]
我更新了preview，你试试

**Comment by kesdoputr** [comment]
試了新preview，看的出來輸入框比較寬了，目前沒有字被切掉的狀況了，謝謝。
