### ISSUE TITLE
你好，是否可以添加对json格式化

### ISSUE THREAD

**Issue by songhtdo** [LiMinggang/madedit-mod#306]
你好。
我是因为抛弃Nodepad++，才找到madedit-mod程序的，
现在json数据在开发程序时，使用频率越来越多了，会有很多格式化的地方。
虽然也可以使用在线工具，或者专门工具，但确实很希望可以在madedit-mod中提供这个功能。

或者在python插件中可以支持第三方py，这样子就可以自己扩展了。
非常感谢你的工作。

**Comment by LiMinggang** [comment]
Python因为做了简化，去掉了regex之类的，支持python程序做格式化比较难。我看看有无C/C++版本的。
