### ISSUE TITLE
0.4.19 x64打不開

### ISSUE THREAD

**Issue by kesdoputr** [LiMinggang/madedit-mod#307]
**Please provide the following information**

Madedit-Mod version (or branch):
`MadEdit-Mod0.4.19_X64.7z`
platform/architecture:
Windows 7 SP1 x64

你好，抓了最新的0.4.19，x64的版本打不開會直接crash，x86的沒有問題
另外在執行檔的內容裡頭顯示的還是0.4.18
![Clip325](https://user-images.githubusercontent.com/16981364/84565361-2a557080-ad9b-11ea-8a6b-61e145d4a84f.png)

**Comment by LiMinggang** [comment]
Oh, really!  我会再次上传

**Comment by LiMinggang** [comment]
没有实质更新，放心使用。

**Comment by kesdoputr** [comment]
重新下載之後都正常了，感謝。
