### ISSUE TITLE
是否可以添加一个按Alt+Up / down移动文本行功能

### ISSUE THREAD

**Issue by songhtdo** [LiMinggang/madedit-mod#308]
你好，非常感谢上次你的json格式化功能，我已经把其他文本编辑器都给卸载了。

再麻烦问一下，是否可以添加按Alt+UP/DOWN移动文本行功能。
这个在一些编辑过程中，也会使用到。
当然这个优先级不高，用剪切+粘贴也是可以实现的。
再一次感谢你！

**Comment by LiMinggang** [comment]
是选择部分，还是光标当前行？

**Comment by LiMinggang** [comment]
json的你测试下有没有缩进的bug，我是改了一个取得当前缩进的bug，但是没有太多测试。

**Comment by songhtdo** [comment]
移动文本行的那个问题，我看别的编辑器是这样干的，
如果没有选择内容时，是移动当前行；
如果选择内容时，由涉及到的文本行，即使是这一行部分选择，也要全行移动。

**Comment by songhtdo** [comment]
json格式化，我目前没有发现缩进方面有bug。
很好用的，再次感谢！

**Comment by LiMinggang** [comment]
你用的哪个编辑器？我要试用研究一下

**Comment by songhtdo** [comment]
编辑器，vscode / editplus，你还可以试用它的列模式。

**Comment by LiMinggang** [comment]
列模式是支持的，你说的这个编辑方式是在列模式下？

**Comment by songhtdo** [comment]
> 列模式是支持的，你说的这个编辑方式是在列模式下？

不好意思，最近几天没有来得及回复你。
是的MadEdit-mod也是支持列模式，
和vscode等相比，ME的列模式是静态型模式，
vscode等是动态型模式，按住Alt时为列，松开时为普通模式。

**Comment by LiMinggang** [comment]
我是不喜欢编辑文本的同时还得腾出一只手按住alt，这个是在是不方便。举例：如果让你对上千行文本进行列编辑，选择文本得多费劲。没觉得按alt这个有啥优势。

**Comment by songhtdo** [comment]
> 我是不喜欢编辑文本的同时还得腾出一只手按住alt，这个是在是不方便。举例：如果让你对上千行文本进行列编辑，选择文本得多费劲。没觉得按alt这个有啥优势。

这个alt切换的功能，确实是一个见仁见智的操作习惯小问题而已。
