### ISSUE TITLE
新增的jsonformat功能，中文字符会被转成utf字符

### ISSUE THREAD

**Issue by songhtdo** [LiMinggang/madedit-mod#309]
你好。
上次新增的jsonformat功能，最近发现会把中文字符串改成utf8字符。比如：
{"name":"中华人民共和国",age:70}

格式化后：
{
  "age" : 70,
  "name" : "\u00e4\u00b8\u00ad\u00e5\u008d\u008e\u00e4\u00ba\u00ba\u00e6\u00b0\u0091\u00e5\u0085\u00b1\u00e5\u0092\u008c\u00e5\u009b\u00bd"
}
这应该算是一个bug.

**Comment by LiMinggang** [comment]
JSON是老外的代码，都是不支持Unicode的，我是把文本转成UTF8来避免问题，后面忘了转回来了。

**Comment by LiMinggang** [comment]
Fixed in master

**Comment by songhtdo** [comment]
太棒了！
