### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by freemagnet** [LiMinggang/madedit-mod#313]
**Please provide the following information**

Madedit-Mod version (or branch):MadEdit-Mod0.4.19_X86.7z

platform/architecture:windows10

compiler and compiler version:0.4.19

MadEdit-Mod0.4.19_X86.7z cannot be downloaded on the sourceforge website, and the x64 version can be downloaded

**Comment by LiMinggang** [comment]
I think it should be a problem of SF. You have to wait for them to fix the issue.
