### ISSUE TITLE
搜索替换窗口中的输入框调大了之后不能再缩小了！

### ISSUE THREAD

**Issue by zhulaojianke** [LiMinggang/madedit-mod#316]
**Please provide the following information**

Madedit-Mod version (or branch): 0.4.19

platform/architecture: Win7 64位 旗舰版

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.

![image](https://user-images.githubusercontent.com/16543111/110790100-970a8680-82ab-11eb-96ad-2dc7a84fa4c2.png)
我这次要替换的文本字数有些多，还有换行，所以把输入框调大了想看看替换内容有没有问题，然后就出现这种情况了。希望能解决这个bug。

**Comment by LiMinggang** [comment]
Fixed by 039b19253c50b4f83c35fabf9d300e73f1b5ea02
