### ISSUE TITLE
“多文件查找/替换”窗口，查找内容文本框无上下文菜单。

### ISSUE THREAD

**Issue by LD-531** [LiMinggang/madedit-mod#320]
0.5.0α2
W7 x64

“多文件查找/替换”窗口，查找内容文本框无上下文菜单。

**Comment by LiMinggang** [comment]
你这说的是什么问题？说清楚一些，贴图什么的，怎么复现？

**Comment by LD-531** [comment]
![contextmenumissed](https://user-images.githubusercontent.com/58158624/129777811-e0a8744a-f070-4a90-9b06-e7a4d0f75923.png)

**Comment by LiMinggang** [comment]
哦，你是说想给这个加上想搜索替换那个一样的右键菜单吧？
