### ISSUE TITLE
EBCDIC

### ISSUE THREAD

**Issue by Johan-Ekdahl** [LiMinggang/madedit-mod#321]
**Please provide the following information**

Madedit-Mod version (or branch):
0.5.0a2
platform/architecture:
WinX64
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and how to reproduce it.
Is there any chance to get support for EBCDIC-encoding (EBCDIC 278) or some kind feature where you can load/use a user defined codepage?

**Comment by LiMinggang** [comment]
Not sure. The encoding support in MadEdit is mainly from OS running it or backported from other encoding support package such as libiconv.

**Comment by Johan-Ekdahl** [comment]
Ok, but it would be nice if you could take into consideration. Another feature that would be really nice is full support for big files in text mode, than I could use MadEdit instead of the obsolete application (Vedit) that I'm using today.

**Comment by Johan-Ekdahl** [comment]
I googled for some kind of encoding package with EBCDIC support and found this: https://github.com/limes-datentechnik-gmbh/libiconv, I don't know if this is something you could use?

**Comment by Johan-Ekdahl** [comment]
Thank you for adding EBCDIC, I have attached a small file for testing. 
I need EBCDIC support because I sometimes have to handle information from old mainframes.
[small_file_EBCDIC.txt](https://github.com/LiMinggang/madedit-mod/files/7386565/small_file_EBCDIC.txt)

**Comment by Johan-Ekdahl** [comment]
Thank you for adding EBCDIC, I have attached a small file for testing.
I need EBCDIC support because I sometimes have to handle information from old mainframes.
[small_file_EBCDIC.txt](https://github.com/LiMinggang/madedit-mod/files/7386620/small_file_EBCDIC.txt)
