### ISSUE TITLE
Aarch64 version enclosed

### ISSUE THREAD

**Issue by EMLommers** [LiMinggang/madedit-mod#324]
Hi,
I modified the source and working on ARM Aarch64 Debian Bookwor/sid
See enclosed. You have to diff yourself.
[madedit-mod-master.zip](https://github.com/LiMinggang/madedit-mod/files/8217746/madedit-mod-master.zip)
!
Regards,
EMLommers

**Comment by LiMinggang** [comment]
Hi, would you please sent the patches(git format-patches -numofpatches) to
me instead of a whole bunch of source code? It's hard for me to figure out
what was changed actually by you.
Thanks

**Comment by LiMinggang** [comment]
Fixed in 0.4.20

**Comment by wuzhaohui100** [comment]
补丁没有补全，在arm64架构上编译报错
In file included from ../minipython/Include/Python.h:11,
                 from ../src/EmbeddedPython.hpp:11,
                 from ../src/EmbeddedPython.cpp:8:
../minipython/Include/pyconfig.h:31:22: fatal error: ../../../config.h: 没有那个文件或目录
   31 |             #include "../../../config.h"
      |                      ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by LiMinggang** [comment]
有没有试过去掉这一行或者是把"../../../config.h"替换成"../../config.h"?
