### ISSUE TITLE
临时的宏语句能否支持re模块？

### ISSUE THREAD

**Issue by sln-1550** [LiMinggang/madedit-mod#330]
我目前用的版本是4.20
临时的宏语句中加入import re会提示ImportError: No module named re
请问能否增加re到内置模块中？

**Comment by sln-1550** [comment]
看python目录里的介绍研究了一下，好像是用的Boost.Python。
我觉得numpy这个模块不会用到，我想去掉这个并且加上re模块，这样程序代码应该不会增加多少，但是不知道怎么操作，能否给个稍微详细的编译说明？

**Comment by LiMinggang** [comment]
程序中用做内嵌脚本的是基于python 2.7的最新的代码简化的，代码在minipython目录。简化版是[阿呆](https://www.adintr.com/)做的。Python嵌入C++
https://www.adintr.com/about/blogs.html

**Comment by LiMinggang** [comment]
编辑器本身是用boost.xpressive做正则的

**Comment by LiMinggang** [comment]
加回来估计难，python的regex本身有python代码，不是C的

**Comment by sln-1550** [comment]
研究了一下，重新编译搞定了

https://github.com/LiMinggang/madedit-mod/assets/59176056/c9a6b01a-6934-44e6-b368-2708ee5d13e8

**Comment by LiMinggang** [comment]
标尺看着不错，愿意共享patch吗？

**Comment by LiMinggang** [comment]
挺好，如果是一些可选的功能，可以通过增加配置选项来让用户选择

**Comment by sln-1550** [comment]
这些对原版改动很大，也我当时没有加可选的代码和配置，没有办法做到可选

**Comment by LiMinggang** [comment]
发PR，或者给我patch我看看

**Comment by sln-1550** [comment]
已提交PR
