### ISSUE TITLE
not enough space for translated string

### ISSUE THREAD

**Issue by nikoss** [LiMinggang/madedit-mod#83]
Hi, I am currently trying to translate Madedit-mod into Greek.
Here is a small GUI issue...

In the window of...
Preferences --> Spellcheck
the space is limited, in option...
Enable Personal Dictionary

![madedit-mod_-_spellcheck_001](https://cloud.githubusercontent.com/assets/4921343/11169329/34b059fa-8bbd-11e5-81b4-87309b984d3f.jpg)

**Comment by LiMinggang** [comment]
Will fix it in the next release.

**Comment by LiMinggang** [comment]
Hi, nikoss, would you please tell me the version of MadEdit-Mod you used? I found the drop down box is still too small and I think I had fixed the issue.
Also, are you using it on Ubuntu? It looks like so.

**Comment by LiMinggang** [comment]
By the way, I enlarged the size of "Enable Personal Dictionary". Would you please share the Greek translation you are working on so that I can have a try.

**Comment by LiMinggang** [comment]
Another tip: you can copy the translation of Astyle formatter in Code::Block if they had because I did copy all the strings from it as the GUI of MadEdit.

**Comment by nikoss** [comment]
Hi LiMinggang ,  


I use...
   madedit-mod-0.3.7-1.x86_64_Mageia5.rpm
   MadEdit-Mod 0.3.7 x86_x64 GCC 4.9.2 build 22:46:19 Sep 17 2015

I see, now, that there is an update.

-----
-----
Here is the greek translation, so far ( el.po ):
http://a-gnu-linux-wiki.awardspace.com/arxeia/madedit-mod.el.po

-----
-----
> you can copy the translation of Astyle formatter in Code::Block 

I don't know anything about coding (I have no idea what the above sentence means :(  )

**Comment by LiMinggang** [comment]
No problem. Code::Block is an IDE for C++.  I just want to save your effort and time. I'll have a double check if I can find the web page of Code::Blocks that has the translation of Astyle.

**Comment by LiMinggang** [comment]
I'll also provide you a private build which has fix for both of the issues you found.

**Comment by nikoss** [comment]
Thanks, but no need to go to all that trouble. After all, these are minor issues.

Here is how this dialog looks in...
MadEdit-Mod 0.3.8 x86_x64 GCC 4.9.2 build 13:12:08 Oct 27 2015

![madedit-mod_-_spellcheck_002](https://cloud.githubusercontent.com/assets/4921343/11269200/38e16272-8ebe-11e5-87c1-26cfbbbd4e82.jpg)

**Comment by LiMinggang** [comment]
Not a big deal. I had finished dynamically discovering for translation. So, the new translation would show up if you put it under the directory. I'll verify it with yours.

After basic test, I'll give you a build if you want to have a try.

**Comment by LiMinggang** [comment]
Do you mind if I add your translation into next release? You can send your update at your convenience.

**Comment by nikoss** [comment]
> So, the new translation would show up if you put it under the directory.

In Linux it is as simple as that. That's how I test the translation:
![madedit-mod_-_translation_001](https://cloud.githubusercontent.com/assets/4921343/11270420/8c5ff8e2-8ec7-11e5-96f8-dd446eb76a9f.jpg)

The" madedit-mod.pot version" and the "Madeit-mod program version" might not match... but no big deal... because it is so easy.. and I always see the latest translation, and corrections...

----
----

> Do you mind if I add your translation into next release?

Not at all.

**Comment by nikoss** [comment]
> After basic test, I'll give you a build if you want to have a try.

Sure, why not. But as I said this  " dynamically discovering for translation" is already working in my system. Maybe it's the default function in gettext .

**Comment by LiMinggang** [comment]
By "dynamically", I mean you could choose your favorite language on the platform that has another language(other than your favorite one) as the default language. Eg, you can choose Greek on Mageia English. Or, like me, working on Win7 English but want to use Chinese.
Current, it was hardcoded in source code.

**Comment by LiMinggang** [comment]
Greek would be shown like below under non-Greek OS.
![2015-11-20 12_03_40-](https://cloud.githubusercontent.com/assets/4847132/11291733/cf526f7e-8f7e-11e5-9626-49edb4cb460d.png)

**Comment by LiMinggang** [comment]
Done. The preview version has been uploaded to https://sourceforge.net/projects/madedit-mod/files/Preview/
![2015-11-20 15_49_47-mageia 5 64bit - vmware player non-commercial use only](https://cloud.githubusercontent.com/assets/4847132/11294608/d0897b00-8f9f-11e5-8882-e1f0c405dac1.png)

**Comment by nikoss** [comment]
I installed the Preview rpm, and... one letter missing.
![madedit-mod_-_spellcheck_003](https://cloud.githubusercontent.com/assets/4921343/11324627/c1a9f3a2-913f-11e5-9e81-dfdf6b3c7344.jpg)

Maybe it doesn't adapt to the font size (and theme?)
I use FreeSans font, size 12, BlackMate theme, and Mate desktop.

----

> you can choose Greek on Mageia English

Ok, I understand it now.

**Comment by LiMinggang** [comment]
OK. Let me check it and enlarge it again. BTW, which one is better for Greek, "el" or "el_GR"? I'm not a n expert.

**Comment by nikoss** [comment]
Generic "el" is the norm. "el_GR" and "el_CY" are there, but noone ever really uses them.

**Comment by LiMinggang** [comment]
OK. Got it.

**Comment by LiMinggang** [comment]
I'm trying to porting the translation of source formatter for Greek. Will
inform you if I'm done

**Comment by LiMinggang** [comment]
Tired, nothing help on the translation :(

**Comment by nikoss** [comment]
What is a "source formatter for Greek" ?

**Comment by LiMinggang** [comment]
Sorry for misleading you. I mean Greek translation for the Source formatter
tab on the Option Dialog. However, I did not find the translation in
Codeblocks. They did not translate it yet. So, forget about it.

**Comment by nikoss** [comment]
Some more lack of space. In Options window --> Source Formatter tab .
I started shortening some of the strings, but then I realised that too many of them where problematic.
And if I make them too short, they won't make any sense.

My system currently:
Mageia 5, 32bit
madedit-mod-0.4.4-1.i586_Mageia4.1_Fedora22.rpm

![source_formatter_001](https://cloud.githubusercontent.com/assets/4921343/16902300/0f89db7a-4c64-11e6-8743-f542d2cd5c91.jpg)
![source_formatter_002](https://cloud.githubusercontent.com/assets/4921343/16902298/0f7965ba-4c64-11e6-91fb-cdaa8b7f7e91.jpg)
![source_formatter_003](https://cloud.githubusercontent.com/assets/4921343/16902299/0f84b78a-4c64-11e6-8cef-29c71fc45600.jpg)

**Comment by LiMinggang** [comment]
To be fixed.
